### ISSUE TITLE
roperty 'idleTimer' does not exist on type 'ReactIdleTimer'

### ISSUE THREAD

**Issue by ncmadhan1989** [SupremeTechnopriest/react-idle-timer#104]
How to use this is react typescript,i getting an following error
"Property 'idleTimer' does not exist on type 'ReactIdleTimer'"

**Comment by SupremeTechnopriest** [comment]
Hi @ncmadhan1989, 

Im going to need more info on your problem.  Please, If you expect me to take time out of my day to help you, at least take the time to write more than two sentences about your issue.  Some sample code of how you are attempting to use the component would be helpful. 

Thanks!

**Comment by HPS-RobRice** [comment]
@ncmadhan1989 making a wild guess here. You may be trying to pass `idleTimer` as a normal prop like this:
`<IdleTimer idleTimer=this.idleTimer ... />`

When it should actually be passed like this:
`<IdleTimer ref={ref => {this.idleTimer = ref;}} ... />`

The readme on this repo shows an example with more detail: https://github.com/SupremeTechnopriest/react-idle-timer

**Comment by SupremeTechnopriest** [comment]
Closing this issue.  @HPS-RobRice's comment is likely the solution to the problem.  Have not received a response from @ncmadhan1989.
