### ISSUE TITLE
yarn example .\scripts\example' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by lavebug** [SupremeTechnopriest/react-idle-timer#108]
yarn run v1.22.4
$ ./scripts/example
'.\scripts\example' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Virtualbox v6.0.20 Windows 10 1909 yarn 1.22.4 

can windows run unix ./script command?

**Comment by SupremeTechnopriest** [comment]
It can if you use wsl, git bash or similar (which I highly recommend).  Windows default shell is absolute trash.

**Comment by SupremeTechnopriest** [comment]
I don't plan on adding support for `.bat` files but if you are dead set on using powershell or whatever, feel free to submit a PR.
