### ISSUE TITLE
Updated Document Triggers Inactive

### ISSUE THREAD

**Issue by FlyRocketDrones** [SupremeTechnopriest/react-idle-timer#109]
Hi,

I have a page within my app that shows reports. Reports part of the page gets loaded couple seconds after the page load. Therefore, when IdleTimer has document as element selected, iframe content doesn't exist. Therefore, when Iframe content loads and user is moving their mouse around, IdleTimer does not recognize that as action. Unless user's mouse go outside the iframe area into the document area that existed at initial load. I tried:

 ` const [currentDocument, setcurrentDocument] = useState(document);`

using this to set initial document then update it 1 minute after page initial load by

```
 setTimeout(function () {
    setcurrentDocument(document);
    console.log(123);
    console.log(currentDocument);
  }, 1000 * ); // every 1 minute check
```

But it didn't help either. How can I make sure if document updates IdleTimer grabs the new document?

**Comment by SupremeTechnopriest** [comment]
An iFrame is technically a separate site embedded in your site (main frame).  It is responsible for its own events.  I'm pretty sure you will need to mount IdleTimer on the iFrame's website.  You could then use postmessage API to pass the events to the main frame if needed.
