### ISSUE TITLE
Cant find variable document

### ISSUE THREAD

**Issue by AkshatS2196** [SupremeTechnopriest/react-idle-timer#112]
Getting the error 
ReferenceError: Can't find variable: document

**Comment by SupremeTechnopriest** [comment]
This component is used by millions of people. They all have no problem with document.  I am going to start immediately closing issues where people don't take the time to write out a detailed description of their problem. 

My guess is you aren't using the component correctly, or you are trying to use it in a non browser environment.  If you want help, take the time to write a complete issue. Include some examples of how you are trying to use the component, the environment you are using it in and a complete stack trace of the error.
