### ISSUE TITLE
getRemainingTime is not working

### ISSUE THREAD

**Issue by SPineapple** [SupremeTechnopriest/react-idle-timer#113]
I keep getting zero value and it is not updating, neither getElapsedTime, help please?

**Comment by SupremeTechnopriest** [comment]
Hi @SPineapple, Can you please post how you are trying to use the component and how you are calling getElapsedTime?  I need more info in order to help.

**Comment by SupremeTechnopriest** [comment]
If you take a look at the example https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/example/src/App.js#L34, The getRemainingTime works here.

**Comment by SPineapple** [comment]
This is where I am using it with useRef hooks :

```
const idleTimerRef = useRef(null)
const onIdle = () => {
        if (isTimedOut) {
            console.log("Logout");
        } else {
            setIsModalOpen(true)
            console.log("time remaining", idleTimerRef.current.getRemainingTime());
            setIsTimedOut(true);
        }
    }

<IdleTimer debounce={250} onAction={onAction} onIdle={onIdle} onActive={onActive} ref={idleTimerRef} timeout={5 * 1000}>
```

**Comment by SPineapple** [comment]
> If you take a look at the example https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/example/src/App.js#L34, The getRemainingTime works here.

ohh sorry I missed out setInterval, I thought it would return the value directly. Thanks for the reference!

**Comment by SupremeTechnopriest** [comment]
You shouldn't need the setInterval thats just so it updates every second for the example.  Let me add a test case.  I suspect its the useRef hook.  Im working on a hook version of the component, but Ill do a little test to see whats going on and get back to you.

**Comment by SPineapple** [comment]
Okay, thanks.

**Comment by SupremeTechnopriest** [comment]
Ah, actually i think the issue is that you are checking the remaining time inside the onIdle callback.  If onIdle is called it means that the remaining time is 0.  What happens if you check remaining time in your onAction callback?  It should work then.

**Comment by SPineapple** [comment]
yes I get the number, but I am displaying remaining time when idle and triggers logout, so when its in onAction callback I don't have any benefit of it because timeout is already doing it? maybe I missed something else..

**Comment by SupremeTechnopriest** [comment]
I see, so when a user goes idle, you want to give them 10 seconds or so before you log then out?

**Comment by SPineapple** [comment]
yes exactly.

**Comment by SupremeTechnopriest** [comment]
You should definitely use your own `setTimeout` inside the idle callback for that.  `getRemainingTime` returns how long until the user will be considered Idle.  Idle timer doesn't have a mechanism for what you want, but a lot of people do exactly that with their own `setTimeout`.

**Comment by SPineapple** [comment]
Okay, will try it out, thanks!

**Comment by SupremeTechnopriest** [comment]
Just make sure that onActive clears your custom timeout.  Something like

```js
const onIdle = () => {
  this.idleTimeout = setTimeout(() => {
    // Your logic
  }, 10000)
}

const onActive = () => {
  if (this.idleTimeout) clearTimeout(this.idleTimeout)
}```

**Comment by SupremeTechnopriest** [comment]
Cool feel free to re open the issue if you have any problems.  Love your Totoro icon btw. ♥️ Ghibli
