### ISSUE TITLE
Reference error cant find variable:document

### ISSUE THREAD

**Issue by AkshatS2196** [SupremeTechnopriest/react-idle-timer#114]
![Screenshot_2020-06-11-16-25-12-24 1](https://user-images.githubusercontent.com/25604509/84740248-af729c80-afca-11ea-969b-2d39f43eee31.png)

My code:

import React, {useRef} from 'react';
import IdleTimer from 'react-idle-timer';

export default function IdleTimerContainer() {
  const idleTimerRef = useRef(null);
  const onActive = () => {
    console.log('Time Restarted', this.idleTimer.reset());
  };

  const onIdle = () => {
    console.log('user is idle');
    this.props.navigation.navigate('Login');
  };
  return (
    <IdleTimer
      ref={idleTimerRef}
      element={document}
      timeout={15 * 1000}
      onIdle={this.onIdle}
      onActive={this.onActive}
    />
  );
}

Error: Reference Error: Cant find variable: document

**Comment by SupremeTechnopriest** [comment]
It looks like this is a lint error. It doesn’t know that document is a global. I’m not sure what metro does, but I’m willing to bet the problem is there. How is your app bundled?

**Comment by AkshatS2196** [comment]
the command i hit for building the app: "react-native run-android --port=8088"

**Comment by SupremeTechnopriest** [comment]
Try removing the element prop and using the default.  It defaults to `document` anyway, but has extra protection for server side rendering.

**Comment by AkshatS2196** [comment]
You means element: default ?

**Comment by SupremeTechnopriest** [comment]
Just remove it all together:

```js
<IdleTimer
ref={idleTimerRef}
timeout={15 * 1000}
onIdle={this.onIdle}
onActive={this.onActive}
/>```

**Comment by AkshatS2196** [comment]
The issue is still their on the line where I Imported IdleTimer

**Comment by SupremeTechnopriest** [comment]
Looking around at similar issues, it looks like it's a server side rendering problem.  Can you post your webpack/ babel config?

**Comment by SupremeTechnopriest** [comment]
@AkshatS2196 Were you able to sort this out on your own?

**Comment by AkshatS2196** [comment]
No, I was not able to solve it.. And I am running this on an Android Phone
so no bable config

**Comment by SupremeTechnopriest** [comment]
Are you able to share the repository you are working on? I need to see the entire scope and possibly run it locally to see what’s going on. I’m almost certain it has to do with server side rendering.

**Comment by SupremeTechnopriest** [comment]
Going to close this issue for now as there hasn't been any activity on it in some time.  If you can put together a reproducible example repository, I'd be happy to take a look for you.

**Comment by kuriel-dev** [comment]
Hi @SupremeTechnopriest  this issue is totally related to front-end apps with Android and iOS, obviously "document" is not part of a mobile react ecosystem.

You should, please:

- fix any document implementation to be able to use this package on React Native

or

- make this package friendly and ignoring any web implementation when runing on mobile

this error happens even when not using this package and ONLY is installed on a React Native project.

**Comment by SupremeTechnopriest** [comment]
This library is not designed to work with react-native. I'm not sure how events work in rn.  I'd be open to reviewing a PR to add support, but its not something I am interested in maintaining. I don't have any react native projects.
