### ISSUE TITLE
No API to clear the timer!

### ISSUE THREAD

**Issue by collegewap** [SupremeTechnopriest/react-idle-timer#115]
pause() doesn't clear the timer. It just pauses it and when the component is mounted back, old timer is back!
I need to clear the old timer and create a new one. Since the variables inside onIdle change between renders, I need to have a new timer. How do I clear the old timer?

Note: I am loading the react app inside another non-react app. So for some reason componentWillUnmount will not be called when the user goes back from react to non-react. However, I do get an event when the user clicks on the back button.

**Comment by SupremeTechnopriest** [comment]
There is an api to clear the timer.  Its `reset()`.

**Comment by SupremeTechnopriest** [comment]
It's literally the first method documented in the README.
