### ISSUE TITLE
IdleTimer not resetting when used with setTimeout

### ISSUE THREAD

**Issue by fluxquantum** [SupremeTechnopriest/react-idle-timer#116]
Hello @SupremeTechnopriest - thanks for creating and supporting this library. 

I am trying to implement a lightweight session timeout functionality for my react app. I am leveraging your idleTimer to trigger a window.confirm prompt. Depending on the response returned - I am either letting the session stay active or performing a setTimeout(timeout, n).

I am coming across two issues, 1) I'd like there to be a timeout regardless while the confirm window is open - if the user remains idle.

2) When I click okay to not end the session it looks like the idleTimer isn't detecting idle action after the fact. Based on my testing, it'll idle out twice in a row and then not detect it afterwards unless I perform another action.

Does my approach work with this library for item 1) and for item 2) am I possibly not setting the correct IdleTimer features?

Some code snippets from my component for context:

const userSessionTimeoutRef = useRef(null);

***onIdle function***

let confirmed = window.confirm("You have been idle for awhile. Click OK to keep the session active.");
userSessionTimeoutRef.current = setTimeout(timeOut);

if(!confirmed) {
            // Execute timeOut immediately
            console.log("User let session time out.");
            userSessionTimeoutRef.current = setTimeout(timeOut);
        } else {
            // Reset currently reference countdown on call to 'timeOut' function.
            console.log("User chose to keep session active.");
        }

<IdleTimer
                ref={timeoutContainerRef}
                timeout={parseInt(process.env.REACT_APP_USER_SESSION_TIMEOUT_MILLIS)}
                onIdle={onIdle}
            ></IdleTimer>

Thank you for your time.

**Comment by SupremeTechnopriest** [comment]
Hi @fluxquantum 

What you are implementing is the most common use case for IdleTimer.  What you want to do is get a ref to the IdleTimer instance and use the `reset()` function to restart IdleTimer if your user clicks continue.  That should get you where you want to be!

Also, all the methods IdleTimer exposes are documented here https://github.com/SupremeTechnopriest/react-idle-timer#methods. 

Feel free to reopen this issue if this doesn't resolve your problem (though Im pretty sure it will).
