### ISSUE TITLE
Remove React as direct dependency

### ISSUE THREAD

**Issue by maxdeviant** [SupremeTechnopriest/react-idle-timer#12]
We are using react-idle-timer in our project, and I just realized that including it as a dependency *massively* increases the bundle size. This is due to React being included as a direct dependency of the library.

We should include all of the React libraries as `"peerDependencies"` in `package.json`. This is how [Material UI](https://github.com/callemall/material-ui/blob/master/package.json#L40-L44), [React Bootstrap](https://github.com/react-bootstrap/react-bootstrap/blob/master/package.json#L40-L43) handle this, and I believe other libraries do the same.

You can see below that react-idle-timer is **7.8% (!)** of our bundle:

![image](https://cloud.githubusercontent.com/assets/1486634/18011084/8f00f172-6b81-11e6-9c8a-8972465e820b.png)

7.3% of which is contributed by React:

![image](https://cloud.githubusercontent.com/assets/1486634/18011096/9be2ea30-6b81-11e6-81ba-1311854f37fb.png)

**Comment by SupremeTechnopriest** [comment]
Hmm thats odd.  I was pretty sure I set it as a peer dependency.  Ill make that quick change and publish a new build.

**Comment by maxdeviant** [comment]
After some further investigation, I noticed that we were still using an older version of react-idle-timer, which used an older version of React as a dependency. Updating to the latest version of react-idle-timer brought the two versions of React into sync, and now the library is sized appropriately:

![image](https://cloud.githubusercontent.com/assets/1486634/18011522/8c3ea3ec-6b83-11e6-973b-d00646d8686f.png)

However, I think that we should definitely be including React as a peer dependency to prevent this in the future.

**Comment by SupremeTechnopriest** [comment]
this should be resolved in `1.3.1` I also added `standard-version` for nice change logs.

**Comment by SupremeTechnopriest** [comment]
sorry `1.3.2` made the peer dependencies only care about the major version number. eg React 15.x.x

**Comment by maxdeviant** [comment]
Thanks for the quick resolution :smile:

**Comment by SupremeTechnopriest** [comment]
Always!
