### ISSUE TITLE
Unable to pass in custom events in useIdleTimer options

### ISSUE THREAD

**Issue by kaihengann** [SupremeTechnopriest/react-idle-timer#120]
First of all, thanks for creating this library. I am having issues passing in a custom array of events to bind as the events option only takes in an EVENTS type. Also it seems the EVENTS enum is not exported, so I have no way to customise the events. Am I missing something? Would appreciate some help. Thanks.

**Comment by SupremeTechnopriest** [comment]
Hey @kaihengann Adding that events enum was new in this patch.  There are probably some issues...   I personally don't use typescript.  I find it to be more trouble than it's worth.  I will export that enum, but could you tell which event you would like to use that isn't there?  I would like this to be a complete list of possible events.

Thanks!

**Comment by SupremeTechnopriest** [comment]
@kaihengann Resolved this issue.  Published version `4.3.1` to NPM.  Reopen if you are still having issues.

**Comment by kaihengann** [comment]
Hey @SupremeTechnopriest ,thanks for the quick reply. It seems you have exported a type instead of the enum itself, so the issue still exists. I am actually trying to omit some of the events from the default ones.

**Comment by SupremeTechnopriest** [comment]
Turns out you can't export an enum from the `.d.ts` file... It has to be a type.  That fixes the intellisense. If you want to omit some events just provide an array of the the events you want to use.
