### ISSUE TITLE
IdleTimer component causing TypeScript errors in 4.3.0

### ISSUE THREAD

**Issue by subvertallchris** [SupremeTechnopriest/react-idle-timer#121]
Hey, thanks for working on this library, it's been very helpful to me.

I was happy to see that you introduced hooks in 4.3.0 so I upgraded and both of the class components are spitting out errors suggesting the component is being interpreted as a plain ole class instance, not a component.

![image](https://user-images.githubusercontent.com/4097271/88091767-84e1a980-cb5d-11ea-93ef-c669b0a0e9aa.png)

Not the end of the world for me, I can just quickly convert both of these classes to hooks, but thought you'd like to know.

**Comment by SupremeTechnopriest** [comment]
Hey @subvertallchris! Thats interesting, the class component didn't change at all.  Could you paste the code that is triggering this error so I can try to recreate it on my side?

**Comment by subvertallchris** [comment]
Sure: https://codesandbox.io/s/vibrant-morning-8ebc5?file=/src/IdleClass/index.tsx

It's your example from the readme converted quickly to TypeScript. Give it a moment to be analyzed. Not getting the first of the two errors that I'm seeing but it gets the second and they're related, probably different from mine due to TS version or something.

**Comment by armando9210** [comment]
I am having the same issue

**Comment by SupremeTechnopriest** [comment]
Probably an issue with my `.d.ts` file.... I'm maintaining that by hand. Not a fan of typescript.  I'm going to add a typescript example and make sure the definition file is working correctly.  Bear with me.

**Comment by SupremeTechnopriest** [comment]
@subvertallchris @armando9210 Found and fixed the issue.  Version `4.3.1` published to NPM.

**Comment by armando9210** [comment]
Thanks bro!

**Comment by SupremeTechnopriest** [comment]
My pleasure!  Enjoy!

**Comment by subvertallchris** [comment]
Thank you!
