### ISSUE TITLE
Can't use props, state variable in hook manner

### ISSUE THREAD

**Issue by gnltkak** [SupremeTechnopriest/react-idle-timer#122]
` 
const {appMode} = props;

 const handleIdle = useCallback(() => {
    if (appMode === "timeLine") {
      setAppMode("screenSaver");
    }
  }, [appMode]);

  useIdleTimer({
    timeout: idleTimeOutSeconds * 1000,
    onIdle: handleIdle
  });
`

appMode is not latest value in above code

**Comment by subvertallchris** [comment]
This is the issue I was about to open. The callback fed to `onIdle` does not reflect the current version of `handleIdle`, it captured the state at initialization instead.

**Comment by SupremeTechnopriest** [comment]
Hmmm... ok.  I will add a test for this later today.

**Comment by SupremeTechnopriest** [comment]
@gnltkak @subvertallchris Fixed and published to NPM as version `4.3.2`.

**Comment by SupremeTechnopriest** [comment]
Sorry I caused a small regression.  Its going to be `4.3.4`.

**Comment by subvertallchris** [comment]
Great, thank you! I'll give it a shot in the morning.

**Comment by SupremeTechnopriest** [comment]
Thanks for the reports!  Let me know if you find anything else.

**Comment by gnltkak** [comment]
@SupremeTechnopriest Thanks for quick fix!
