### ISSUE TITLE
useState variables not updating in onIdle

### ISSUE THREAD

**Issue by acomito** [SupremeTechnopriest/react-idle-timer#124]
I'm trying to show a modal when the user is idle, and if the modal stays open for 30 seconds without any action taken, then I log the user out.

I'm using setTimeout, which I'm not sure if that's the right approach here. 

I thought maybe I was running into this issue: https://github.com/SupremeTechnopriest/react-idle-timer/issues/122 but it doesn't seem to be working for me even though i'm on ` "react-idle-timer": "^4.3.5",`

below is pseudo code of where I'm at right now:

```
import React, {useState, useCallback} from 'react';
import {useIdleTimer} from 'react-idle-timer';

export default () => {
  const [inactiveModal, setInactiveModal] = useState(false);

  const onLogout = () => {
    setInactiveModal(false);
    // do logout stuff here
  };

  const handleOnIdle = useCallback(() => {
    setInactiveModal(true); // show the modal
    setTimeout(() => {
      console.log('timeout', inactiveModal); // inactiveModal = false here... 
      if (inactiveModal) {
        onLogout(); // leave modal open for 30 seconds and if they don't accept, then log the user out
      }
    }, 30000);
  }, [inactiveModal]);

  useIdleTimer({
    timeout: 1000 * 60 * 5, // 5 minute inactivity
    onIdle: handleOnIdle,
    debounce: 500,
  });

  // only show the modal if inactiveModal = true
  if (!inactiveModal) return null;

 return 'Here is inactive modal'
}
```

**Comment by SupremeTechnopriest** [comment]
@acomito You should perform your setTimeout in a `useEffect` instead of the `useCallback`.  I made a code sandbox example.  I think it does what you want https://codesandbox.io/s/sweet-http-oo1hf?file=/src/App.js.
