### ISSUE TITLE
dist folder contains es6 code and not is compatible with ie11

### ISSUE THREAD

**Issue by prodigic** [SupremeTechnopriest/react-idle-timer#126]
![Screen Shot 2020-08-07 at 1 22 56 PM](https://user-images.githubusercontent.com/2828303/89685686-b1155e00-d8b1-11ea-8161-d8b767912f39.png)

arrow functions are included in the build code. this breaks older browsers

**Comment by prodigic** [comment]
`index.es.js` and `index.min.js` both contain es6 code.

**Comment by SupremeTechnopriest** [comment]
@prodigic I feel for you having to support IE.  I will make babel transpile all es6 and push a new version today.

**Comment by prodigic** [comment]
thanks for that! it's a pain. but less so when library devs are so on it. many thanks

**Comment by SupremeTechnopriest** [comment]
Hey @prodigic, Quick question.  Are you using the latest version?  Im grepping the source for `4.3.6` and I don't see any instances of `()=>{`.  Check here https://unpkg.com/react-idle-timer@4.3.6/dist/index.min.js

**Comment by prodigic** [comment]
react-idle-timer@4.3.0.

updating to 4.3.6. and will check back

**Comment by prodigic** [comment]
looks like 4.3.6 doesnt have arrow functions in the build code so maybe just an issue with 4.3.0 (which did have them)

you can close this out. thanks, sorry to bug you with a stale version issue. rookie mistake!

**Comment by SupremeTechnopriest** [comment]
@prodigic All good! Enjoy!

**Comment by prodigic** [comment]
using 4.3.6 fixes the issue. many thanks.
