### ISSUE TITLE
Tracking user time

### ISSUE THREAD

**Issue by jacobwhood** [SupremeTechnopriest/react-idle-timer#130]
Hello! Great job with this package overall, we appreciate all the effort you've put in.

We're wanting to move away from this [jQuery-based timer](https://github.com/thorst/jquery-idletimer) to your library. Similar to [this earlier issue](https://github.com/SupremeTechnopriest/react-idle-timer/issues/56), we are trying to track total active time for a user, while pausing when they become idle. When tracking total active time, we subtract any time the user is idle, including the idle timeout period.

The library doesn't seem to allow tracking the active time since the elapsed time is calculated from when the timer was loaded in. The jQuery-based library seems to interpret the elapsed time as time since last change between active <--> idle ([see here](https://github.com/thorst/jquery-idletimer/blob/d52354c25ff688fe16550338bbac9c69218b1326/src/idle-timer.js#L73)).

- Was defining the elapsed time in this way an intentional decision?
- Have you given any more thought to tracking total active time, as requested in the issue I linked above?

We've managed to get around this by wrapping your `useIdleTimer` hook with a custom hook of our own and keeping track of a `stateChangeDate` which is updated any time `onActive`, `onIdle`, or `reset` is called. We then defined a custom `getElapsedTime` function which returns the time since last state change by using our custom `stateChangeDate`. When we retrieve the user's total active time, we need the `getElapsedTime` function to return the time since last state change in the case they're still currently active. This time is added to a running sum of active time updated whenever the user goes idle.

**Comment by SupremeTechnopriest** [comment]
Hey @jacobwhood, Just so I'm clear on what you are asking for, you want a method like `getActiveTime` that tracks the amount of milliseconds the user is not idle?  I can work on adding that, but out of curiosity, what is the use case for such a function?

**Comment by adamthewan** [comment]
Just, thinking out loud. @jacobwhood its possible you can collect timestamps on the onActive and onIdle events. Then calculate the sum of the duration between each onActive and onIdle timestamp.

**Comment by jacobwhood** [comment]
@SupremeTechnopriest I appreciate the prompt response! Yes, your description of `getActiveTime` is the desired behavior -- that's basically what we're tracking now with our own wrapper around your timer. The active time is meant to be a sum of total active time, so tracking this time from component mount would be ideal. Our specific use case is for tracking the total active time our users are spending in one of our tools and displaying it in the UI on certain user actions.

@adamthewan Thanks for the suggestion - that would definitely work nicely! We're doing something similar by keeping track of a running sum of active time and updating the sum each time a user goes idle by adding the elapsed time between current time and when the user last became active. The only caveat is handling when the total active time is retrieved when a user is still active, in which case we use the custom `getElapsedTime` function I mentioned above to add the elapsed time to the running sum.

**Comment by SupremeTechnopriest** [comment]
Thanks for the clarification.  I will work on this feature this week.

**Comment by SupremeTechnopriest** [comment]
Hey @jacobwhood,

I added `getTotalActiveTime()` and published it as `v4.4.0`.  Let me know if they are any issues!
