### ISSUE TITLE
Does not support React 17

### ISSUE THREAD

**Issue by adam-beck** [SupremeTechnopriest/react-idle-timer#132]
As the title says this package has a strict peer dependency on React 16. I'm not too familiar with the whole process of testing if a major version change of React would be compatible with this codebase. I assume it would since it is only a peer dependency. 

If it just involves updating the peerDependency property I can create a PR.

**Comment by SupremeTechnopriest** [comment]
No worries I will update the peer dependency requirements and deploy a patch version. Thanks for the report.

**Comment by SupremeTechnopriest** [comment]
Updated the peerDependencies to `>=16`.  Should do the trick.  Let me know if there are any issues.
