### ISSUE TITLE
Incorrect dinamic idle timeout value

### ISSUE THREAD

**Issue by Cloudzaaa** [SupremeTechnopriest/react-idle-timer#135]
Hi!

I am trying use idleTimer for user logout when he bacame idle.
Also in my case I have to prolongate his session (send request for new token) if he was not idle (before existed token fall).

In my case token has dinamically duration time and I try handle all these things like that

```
  const { logout } = useLogout()
  const tokenDurationMs = useSelector(selectTokenDuration) * 1000
  const currentToken = useSelector(selectToken)
  const criticalTokenDurationMs = tokenDurationMs - 2000

  useIdleTimer({
    timeout: tokenDurationMs, //is it possible?
    events: ['click', 'contextmenu', 'keydown', 'wheel'],
    onIdle: logout,
    debounce: 1000,
  })

  useEffect(() => {
    const prolongateInterval = setInterval(() => {
      service.updateToken()
    }, criticalTokenDurationMs)

    return (): void => {
      clearInterval(prolongateInterval)
    }
  }, [currentToken, criticalTokenDurationMs])
```

But in that case sometimes after several new tokens, onIdle has timeout bigger than he has to be, where am I wrong?

**Comment by SupremeTechnopriest** [comment]
@Cloudzaaa, Just so I'm clear, you want to be able to change the timeout duration after the component is mounted?  The hook does not currently support that, but it could be added.

**Comment by Cloudzaaa** [comment]
@SupremeTechnopriest Yes, exactly (awesome fast feedback) 
Could you implement it?

**Comment by Cloudzaaa** [comment]
@SupremeTechnopriest in current case, timeout value behave unstable, and onIdle callback called in wrong time sometimes

**Comment by SupremeTechnopriest** [comment]
Yep I will implement it for you.

**Comment by Cloudzaaa** [comment]
I will look forward to
thank you!

**Comment by SupremeTechnopriest** [comment]
Actually. It looks like this is already possible, you just need to call `reset()` after changing the timeout.  Can you change your code to this and let me know if it works?

```js
  const { logout } = useLogout()
  const tokenDurationMs = useSelector(selectTokenDuration) * 1000
  const currentToken = useSelector(selectToken)
  const criticalTokenDurationMs = tokenDurationMs - 2000

  const { reset } = useIdleTimer({
    timeout: tokenDurationMs, //is it possible?
    events: ['click', 'contextmenu', 'keydown', 'wheel'],
    onIdle: logout,
    debounce: 1000,
  })

  useEffect(reset, [tokenDurationMs])

  useEffect(() => {
    const prolongateInterval = setInterval(() => {
      service.updateToken()
    }, criticalTokenDurationMs)

    return (): void => {
      clearInterval(prolongateInterval)
    }
  }, [currentToken, criticalTokenDurationMs])

```

**Comment by SupremeTechnopriest** [comment]
Here is the test that covers this:

https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/src/__tests__/useIdleTimer.test.js#L127-L140

**Comment by Cloudzaaa** [comment]
you are right
added this effect and case is covered

```
  useEffect(() => {
    if (previousTokenDurationMs !== tokenDurationMs) {
      resetIdle()
    }
  }, [tokenDurationMs, resetIdle, previousTokenDurationMs])
```

thx for help, close that issue

**Comment by SupremeTechnopriest** [comment]
You are welcome!

**Comment by SupremeTechnopriest** [comment]
@Cloudzaaa Hello, version `4.5.1` no longer requires you to call `reset()` manually. Just change the timeout and it should all work out of the box.

**Comment by Cloudzaaa** [comment]
thanks!
