### ISSUE TITLE
Stop timer initially and run timer when calling reset manually in code

### ISSUE THREAD

**Issue by yatharth1706** [SupremeTechnopriest/react-idle-timer#136]
Hy, I am using useIdleTimer hook in react. Is there any way by which we can keep idleTimer initally stopped and when we call reset function in our code then only idle timer should start.

**Comment by SupremeTechnopriest** [comment]
@yatharth1706  I imagine you came across the `startOnMount` property!  That should do what you want.

**Comment by yatharth1706** [comment]
yes, I read the documentation carefully and came across startOnMount property. Thanks
