### ISSUE TITLE
Hook - Dynamic timeout

### ISSUE THREAD

**Issue by woodreamz** [SupremeTechnopriest/react-idle-timer#137]
Hi,

Thanks for this package, I am using it since few months to handle the session timeout in my webapps. It works fine but we decided to have a dynamic timeout editable by the user and I am not able to figure out why the the timer does not reset.

I saw the closed issue #135, it seems the provided solution is working but it's not working in my case, I don't know why.

I created a simple codesandbox to reproduce it:  https://codesandbox.io/s/dynamic-timeout-0w21j

The initial timeout is 6000 ms. After 6000 ms, the onIdle is called. If you change the timeout (using the input) to 2000 ms, onIdle continue to be called after 6000 ms.

Adding the 'reset' function in the useEffect dependencies does seems to change anything.

Thanks for your help.

**Comment by SupremeTechnopriest** [comment]
Thanks for the report.  I have confirmed that this is an issue.  I will make it so you can pass a dynamic timeout to the hook without the need to call reset.  Stand by.

**Comment by SupremeTechnopriest** [comment]
@woodreamz Hello, I just published version `4.5.1` to npm that supports dynamic timeouts.  I updated your code sandbox and it appears to be working as expected. https://codesandbox.io/s/dynamic-timeout-forked-npqbq?file=/src/App.js

Let me know if you have any other issues!

**Comment by woodreamz** [comment]
Thank you for the quick fix.

I tested the version 4.5.1 in the codesandbox  and my webapp, it works perfectly!

**Comment by muthu1712** [comment]
Hi... 
Does the dynamic timeout logic work only if its used as a hook?

Am using the timer as a component itself (<IdleTimer (...props)/>). Dynamically updating the 'timeout' prop doesn't seem to work in this case.

**Comment by SupremeTechnopriest** [comment]
I think you might need to call reset here, but I should be able to make it so you dont need to.  Ill work on it today.

**Comment by SupremeTechnopriest** [comment]
@muthu1712 Hey this is good to go.  Published version `4.5.2` to npm.  Just set the timeout and it will automatically do the rest.

**Comment by muthu1712** [comment]
Thanks buddy @SupremeTechnopriest for the really really quick fix.
