### ISSUE TITLE
pause() is not working properly when using hooks

### ISSUE THREAD

**Issue by Edsonzhu** [SupremeTechnopriest/react-idle-timer#141]
Hi,

I'm having trouble on using pause() to stop the timer on my app. On the first try it works fine but it stop working on the next tries. 
I getting the pause and reset function from the useuseIdleTimer() and pass it to the rendering component1. That component1 will then pass it to componentVideo and pause the idle timer.
I seems like the pause() is never triggered by the componentVideo. 

Any help?

**Comment by SupremeTechnopriest** [comment]
Could you make a codesandbox that demonstrates the issue?  Would make it easier for me to figure out whats going on.

**Comment by Edsonzhu** [comment]
I tried to reproduce the error on codesandbox but I couldn't. In it, the code works fine so it might be something else.

Thanks

**Comment by SupremeTechnopriest** [comment]
Thanks for confirming.  Good luck!
