### ISSUE TITLE
Pause / resume creates multiple event listeners

### ISSUE THREAD

**Issue by strmer15** [SupremeTechnopriest/react-idle-timer#146]
When I add the `useIdleTimer` hook in my component, using `pause` and `resume` add multiple extra event listeners to the `document` (or whatever `element` I choose). When debugging, it seemed that `pause` and `resume` were using different, non-throttled versions of the [`_handleEvent` callback](https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/src/useIdleTimer.js#L86), so the `removeEventListener` invocations were not actually removing the events from the `document`. Because of that, pausing and resuming multiple times added a new event listener to the `document` each time.

This only seems to happen when I use `pause` and `resume` in a `useEffect` hook, since I use Redux to manage the state of the page (since there are other things the app does on pause, like make an API call, etc).

Here's a [codesandbox link](https://codesandbox.io/s/goofy-shockley-jkhpn?fontsize=14&hidenavigation=1&theme=dark) that reproduces the problem - if I remove the `useEffect` and use `pause` and `resume` directly, it works, but I can't do that in my app because of the need for a `useEffect` hook to change with the Redux state.

**Comment by SupremeTechnopriest** [comment]
@strmer15 Acknowledged!  This is definitely bad, but should be an easy fix.  I will take a look after work today.

**Comment by strmer15** [comment]
@SupremeTechnopriest thanks for the quick response!

**Comment by SupremeTechnopriest** [comment]
Work has been busy the past few days.  I will get to this as soon as I can.

**Comment by strmer15** [comment]
> Work has been busy the past few days. I will get to this as soon as I can.

No problem! Thanks for all the effort you put in to maintain this package.

**Comment by SupremeTechnopriest** [comment]
@strmer15 This is all set now. Published to npm as version `4.5.6`. I updated your codesandbox to demonstrate the fix.

https://codesandbox.io/s/crazy-hopper-dou18?file=/src/App.js
