### ISSUE TITLE
About events

### ISSUE THREAD

**Issue by huseyingoztok** [SupremeTechnopriest/react-idle-timer#148]
How can I activate the onAction without sending a requestt when I click anywhere on the page?

**Comment by huseyingoztok** [comment]
Which event or events should I use?

**Comment by SupremeTechnopriest** [comment]
Im not sure I fully understand your question, but it depends on what events you want to consider an action. 

[Here](https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/src/index.d.ts#L6-L95) is a list of most all of the events you can choose from, but any dom event is applicable.  

Do you mean you want onAction to fire when you click, but you don't want the click to propagate to the actual thing you clicked on?  Or do you want to exclude the click event from the onAction handler?

**Comment by huseyingoztok** [comment]
To give an example,

For example, when an unauthorized user logged in in a different tab clicks on a place in the menu where he is not authorized, the request goes directly to the server and the application redirects to the 401 page because the server returns 401. What event will I be able to intercept without going to this request server?

**Comment by SupremeTechnopriest** [comment]
Well if the click is the event you want to intercept, then click is the event you want to listen to.  What you could to to prevent the propagation is put the css property `pointer-events: none` on the element you don't want the click to go through.  Then just the onAction event will trigger.  From there you can dynamically update the `pointer-events` prop when you want the user to be able to click the element again.

Does that help?

**Comment by huseyingoztok** [comment]
Thanks, I'll try.

**Comment by SupremeTechnopriest** [comment]
Sure thing, if it works out feel free to close this issue.  If you are still having trouble we can try to figure something else out.
