### ISSUE TITLE
Need clarification on "onIdle" event

### ISSUE THREAD

**Issue by AndriyHromyak** [SupremeTechnopriest/react-idle-timer#149]
I have 2 scenarios:

1. I am setting "timeout" as 9 min, and do nothing till "onIdle" event triggers and show me modal window(with counter i have set up) i have implemented, and it works perfectly fine.
2. Same thing as above yet i am hiding browser and using other apps, in this case seems like "onIdle" is triggered right before i open my tab where i have my app, and not after 9 min of idleness, why i am assuming this, is because i see my timer in modal just starting counting.

Is it expected?

UPD: Seems like if i set 2 min everything works well on both cases, also its might be react hook behaviour

**Comment by SupremeTechnopriest** [comment]
This sounds like it's from [timer throttling](https://developers.google.com/web/updates/2017/03/background_tabs#budget-based_background_timer_throttling).  There are ways to prevent this, but it will consume resources. https://github.com/turuslan/HackTimer being one of them.  

Hope this helps.

**Comment by ad9999** [comment]
Some reading regarding setTimeout and sleep mode would help understand upto certain extend

https://stackoverflow.com/questions/6346849/what-happens-to-settimeout-when-the-computer-goes-to-sleep

**Comment by SupremeTechnopriest** [comment]
Ive thought about capturing timestamps and using them for a sanity check.  Maybe I'll get this in the next release.
