### ISSUE TITLE
react-idle-timer@4.5.5" has unmet peer dependency "prop-types@>=15"

### ISSUE THREAD

**Issue by AndriyHromyak** [SupremeTechnopriest/react-idle-timer#150]
i have warning when installing react-idle-timer
"react-idle-timer@4.5.5" has unmet peer dependency "prop-types@>=15""
is there any solution how to fix this?

**Comment by SupremeTechnopriest** [comment]
Hey @AndriyHromyak, yeah all you have to do is `npm i prop-types --save-dev`.  I set it as a peer dependency so there aren't multiple versions of it floating around in your modules folder.  Most React projects use it and I would consider it good practice to.
