### ISSUE TITLE
Rehydrate a previous idle state after closing and opening page

### ISSUE THREAD

**Issue by annabrit** [SupremeTechnopriest/react-idle-timer#154]
Thanks for adding multiple tab support!
Is there any way to work with the existing structure supporting multiple tabs to support resuming/rehydrating a previous idle state when all the tabs are closed and later, a new one is opened?
It looks like I can use `removeTimeout` to control the lifespan of the cross tab messaging with localStorage, but can I use the data in localStorage to set the internal state of the `useIdleTimer`?

**Comment by SupremeTechnopriest** [comment]
Hi @annabrit,

In its current form this isn't possible.  Tabs are given a unique Id when they are created so the old state wouldn't map back to the new state. How ever, if all you care about is the idle state of all tabs from the previous session I may be able to implement something for you. 

```javascript
const { setAllIdle, isAllIdle } = useIdleTimer({ 
  crossTab: { 
    type: 'localStorage',
    removeTimeout: 1000 * 60 * 60 * 24 // something long
  }
})

useEffect(() => {
  const allIdle = localStorage.getItem('your-key')
  setAllIdle(allIdle)
  return () => {
    localStorage.setItem('your-key', isAllIdle())
  }
})
```

Is that sort of what you want?

**Comment by SupremeTechnopriest** [comment]
Though I kind of question why this would be needed.  The act of going back to the site kind of implies the user is active again.  Can you describe your use case a little?

**Comment by annabrit** [comment]
Hi @SupremeTechnopriest 
You are quick!

I figured it wouldn't be possible, but I thought I'd ask. 
In my particular use case, I want to log users out after X minutes of inactivity. They might close all their tabs while they are still considered to be active, but if X minutes pass before they open a new tab, they should be logged out when they do open the tab (although possibly that is the wrong approach from a security standpoint because their auth is still stored in the meantime). 
So I think `allIdle/setAllIdle` wouldn't be useful in this scenario. 

Thanks though!

**Comment by SupremeTechnopriest** [comment]
Hmm yeah I think JWT is better suited for that.  You could request a new JWT with an expiration of your timeout when the user closes all the tabs and then check the JWT against the server when they come back.  Going to close this issue, but if I can come up with another solution for you I will post it here.
