### ISSUE TITLE
TabManager locks in onActive and other callbacks.

### ISSUE THREAD

**Issue by nathanielhunter** [SupremeTechnopriest/react-idle-timer#156]
I was trying to integrate using crosstab support, and I found that it doesn't support updating the onActive (and other) function callbacks. For example if the activity callback depends on local state such as the login status, the initial login status is retained throughout the lifecycle of the crosstab timer with respect to the callback.

**Comment by SupremeTechnopriest** [comment]
You mean changing the callback functions?

**Comment by nathanielhunter** [comment]
Technically, yes. I'm not actually changing the function just the data captured in closure, but I guess it's true the function itself has to change to make that happen.

**Comment by SupremeTechnopriest** [comment]
Are you using the hook or the component?

**Comment by nathanielhunter** [comment]
The component currently, if the hook behaves differently I could try that instead.

**Comment by SupremeTechnopriest** [comment]
The hook should use the most recent functions.  I see if I can make the component do the same.

**Comment by SupremeTechnopriest** [comment]
Think I have a patch that will support this in the Component.  Just writing some tests and ill push a revision to the `@next` tag.

**Comment by SupremeTechnopriest** [comment]
Can you test out `4.6.2-rc.1` by installing from `npm i react-idle-timer@next`?  Let me know if that fixed the issue for you and I will publish it to the `latest` tag.

**Comment by nathanielhunter** [comment]
Now I'm not observing events at all.

**Comment by SupremeTechnopriest** [comment]
Hmm.  I'll dig more into this when I have a chance. Probably this weekend.

**Comment by SupremeTechnopriest** [comment]
@nathanielhunter Sorry for the delay, work got busy.  Can you try `4.6.2-rc.2` published to `@next`?  Tried a different approach.

**Comment by SupremeTechnopriest** [comment]
Just checking in, did you have a chance to test this?  Seems to be working for me.

**Comment by nathanielhunter** [comment]
No, I haven't had time to get back to it. We changed tact on our project and don't know if we need this anymore.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by SupremeTechnopriest** [comment]
Okay Im going to roll out the change and close this issue then.  Thanks for the report.

**Comment by SupremeTechnopriest** [comment]
Published `4.6.2` to npm.  Added tests to cover this use case.  Should be good to go should you decide to use the component again. 👍
