### ISSUE TITLE
Question about start() vs. reset()

### ISSUE THREAD

**Issue by v1v2v3vv55** [SupremeTechnopriest/react-idle-timer#157]
So according to the document when onActive is being called then reset() will be called, so if I use start, does the previous timer still counting down or it will setup a new timer with timeout and previous one will be gone?

Another question, for my tag IdleTimer , if I don't put in onActive as prop, does the reset() will still be called? What I mean is that how to not triggered reset() if reset() is being called even without put in onActive tag. Basically I don't want onActive to be triggered.

**Comment by SupremeTechnopriest** [comment]
`onActive` does not call `reset`.  It's the other way around.  Calling `reset` will fire the `onActive` event if you are in the idle state.  `start` will just re start the timer without firing `onActive`
