### ISSUE TITLE
Doesn't support screen readers?

### ISSUE THREAD

**Issue by ch-tactica** [SupremeTechnopriest/react-idle-timer#159]
It seems that if there is a screen reader actively reading text on the page, it doesn't prevent the idle timer from firing. This is easily reproducible if you have a lot of text on the page and set a short-lived timer expiration.

**Comment by SupremeTechnopriest** [comment]
Hmmm interesting problem. I will have to look into how the screen reader works. It's likely a separate frame. Might need to file a bug on the browser vendors. I'll do some tests and see what I can come up with.

**Comment by SupremeTechnopriest** [comment]
By screen readers, do you mean text to speech/ accessibility or reader mode where most of the styles are removed giving the user a clean reading experience?

**Comment by SupremeTechnopriest** [comment]
In either case, it doesn't seem like there is a unified API for me to be able to add support. The closest solutions I can find are:

https://github.com/wicg/aom
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/toggleReaderMode

If/when these APIs are well supported I can add support for screen readers and reader mode.  Until then there is not much I can do.  Going to close this for now, but will revisit when the APIs are available.
