### ISSUE TITLE
Function to call each time a remaining second elapses?

### ISSUE THREAD

**Issue by mellis481** [SupremeTechnopriest/react-idle-timer#163]
I'm looking for a piece of functionality in react-idle-timer that doesn't seem to be present and that is a way to define a function/callback each time a remaining second elapses.

Here is an example use-case:  I want the log out a user if they have been idle for 30 minutes, but want to pop up a dialog in the last 60 seconds of that 30 minutes with a countdown timer, warning he/she that they will be logged out shortly due to idleness.

It seems like the only way to do this currently is to define an additional timer that I manage for the "secondary" countdown.  Providing a `onRemainingSecondElapse()` function would avoid library users from having to try to keep two timers in sync.

**Comment by mellis481** [comment]
I'm seeing this appears to be possible in one of the examples: https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/examples/hook-ts/src/App.tsx

**Comment by SupremeTechnopriest** [comment]
Glad you sorted it out.  This is probably the most common use case and it's definitely possible.  It seems most people use the Idle Timeout to open the modal and then use their own setTimeout to actually do the logout.  Clear the timeout on the "Im still here" button.

I imagine for your use case you want user activity to clear the modal instead of a button, in which case, you are on the right track.  Good luck!

**Comment by rikinshah23** [comment]
> 

I could not open the example link. do you have a new link by any chance? Thanks

**Comment by rikinshah23** [comment]
> I'm seeing this appears to be possible in one of the examples: https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/examples/hook-ts/src/App.tsx

I could not open the example link. do you have a new link by any chance? Thanks

**Comment by SupremeTechnopriest** [comment]
Yeah that example is in the v4 branch.  The new examples will live on the docs site.  Heres a link to the old examples for v4:
https://github.com/SupremeTechnopriest/react-idle-timer/tree/v4/examples
