### ISSUE TITLE
Package causing CSP issues

### ISSUE THREAD

**Issue by caranad** [SupremeTechnopriest/react-idle-timer#164]
Hi there,

It appears that when I'm implementing this module with CSP (script-src) you're relying on the regenerator-runtime package to bundle this module, which will end up triggering the following CSP error when I try it: 

![image](https://user-images.githubusercontent.com/16296061/118576561-c54a8d80-b756-11eb-8dd1-b714d609b9ce.png)

Thanks for all your assistance.

**Comment by SupremeTechnopriest** [comment]
Hello, let me see what I can do about that.  I will be publishing a release candidate later today.

**Comment by SupremeTechnopriest** [comment]
Published `4.6.3-rc.1` to npm `next` tag.  Install with `npm i react-idle-timer@next` and let me know if that build fixes your issue :)

**Comment by caranad** [comment]
Yikes, that was fast. Thanks for the quick response! I'll test it and get back to you.

**Comment by caranad** [comment]
Sir, you are a God amongst men. I salute you and your work, for your solution has SOLVED MY ISSUE! THANK YOU AND BLESS YOU! :D :D :D :D :D :D

**Comment by SupremeTechnopriest** [comment]
Glad to be of service!  I will roll this out to the `latest` tag as soon as I resolve a few more issues.  Until then feel free to use the `next` tag.  I will update you here when you can switch back over!

**Comment by SupremeTechnopriest** [comment]
Hello @caranad,

I had to make a few changes to try and support older browsers that need the runtime.  I checked the built code and theres no `eval` being called.  Can you just confirm your CSP example still works with `4.6.3-rc.2`? 

Thanks!

**Comment by caranad** [comment]
Hi @SupremeTechnopriest,

Thanks for checking. Unfortunately the error comes back when I use 4.6.3-rc.2.

**Comment by SupremeTechnopriest** [comment]
Yeah, thought it might.  From what I've read about this issue, it involves `use-strict;` or something.  Is your project a CRA by any chance?  I think this is definitely a problem with regeneratorRuntime....  Here are a few threads that I found:

https://github.com/facebook/regenerator/issues/378
https://github.com/facebook/regenerator/issues/450

From what I gather here, if you were to remove strict mode, it should start working.  

I need to ensure that this package supports old browsers.  I tried to drop support for dead browsers (IE) and people were opening issues about it.  Can you see if you can get it working using some of the methods in those threads?  If not we can revisit.  Maybe I can export an additional build without support for older browsers that you can import.  Something like:

`import IdleTimer from 'react-idle-timer/dist/modern`

Let me know how you make out.

**Comment by caranad** [comment]
Correct - my app uses **create-react-app**. I have looked at those two threads previously, but unfortunately I could not make do with them.

**Comment by SupremeTechnopriest** [comment]
Sure can do.  Im going to do a bit more research and see if I can fix this.  Otherwise I will add a modern importable.  In the mean time you can just work with `4.6.3-rc.1` and I will let you know when I have a solution.

**Comment by caranad** [comment]
Will do. Once more thank you so much for your work on this; I appreciate it. Best of luck on your efforts and if there's any way I can help let me know 🙂

**Comment by SupremeTechnopriest** [comment]
Can you send me your csp header so I can test some things locally?

**Comment by SupremeTechnopriest** [comment]
I can export a modern.js along side the current builds, but its not ideal because it breaks typescript definitions. Id rather figure out a way to resolve the issue with the current build system.

**Comment by caranad** [comment]
This is the CSP I'm using right now. Note that I censored the name of the site I'm working on for privacy reasons.

require-trusted-types-for 'script'; 
frame-ancestors 'self'; 
form-action 'self'; 
img-src 'self'; 
style-src-elem 'self' 'unsafe-inline'; 
default-src 'self'; 
script-src 'self' https://www.<websitename>.com https://cdnjs.cloudflare.com https://ajax.cloudflare.com https://js.stripe.com/v3 'nonce-${ nonce }'; 
style-src 'self' 'unsafe-inline'; 
object-src 'none'; 
base-uri 'self'; 
font-src 'self'; 
frame-src 'self' https://js.stripe.com/; 
manifest-src 'self'; 
media-src 'self'; 
worker-src 'self' blob: https://cdnjs.cloudflare.com/; 
connect-src 'self' https://firebasestorage.googleapis.com https://securetoken.googleapis.com https://www.googleapis.com;

**Comment by SupremeTechnopriest** [comment]
Thanks for that.  I will hopefully find a good solution today.

**Comment by caranad** [comment]
Sounds good - let me know if anything arises

**Comment by SupremeTechnopriest** [comment]
Hey @caranad,

I just published `4.6.3-rc.4`.  What I did is created a modern browser export. If you are using Webpack 5 you can do:

```js
import IdleTimer, { useIdleTimer } from 'react-idle-timer/modern'
```

If you are on Webpack 4 (which I believe CRA still uses), you have to do:

```js
import IdleTimer, { useIdleTimer } from 'react-idle-timer/dist/modern'
```

In both cases typedefs should still work and there are no babel transpilations of any sort.  For version 5 I plan to make this the default and if you want to support dead browsers you will have to:

```js
// Webpack 5
import IdleTimer, { useIdleTimer } from 'react-idle-timer/legacy' 

// Webpack 4
import IdleTimer, { useIdleTimer } from 'react-idle-timer/dist/legacy' 
```

Can you take that for a spin and let me know if it resolves your issue?

**Comment by caranad** [comment]
Hi Randy,

I tried **npm install --save react-idle-timer@4.6.3-rc.4** and it didn't work.

**Comment by SupremeTechnopriest** [comment]
@caranad,

Looks like I forgot to publish it 😬.  It's up now.  Give that a go.

**Comment by SupremeTechnopriest** [comment]
@caranad 

Did you have a chance to confirm this?  I plan to roll it out today.

**Comment by caranad** [comment]
Not yet, I will do so now.

**Comment by caranad** [comment]
Yes, it works. Thanks!

**Comment by SupremeTechnopriest** [comment]
Perfect, going to roll this out shortly.

**Comment by SupremeTechnopriest** [comment]
@caranad `4.6.3` published to `latest` tag!
