### ISSUE TITLE
ignore mouse movement

### ISSUE THREAD

**Issue by Charles6** [SupremeTechnopriest/react-idle-timer#169]
I see that mouse movement is one of the event triggers to reset the timer, is there a way to ignore this?

**Comment by SupremeTechnopriest** [comment]
Hello, 

Yes you can set which events you want IdleTimer to listen to. Just set the `events` property.  The default events are https://github.com/SupremeTechnopriest/react-idle-timer#default-events

Here is a list of most events you can use.
