### ISSUE TITLE
Is there a way to know that onIdle has been triggered after sleep mode?

### ISSUE THREAD

**Issue by nigellima** [SupremeTechnopriest/react-idle-timer#172]
Hello, thanks for the awesome lib.

I'm using this to sign out users after they are idle for some time. So, when the onIdle is called I show a modal with a message, which then automatically logs off users if no action is taken.

I realized that when I close my laptop and opens it again, the modal is immediately  triggered due to the onIdle call. I saw that this is implemented due to this issue: https://github.com/SupremeTechnopriest/react-idle-timer/issues/138

So, how do know to trigger onIdle after the user wakes up the computer? Is it exposed somehow, so I could immediately log off the user?

Thanks in advance

**Comment by SupremeTechnopriest** [comment]
Hello!  Can you tell me what your timeout is set to?  Maybe show me the props you are passing to the IdleTimer?  Currently I don't do anything special here, but I am thinking about tracking the timestamp diffs in between timer ticks. What i think is happening here is that when the computer goes to sleep the user is considered idle, and when you open it, the onIdle event gets emitted. 

Just so Im clear, you are looking for a way to determine when a user is coming back from a sleep so you can log them out without triggering a modal?

**Comment by RealDrewKlayman** [comment]
@SupremeTechnopriest Yeah, it looks like it does hit the onIdle when the user re-opens but because I have a countdown that happens upon the onIdle function they are able to restore the session and exceed timeout..

**Comment by RealDrewKlayman** [comment]
I think he is facing the same issue as me.

**Comment by SupremeTechnopriest** [comment]
So what you're looking for is either a different event like `onWake` or an argument to `onIdle` to let you know if the timer is coming back from a throttle or a sleep?  

If so I will have to think about how to detect that.  My initial thoughts would be to track a timestamp `lastAction` and compare that against a timestamp when the set timeout is triggered.  If its greater than the `timeout` prop then its probably safe to assume it's been asleep or throttled.

What do you think?

**Comment by RealDrewKlayman** [comment]
That would be great.

**Comment by SupremeTechnopriest** [comment]
Okay I will work on it for the next release.  Work is a bit busy right now so it probably wont be for a couple weeks, but I will keep you posted.

**Comment by RealDrewKlayman** [comment]
How would the onWake function work with crossTab?

The lastActive is on a per tab basis and not shared between tabs so the leader may have a much earlier lastActive then the actual tab that the user was working on before.

**Comment by SupremeTechnopriest** [comment]
`lastActive` is probably not the right nomenclature.  Maybe `lastEvent` is more succinct.  It would be the timestamp of the last time an 'onIdle` or `onActive` was emitted.  Those events are synced across tabs.  Then when the tab is focused (`pageshow`) I can compare `currentTime - lastEvent > timeout` you are probably coming back from being asleep or throttled.  I will have to do some tests to verify this will work, but thats my initial thoughts.

**Comment by RealDrewKlayman** [comment]
Technically speaking though they can just keep moving their mouse on a page and the onIdle / onActive events will not be hit.

Won't that make also trigger this event you are talking about if they move around for awhile and then pause and hit the onIdle or onActive function?

**Comment by RealDrewKlayman** [comment]
The onIdle function will not get hit if the computer is already asleep so when it does get hit you are just setting it to the current datetime when the re-open the computer, right?

**Comment by SupremeTechnopriest** [comment]
If they are moving around they definitely aren't asleep.  Im going to move the timeout to a webworker and that should solve the throttle issue. 

When the computer goes to sleep, the `setTimeout` is paused and is resumed when the computer wakes up.  Another idea is to make the timer `setInterval` based and use timestamps.  That way `currentTime - lastActionTime > timeout` fire `onIdle`.  If your computer is asleep and wakes back up, the timer will know that the timeout has elapsed and will immediately emit the onIdle.

**Comment by nigellima** [comment]
@SupremeTechnopriest hello. Sorry for the delay, but for some reason I was not getting the comments notifications.

So, I tried one of the solutions I found googling around, and one of them is similar to what you are saying there. However, I realized after around 6min without using the computer, this difference gets greater than the timeout.

This thing is it's happening ONLY on Google Chrome. I tested this solution in Firefox and it works perfectly.

```
var TIMEOUT = 20000;
var lastTime = (new Date()).getTime();

setInterval(function() {
  var currentTime = (new Date()).getTime();
  if (currentTime > (lastTime + TIMEOUT + 2000)) {
    // Wake!
  }
  lastTime = currentTime;
}, TIMEOUT);
```

Do you happen to know some way that it would work on all browsers?

**Comment by RealDrewKlayman** [comment]
@nigellima Use a web worker for the interval.

**Comment by SupremeTechnopriest** [comment]
Hey everyone!

The version 5 beta is out and can be dowloaded with `npm i react-idle-timer@next`.  All timers are now moved to web-workers, so you should no longer have issues with backgrounded tabs.  Check out the docs at [https://idletimer.dev](https://idletimer.dev).  Im going to close this issue, but if your problem persists in v5, feel free to open another one.

**Comment by Tasin5541** [comment]
@SupremeTechnopriest 
Having the same problem with v5.4.2. I set a promptTimeout (1min) to show a prompt. After I come back from **sleep**, I can see the prompt and the remaining time shows up as 0. But it doesn't call the onIdle function.

```
const { getRemainingTime, isPrompted, reset, message } = useIdleTimer({
    timeout,
    promptTimeout,
    onPrompt,
    onIdle,
    onActive,
    onAction,
    debounce: 500,
    crossTab: true,
    name: 'someproject',
    syncTimers: 1000,
    onMessage,
  });

  useEffect(() => {
    const interval = setInterval(() => {
      if (isPrompted()) {
        setRemaining(Math.ceil(getRemainingTime() / 1000)); // show remaining time in seconds on the prompt
      }
    }, 1000);
    return () => {
      clearInterval(interval);
    };
  }, [getRemainingTime, isPrompted]);
```

**Comment by garyb01** [comment]
I have the same exact issue on OSX as @Tasin5541

**Comment by SupremeTechnopriest** [comment]
@garyb01 which version are you running?

**Comment by garyb01** [comment]
Version: 5.5.2

Same issue was also happening on Version: 5.4.2

The way I was able to recreate this was to:

```
const startManually = true
const startOnMount = false
const promptTimeout = 60 * 1000
const timeout = 5 * 60 * 1000
```

Open the browser start `react-idle-timer` via the `start()` method. Then on my OSX machine hit the Apple Icon -> Sleep

The machine falls asleep... then I wait 10 minutes.

Wake the machine back up.

And the `getRemainingTime` starts a 5 minutes but the `onIdle` handler gets called after only 1 minute.

Similar issue happens if I set the timeout to 10 minutes and the promptTimeout to 5 minutes... once the prompt shows up after 10 minutes and `getRemainingTime` starts at 5 minutes. I put the machine to sleep then wake it back up 5 minutes later. The remaining time showed 10 minutes. But the `onIdle` handler got called 5 minutes later. 

I have also seen `getRemainingTime` show 0 seconds but the `onIdle` handler only gets called after a full `promptTimeout`.

There seems to be something that resets 1 timer but not the other... 


Let me know if there are some steps that I could follow to help you get the information needed.

**Comment by pream1234** [comment]
Is there any update on above issue , facing the same issue in V 5.5.2

**Comment by SupremeTechnopriest** [comment]
Ah okay so the prompt fires when it should be idle. That sounds like a bug that can be fixed. I'll take a look this weekend.

**Comment by SupremeTechnopriest** [comment]
@garyb01, @pream1234, @Tasin5541, @RealDrewKlayman, @nigellima 

Okay I think this should be behaving the way you expect in the latest version `5.3.3`.  

https://github.com/SupremeTechnopriest/react-idle-timer/releases/tag/5.3.3

Let me know if you are still seeing issues.

**Comment by tgelu** [comment]
@SupremeTechnopriest I think you wanted to refer to `5.5.3`, right? https://github.com/SupremeTechnopriest/react-idle-timer/releases/tag/5.5.3 :)

**Comment by SupremeTechnopriest** [comment]
100%.  I published the wrong tag, but its fixed now.  The npm version was published correctly :D

**Comment by deleonjulio** [comment]
@SupremeTechnopriest 

Is there a way to trigger an onIdle event even when the machine is asleep? For example, if the idle timeout is set to 30 seconds and I put my laptop to sleep, I want an API request to be sent as soon as the 30 seconds pass — without waiting for the user to wake the laptop.

**Comment by SupremeTechnopriest** [comment]
> Is there a way to trigger an onIdle event even when the machine is asleep? For example, if the idle timeout is set to 30 seconds and I put my laptop to sleep, I want an API request to be sent as soon as the 30 seconds pass — without waiting for the user to wake the laptop.

No, the computer is asleep....
