### ISSUE TITLE
Any plans to allow us to use the broadcast channel?

### ISSUE THREAD

**Issue by RealDrewKlayman** [SupremeTechnopriest/react-idle-timer#174]
We have some data going back and forth between tabs.

If they are active after a couple minutes I send a refresh call to the API which also refreshes the user and instead of creating an additional broadcast channel I'd like to be able to use the already existing one to pass the refreshed user to the other tabs.

**Comment by SupremeTechnopriest** [comment]
No plans for that currently.  I don't see there being any harm in having more than one broadcast channel on your page.  Its actually probably better to keep a different channel for different events.  That said, I suppose you would want to take advantage of the fallback local storage method to support older browsers.  It shouldn't be too hard to expose.  I will look at some options for the next release.

**Comment by RealDrewKlayman** [comment]
Alright, that sounds great. Should I close this?

**Comment by SupremeTechnopriest** [comment]
You can leave it open, I will close it when I get it implmented.

**Comment by RealDrewKlayman** [comment]
Just thought of a good use case for this:

I have a countdown that comes up after the timeout and a user has 30 seconds to click that they'd like to continue the session. There is an additional 30 second timeout that I set for logging off the user. If a user clicks continue on another tab that isn't the leader I need it to clear the timeout on the leader tab.


Rather then creating a whole broadcast channel with fallback support for that simple thing, it would be easier already using the pre-existing broadcast channel that you have setup.

**Comment by SupremeTechnopriest** [comment]
If you call `reset` on any of the tabs it should propagate to all the other tabs and reset the timer.

**Comment by RealDrewKlayman** [comment]
Correct, but I can't modify the reset function and also add the ability to clear out my custom timeout on my leader tab that logs them off from a non-leader tab.

**Comment by RealDrewKlayman** [comment]
Maybe if we had a way to add stuff onto the reset function that would work.

**Comment by SupremeTechnopriest** [comment]
Hey @RealDrewKlayman!

The version 5 beta has been released and can be installed with `npm i react-idle-timer@next`.  I added a feature that exposes the underlying messaging layer for your own use.   In short I've added an [`onMessage`](https://idletimer.dev/docs/api/props#onmessage) callback and a [`message()`](https://idletimer.dev/docs/api/methods#message) method. You can check out the feature overview [here](https://idletimer.dev/docs/getting-started/new#cross-tab-messaging). 

If for some reason this does not fulfill your needs, feel free to open another issue.
