### ISSUE TITLE
session timeout warning 

### ISSUE THREAD

**Issue by skyshine999** [SupremeTechnopriest/react-idle-timer#175]
I am using this library and it is working fine but if i put my timeout for 20 mins , at 15 mins i want to show some warning kind of message. I haven't found any parameter watching time change. Should i need to maintain separate time check stuff or is there any existing parameter that satisfy warning condition.

**Comment by RealDrewKlayman** [comment]
This would be nice. Was going to write something about this.

**Comment by RealDrewKlayman** [comment]
Seems like everybody is doing this anyways so would be nice to have this built into the package to make it an all in one solution.

**Comment by skyshine999** [comment]
is there any update on this ?

**Comment by SupremeTechnopriest** [comment]
Right now you have to manage your own timeout. I can look into adding this feature to the v5 release scheduled for early Q3. I don't have time to work on this until then.

**Comment by RealDrewKlayman** [comment]
@SupremeTechnopriest Next year early Q3?

**Comment by SupremeTechnopriest** [comment]
Sorry Q4 this year.  September/ October I will have time.  We are releasing a new product at work and its consuming all my time, free and otherwise...

**Comment by arnonate** [comment]
This was my solution for now. A simple modal with a 60 second countdown that calls `reset`. Hope it helps!

```
const COUNTDOWN = 60;
const [modalOpen, setModalOpen] = useState(false);
const [logoutTimer, setLogoutTimer] = useState(COUNTDOWN);

const { reset } = useIdleTimer({
    timeout: Config.inactivityTimeout,
    onIdle: () => setModalOpen(true),
  });
  
useEffect(() => {
    if (modalOpen) {
      setTimeout(
        () => setLogoutTimer((count) => (count > 0 ? count - 1 : count)),
        1000,
      );
    }
    if (logoutTimer === 0) logout(true); // Is idle timeout
  }, [modalOpen, logoutTimer]);
  ```

**Comment by SupremeTechnopriest** [comment]
Hey @RealDrewKlayman and @arnonate!

The version 5 beta has been released and can be installed with `npm i react-idle-timer@next`.  I added a feature that internalizes the prompt mechanism.  It seems to be a very common use case and is worth having a built in solution.  In short I've added a [`promptTimeout`](https://idletimer.dev/docs/api/props#prompttimeout) property, an [`onPrompt`](https://idletimer.dev/docs/api/props#onprompt) callback and an [`isPrompted()`](https://idletimer.dev/docs/api/methods#isprompted) method. You can check out the feature overview [here](https://idletimer.dev/docs/getting-started/new#integrated-prompting). 

If for some reason this does not fulfill your needs, feel free to open another issue.

**Comment by dpgalloway** [comment]
Hey @SupremeTechnopriest thank you for your work here. Do you have any estimated date on when v5 will go out of beta? I'd like to use this now-built-in feature but plan to deploy in the next couple weeks. Is it stable enough to use in a production environment or should I stick with v4?

**Comment by SupremeTechnopriest** [comment]
@dpgalloway I would say its stable enough for production.  You should join the discord so you can keep track of any major changes during the release candidate phase.  I'm getting pretty close to ready.  There's just a few more features I want to add.

**Comment by SupremeTechnopriest** [comment]
@dpgalloway v5 is released!
