### ISSUE TITLE
On crossTab.emitOnAllTabs non-leader browser tab doesn't trigger/emit any events

### ISSUE THREAD

**Issue by bhattaraib58** [SupremeTechnopriest/react-idle-timer#177]
Version: 4.6.4

Thank you so much for the awesome package. On the new feature addition, I noticed a issue,
I am using react-idle-timer on Chrome Version 91.0.4472.164 (Official Build) (64-bit), so broadcast is enabled.

I have enabled crossTab and emitOnAllTabs.
Here is the code.

`
  const { start, reset } = useIdleTimer({
    timeout: 15000,
    onActive: handleOnActive,
    onIdle: handleOnIdle,
    debounce: 250,
    crossTab: {
      emitOnAllTabs: true
    }
  });
`

The issue I am getting is:
If I open 3-4 tabs (Tab-1, Tab-2, Tab-3, Tab-4), use browser Tab-1 for few second (in 2 second, leader is selected by default). On the same Tab (Tab-1), due to my events timer gets reset after new event. Also, after the timer end (timeout), if an activity is performed (event) on Tab-1, the timer is getting reset. (Which is working well as expected).

But after that, if I go to Tab-2, Tab-3, or Tab-4 (which are non-leader tabs, as Tab-1 is Leader), on my activity (mouse move, key up/down events) also timer (remaining time) is not reset and timer ends. After time end as well, even if an activity is performed, the remaining time is not reset.

Expected Scenario:
Activity/Events on non-leader tabs should also reset the remaining time as the user is active. Also, after the timer end as well, if the user performed action on non-leader tabs (Tab-2, Tab-3, Tab-4), the remaining time should reset.

I think as emitOnAllTabs is enabled, there shouldn't be a leader i.e: all browser tabs should be the leader. And activity on each tab should reset IdleTimer on other.

**Comment by RealDrewKlayman** [comment]
I think this is being fixed in V5.

**Comment by SupremeTechnopriest** [comment]
Yeah v5 will have a patch for this.  Im going to start working on it in September.  Been really busy releasing a new product at work.

**Comment by SupremeTechnopriest** [comment]
Hey @vickyvxr. 

The version 5 beta has been released and should fix this issue.  The cross tab feature received a ground up rewrite.  You can install it with `npm i react-idle-timer@next` and check out the docs at [https://idletimer.dev](https://idletimer.dev).  Im going to close this issue, but if you have any additional problems or concerns, feel free to open another one!
