### ISSUE TITLE
Feature request: trigger the onIdle function manually

### ISSUE THREAD

**Issue by madmaxlax** [SupremeTechnopriest/react-idle-timer#180]
Howdy!
this has helped us a lot, we use it for logging out all tabs after inactivity. 

the cross tabs feature actually handles the logout on all tabs very well, i was wonder if it would be possible to open the 'onIdle' function to be triggered manually. 
say when a user clicks a logout button, it does the same thing on all tabs for us

thanks!

**Comment by SupremeTechnopriest** [comment]
Sure I can add this for you.  Ill be starting work on the v5 release in the next few weeks and you can look forward to that being exposed then!

**Comment by madmaxlax** [comment]
Wow thanks!

**Comment by RealDrewKlayman** [comment]
V5 is coming out soon?

**Comment by SupremeTechnopriest** [comment]
In the next two months. Soon as I get the time to focus on it uninterrupted.

**Comment by SupremeTechnopriest** [comment]
Hey Everyone!

The version 5 beta has been released and can be installed with `npm i react-idle-timer@next`.  I added a feature that exposes the underlying messaging layer for your own use.   In short I've added an [`onMessage`](https://idletimer.dev/docs/api/props#onmessage) callback and a [`message()`](https://idletimer.dev/docs/api/methods#message) method. You can check out the feature overview [here](https://idletimer.dev/docs/getting-started/new#cross-tab-messaging). 

If for some reason this does not fulfill your needs, feel free to open another issue.
