### ISSUE TITLE
Bug: crossTab.emitOnAllTabs will not trigger the onIdle from the second time when open more than 2 tabs

### ISSUE THREAD

**Issue by nenjamin2405** [SupremeTechnopriest/react-idle-timer#182]
I want to say thanks to this awesome library, it's easy to use and well organized. However I found a bug today and want to describe the reproduction steps to you:

1. Use the hook example like below
```javascript
import { useIdleTimer } from 'react-idle-timer';

export default function InactivityHandler() {
  const handleOnIdle = () => {
    console.log('user is idle');
    console.log('last active', getLastActiveTime());
  };

  const handleOnActive = () => {
    console.log('user is active');
    console.log('time remaining', getRemainingTime());
  };

  const handleOnAction = () => {
    console.log('user did something');
  };

  const { getRemainingTime, getLastActiveTime } = useIdleTimer({
    timeout: 10000,
    onIdle: handleOnIdle,
    onActive: handleOnActive,
    onAction: handleOnAction,
    debounce: 500,
    crossTab: {
      emitOnAllTabs: true,
    },
  });
  return <div></div>;
}

```

2. Open 1 tab and test the functionality. It works well in this case, onIdle will be always called whenever I'm idle for 10 seconds.

3. Open 2 tabs and test the functionality. It still works well, onIdle will be always called whenever I'm idle for 10 seconds.

4. Open 3 tabs and test the functionality. At the first time I'm idle, the onIdle is triggered, then I start to move the mouse to trigger the onActive and onAction, then I try to be idle again. At this moment, the onIdle will never be called again.

5. When I close the 3rd tab, then the onIdle will be called normally again without any problem.

I already tried with 4 tabs and the problem occurs again. My conclusion is that Bug: crossTab.emitOnAllTabs will not trigger the onIdle from the second time when open more than 2 tabs. Could you please help me to check this issue, thank you!

**Comment by anupamabauri** [comment]
I am also facing the same issue.

**Comment by anupamabauri** [comment]
@SupremeTechnopriest Please check the issue and help resolve this. 
Thank you

**Comment by SupremeTechnopriest** [comment]
Hi everyone!

The version 5 beta has just been released and it should resolve this issue.  The cross tab feature has been rewritten from the ground up and throughly tested.  You can install it with `npm i react-idle-timer@next` and check out the new docs at [https://idletimer.dev](https://idletimer.dev).  I'm going to close this issue, but if you are still experiencing problems on v5, feel free to open another one.
