### ISSUE TITLE
Please consider making this repo eligible for `hacktoberfest`

### ISSUE THREAD

**Issue by drecali** [SupremeTechnopriest/react-idle-timer#186]
@SupremeTechnopriest thank you so much for maintaining such a useful library!

Would you be willing to participate in Hacktoberfest (https://hacktoberfest.digitalocean.com/). It's a yearly initiative to encourage people to contribute to open source project. For some, this is their first OS experience.I think this would be a good way to encourage more contributions on the repo. All you have to do is tag the repo with the `hacktoberfest` topic. Here is more information: https://hacktoberfest.digitalocean.com/resources/maintainers

It seems like you're super busy, so I understand if you don't have time to do this. However, I hope your schedule provides a bit of time to participate.

Thanks again for maintaining such a useful library and continuing to improve it!

**Comment by SupremeTechnopriest** [comment]
Hey @drecali!

The version 5 beta has been released and it includes the [contributing guide](https://idletimer.dev/docs/about/contributing), issue templates and pull request templates.  I went ahead and added the `hacktoberfest` topic so we will be good to go for this year!

**Comment by drecali** [comment]
Thanks for the update @SupremeTechnopriest!
Sorry for the late reply! This got buried in my notifications. Wishing you a smooth `hacktoberfest`! I'll do my best to contribute even before the event :)
