### ISSUE TITLE
onIdle even handler function is not invoked as per 'timeout' until tab is active on ipad (safari)

### ISSUE THREAD

**Issue by ShrikantGit88** [SupremeTechnopriest/react-idle-timer#187]

**Comment by salihvs** [comment]
This happens in chrome too. When I'm idle for the timeout, onIdle event doesn't fire but after I stop being idle it fires. 

This should work when the user isn't active not when the user is active. I use version 4.6.4

**Comment by SupremeTechnopriest** [comment]
I have a fix for this in v5. I'm just wrapping up the new test suite and I will have a beta ready for testing. Hopefully by the weekend.

**Comment by SupremeTechnopriest** [comment]
Hey @ShrikantGit88 and @salihvs,

The version 5 beta has been released and can be installed with `npm i react-idle-timer@next`.  All timers have been moved into web-workers.  This will mitigate the effects you are seeing here. You can check out the docs at [https://idletimer.dev](https://idletimer.dev).  Im going to close this issue, but if you are still experiencing problems with v5.  Feel free to open another one.

**Comment by salihvs** [comment]
Thanks @SupremeTechnopriest, will check out v5
