### ISSUE TITLE
using crossTab not working when first tab is already Idle

### ISSUE THREAD

**Issue by ET-CS** [SupremeTechnopriest/react-idle-timer#188]
There is a bug that when new tab opened after another tab goes Idle, the Idle tab will not go into Active when `crossTab` is enabled.

Reproduce:
* open a tab
* wait for it to do idle
* open another tab
* work in the new tab (it's active)

expected:
The first tab which is Idle should be active

actual: 
The first tab will stay Idle and will not become Active even if the second tab is active.

**Comment by SupremeTechnopriest** [comment]
Hey @ET-CS!

I just released the version 5 beta.  The cross tab feature has been completely rewritten and this issue should be resolved now.  You can install it with `npm i react-idle-timer@next` and check out the new docs at [https://idletimer.dev](https://idletimer.dev).  Im going to close this issue, but if you are still experiencing problems, feel free to open a new one.
