### ISSUE TITLE
Memoized callbacks

### ISSUE THREAD

**Issue by Niks218** [SupremeTechnopriest/react-idle-timer#189]
Hi, thank you for your wonderful library!

Is it possible to return memoized versions of callbacks from `useIdleTimer` hook. Like to wrap `pause`, `isLeader` and so on in `useCallback` for example. Currently we use `eslint-plugin-react-hooks` in our project and it's challenging to have these callbacks in dependency array.

**Comment by SupremeTechnopriest** [comment]
Hey @Niks218!

I just released the v5 beta and all callbacks and methods are memoized.  You can test out the beta by installing from npm `npm i react-idle-timer@next`.  There are also new docs you can find at [https://idletimer.dev](https://idletimer.dev).  Going to close this, but if you are still having issues with memoization, feel free to open another issue.
