### ISSUE TITLE
Using PropTypes from React shows warning, use prop-types instead

### ISSUE THREAD

**Issue by m0hitk** [SupremeTechnopriest/react-idle-timer#19]

**Comment by SupremeTechnopriest** [comment]
Sounds like i need to update things for the latest react.  Ill try to get to it this week, or feel free to send a PR!

**Comment by danielditgens** [comment]
I did! Please merge it.

**Comment by SupremeTechnopriest** [comment]
Sorry for the delay.  I've been very busy lately.  Im checking the PR and merging in now.

**Comment by SupremeTechnopriest** [comment]
All set. Pushed to npm as `1.4.0`
