### ISSUE TITLE
does it support on mobile browser as well?

### ISSUE THREAD

**Issue by mayurpatel6** [SupremeTechnopriest/react-idle-timer#192]
i have used react-idle-timer for my website and it is responsive. the issue is, when i remain idle on the mobile browser it does not log me out (timeout = 15 mins). so, i want to know if the library supports the mobile browser as well or not?
@SupremeTechnopriest

**Comment by SupremeTechnopriest** [comment]
Are you backgrounding the browser on the device?  If so the timers are likely getting throttled.  I will be working on version 5 over the holiday that will fix this issue.

**Comment by SupremeTechnopriest** [comment]
Hey @mayurpatel6,

I just released the beta of v5 and this issue should be resolved.  You can install it with `npm i react-idle-timer@next` and check out the docs at [https://idletimer.dev](https://idletimer.dev).  If your issue still persists on v5 feel free to open another issue.
