### ISSUE TITLE
Auto idle on document visibilitychange?

### ISSUE THREAD

**Issue by d9k** [SupremeTechnopriest/react-idle-timer#196]
How about automatically switching to idle mode if `document` event `visibilitychange` is being caught and `document.hidden: true`?

**Comment by SupremeTechnopriest** [comment]
Not a bad idea. I'm currently working on v5. Hope to have it out soon. I noticed what you are seeing in your other issue and that will be fixed. Thanks for the report.

**Comment by SupremeTechnopriest** [comment]
The version 5 beta has been released and it includes this new feature.  The property is called `immediateEvents`.  You can install the beta from npm with `npm i react-idle-timer@next` and check out the documentation at [https://idletimer.dev](https://idletimer.dev).  The documentation for this specific feature can be found [here](https://idletimer.dev/docs/api/props#immediateevents). If you experience any issues with the new feature, feel free to open a new issue.
