### ISSUE TITLE
Reset doesn't reset the timer.

### ISSUE THREAD

**Issue by richacodesofficial** [SupremeTechnopriest/react-idle-timer#202]
Reset doesn't reset the timer, tried running the code from examples of the official repo (hook-ts).
Removed some code.
App.tsx: 
/* eslint-disable react-hooks/exhaustive-deps */
import React, { useState, useEffect } from 'react'
import { format } from 'date-fns'
import { useIdleTimer } from 'react-idle-timer'

export default function App () {
  const timeout = 500000000;
  const [remaining, setRemaining] = useState(timeout)
  const [elapsed, setElapsed] = useState(0)
  const [lastActive, setLastActive] = useState(+new Date())
  const [lastEvent, setLastEvent] = useState('Events Emitted on Leader')
  const [leader, setLeader] = useState(true)

  const handleOnActive = () => setLastEvent('active')
  const handleOnIdle = () => setLastEvent('idle')

  const {
    reset,
    pause,
    resume,
    getRemainingTime,
    getLastActiveTime,
    getElapsedTime,
    isIdle,
    isLeader
  } = useIdleTimer({
    timeout,
    //onActive: handleOnActive,
    onIdle: handleOnIdle,
    // crossTab: {
    //   emitOnAllTabs: true
    // }
  })

  const handleReset = () => reset()
  const handlePause = () => pause()
  const handleResume = () => resume()

  useEffect(() => {
    setRemaining(getRemainingTime())
    setLastActive(getLastActiveTime())
    setElapsed(getElapsedTime())

    setInterval(() => {
      setRemaining(getRemainingTime())
      setLastActive(getLastActiveTime())
      setElapsed(getElapsedTime())
      setLeader(isLeader())
    }, 1000)
  }, [])

  return (
    <div>
      <div>
        {/* <h1>Timeout: {timeout}ms</h1> */}
        <h1>Time Remaining Sample: {remaining}</h1>
        {/* <h1>Time Elapsed: {elapsed}</h1> */}
        {/* <h1>Last Active: {format(lastActive, 'MM-dd-yyyy HH:MM:ss.SSS')}</h1> */}
        <h1>Last Event: {lastEvent}</h1>
        {/* <h1>Is Leader: {leader.toString()}</h1> */}
        {/* <h1>Idle: {isIdle().toString()}</h1> */}
      </div>
      <div>
        <button onClick={handleReset}>RESET</button>
        <button onClick={handlePause}>PAUSE</button>
        <button onClick={handleResume}>RESUME</button>
      </div>
    </div>
  )
}

**Comment by SupremeTechnopriest** [comment]
Reset is pretty throughly tested.  Either way,  v5 is right around the corner.  Its a from scratch rewrite so I wont be supporting v4.  Im currently just finishing up the test suite and i hope to have a release candidate out soon.

Hang tight!

**Comment by richacodesofficial** [comment]
I'm expecting reset to reset the timer to reset to starting value(timeout) and not to the last  incremented value.
const timeout = 500000000;
Something like reinitializing the timer value.
Is reset expected to do that or some other method available ?

**Comment by SupremeTechnopriest** [comment]
Hey @richacodesofficial! The version 5 beta has been released and it should resolve your issue.  You can install the beta from npm with `npm i react-idle-timer@next` and check out the documentation at [https://idletimer.dev](https://idletimer.dev).  I'm going to close this issue.  If your issue persists on v5 please open another issue.
