### ISSUE TITLE
Timeout using old timeout value

### ISSUE THREAD

**Issue by hortizgarrido** [SupremeTechnopriest/react-idle-timer#204]
I have functional component that uses the non-hook for of react-ifle-timer. The initial timeout is set on load (ex. 30 mins) but a user has the option to set a different timeout via a modal (ex 45 min). I have the new timeout set to a state. I then call reset(). When doing so, the timeout is still using the old timeout and not the user’s new timeout entered.

**Comment by SupremeTechnopriest** [comment]
Thanks for the report. I am within days of releasing version 5 and it should fix your issue. The code and tests are all done, just working on finishing up the documentation. I will let you know when you can update.

**Comment by SupremeTechnopriest** [comment]
Hello @hortizgarrido!  Version 5 has been released and it should resolve your issue.  You can install the beta from npm with `npm i react-idle-timer@next` and check out the documentation at [https://idletimer.dev](https://idletimer.dev).  Im going to close this issue.  If your issue persists on v5 please open another issue.
