### ISSUE TITLE
Uncaught ReferenceError: Global is not defined

### ISSUE THREAD

**Issue by owen-deepsee** [SupremeTechnopriest/react-idle-timer#212]
### Affected Module

- `Version`: 5.0.0-rc.9

### Describe the bug

When using Create React App 5 + TypeScript in Yarn 2 with React Idle Timer, my application immediately errors out with `Uncaught ReferenceError: global is not defined` before it can do the initial render. The culprit is [Line 123 in BroadcastChannel.ts](https://github.com/SupremeTechnopriest/react-idle-timer/blob/64cadd909ffdb0535236ee9853af65fda1ef63fd/src/TabManager/BroadcastChannel.ts#L123)

### To Reproduce

Install CRA
Install React Idle Timer
Add a timer to the application

### Expected behavior

The application to run and not error out.

### System Information (please complete the following information)

 - `OS`: MacOS Monterey
 - `Device`: Laptop
 - `Browser Vendor`: Brave
 - `Browser Version`: 1.34.81

### Additional context

A workaround that makes it work for me is to add `<script>window.global = window</script>` to my `index.html` which gets executed before any React . I believe the actual solution would be to replace `global` with `globalThis` in `BroadcastChannel.ts` which in a browser would point to `window` as it expects. See [the MDN page on globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) for browser compatibility.

**Comment by SupremeTechnopriest** [comment]
Thanks for the report!  I can add DOM libs and change this to `window` and it should resolve the problem.  Seems to be a brave specific issue.  Theres no issues on the 3 major browsers.

**Comment by SupremeTechnopriest** [comment]
Hey @owen-deepsee, 

Can you test out `5.0.0-rc.10`?  It should resolve your issue.

**Comment by owen-deepsee** [comment]
@SupremeTechnopriest - Love the quick response time! RC-10 fixes it, I am able to remove my workaround and it works great. Thanks!

**Comment by SupremeTechnopriest** [comment]
Awesome!  Thanks again for finding the bug.  Im going to close this issue!
