### ISSUE TITLE
mjs file breaking CRA on react-idle-timer v5 release

### ISSUE THREAD

**Issue by bhattaraib58** [SupremeTechnopriest/react-idle-timer#213]
## Bug information
Idle timer seems to have import and module export as mjs file. It is breaking react application (made using JS based Create React App v4.0.3).

### Affected Module
- `Version`: react-idle-timer@5.0.0-rc.11

### Describe the bug
I am using application with Create React App v4.0.3 which is in Javascript (not TS). When I import the new react-idle-timer and try to run the application. I am getting following error:

Failed to compile
./node_modules/react-idle-timer/dist/index.mjs
Can't import the named export 'createContext' from non EcmaScript module (only default export is available)

It seems to fail in compilation due to the following lines in react-idle-timer:
```
"exports": {
    ".": {
      "require": "./dist/index.js",
      "import": "./dist/index.mjs",
      "types": "./dist/index.d.ts"
    }
  },
 "module": "./dist/index.mjs",
```

when changed to:
```
"exports": {
    ".": {
      "require": "./dist/index.js",
      "import": "./dist/index.js",
      "types": "./dist/index.d.ts"
    }
  },
 "module": "./dist/index.js",
```
then the package works as intended.

### To Reproduce

1. npx create-react-app my-app
2. CRA only comes with latest react-scripts, so install 4.0.3 version, 
    `npm install --save --save-exact react-scripts@4.0.3`
		or
	`yarn add --exact react-scripts@4.0.3`
3. Install idle timer: `npm i react-idle-timer@5.0.0-rc.11`
4. Import the package:
    `import { useIdleTimer } from 'react-idle-timer';`
5. run `npm start` or `yarn start`
6. See error.

Maybe different error based on imports but same mjs file error:
```
index.js:1 Uncaught Error: Module parse failed: Unexpected token (632:14)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
|   B(() => {
>     _.current?.cancel && _.current.cancel(), a > 0 ? _.current = Be(L, a) : u > 0 ? _.current = ve(L, u) : _.current = L;
|   }, [L, u, a]);
| 
    at Object../node_modules/react-idle-timer/dist/index.mjs
```

### Expected behavior
It requires a good amount of effort just to use just mjs file. I think there is no reason that .mjs extension is needed to indicate a ESM file.

### Screenshots
![Screen Shot 2022-02-22 at 3 14 20 PM](https://user-images.githubusercontent.com/15843175/155235533-8bfaeacf-69d6-45a2-8172-fe0976d848d4.png)

### System Information (please complete the following information)

 - `OS`: macOS Monterey v12.2 M1
 - `Device`: Desktop
 - `Browser Vendor`: chrome
 - `Browser Version`: Version 98.0.4758.102 (Official Build) (arm64)

**Comment by SupremeTechnopriest** [comment]
@bhattaraib58,

Ah thats no problem.  I can change the `esm` export to have the `.js` extension and it should all work out of the box.  Give me a few.

**Comment by SupremeTechnopriest** [comment]
@bhattaraib58,

Can you try `5.0.0-rc.12`. It should fix your issue.

**Comment by bhattaraib58** [comment]
@SupremeTechnopriest thank you `react-idle-timer@5.0.0-rc.12` fixed the issue.

**Comment by SupremeTechnopriest** [comment]
Awesome!  Thanks for reporting the bug.  I'm going to close this issue now!

**Comment by baselbj** [comment]
same issue on 5.0.0-rc.16

**Comment by SupremeTechnopriest** [comment]
Hey @baselbj,

Could you show me your webpack config?  Also which version of webpack are your using?  Is the line you pasted the line its throwing on?

**Comment by baselbj** [comment]
I am using create react app(react-scripts 4.0.3) with https://github.com/gsoft-inc/craco. Yes this is the line it is throwing.

**Comment by baselbj** [comment]
@SupremeTechnopriest Thank you ... I just updated my react-scripts to 5.0.0 and it works but with some warnings, about 20 warnings. Those are the first tow:

```
WARNING in ./node_modules/react-idle-timer/dist/index.esm.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/basel/Development/shamlisfrontend/node_modules/react-idle-timer/node_modules/fast-unique-numbers/build/es5/bundle.js' file: Error: ENOENT: no such file or directory, open '/home/basel/Development/shamlisfrontend/node_modules/react-idle-timer/node_modules/fast-unique-numbers/build/es5/bundle.js'
```
```
WARNING in ./node_modules/react-idle-timer/dist/index.esm.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/basel/Development/shamlisfrontend/node_modules/react-idle-timer/node_modules/worker-timers-broker/src/guards/call-notification.ts' file: Error: ENOENT: no such file or directory, open '/home/basel/Development/shamlisfrontend/node_modules/react-idle-timer/node_modules/worker-timers-broker/src/guards/call-notification.ts'
```

**Comment by SupremeTechnopriest** [comment]
thats odd.  It shouldn't be looking in node_modules.  Everything gets bundled.  Can you show me how you are importing idle timer?

**Comment by baselbj** [comment]
just like the example:
import {useIdleTimer} from 'react-idle-timer';

**Comment by SupremeTechnopriest** [comment]
Okay I can fix that by disabling source maps I think.  Its looking for sourcemaps that don't exist because everything is bundled.

**Comment by SupremeTechnopriest** [comment]
@baselbj `5.0.0-rc.17` should get rid of those warnings for you.

**Comment by baselbj** [comment]
@SupremeTechnopriest thank you it is working perfectly

**Comment by SupremeTechnopriest** [comment]
This will also work with webpack v4 now as well.
