### ISSUE TITLE
Activity not being detected when onPrompt is called

### ISSUE THREAD

**Issue by bhattaraib58** [SupremeTechnopriest/react-idle-timer#214]
## Bug information
When the onPrompt is active, onAction and onActive are not being called on user activity.

### Affected Module

- `Version`: 5.0.0-rc.12

### Describe the bug
I can't say for sure if its bug or by design.

By looking at documentation:
`https://idletimer.dev/docs/features/idle-detection`
[onActive](https://idletimer.dev/docs/props#onactive): Function called when a user becomes active from an idle state.

`https://idletimer.dev/docs/features/activity-detection`
[onAction](https://idletimer.dev/docs/props#onaction): Function called each time an event is triggered.

### To Reproduce

1. Set configuration as follow:
```
  const { start , reset, pause } = useIdleTimer({
    crossTab: false,
    emitOnAllTabs: false,
    stopOnIdle: false,
    startManually: true,
    timeout: WAIT_TIME_FOR_TIMEOUT,
    promptTimeout: WAIT_TIME_FOR_PROMPT,

    onPrompt: handleOnPrompt,
    onIdle: handleOnIdle,
    onActive: handleOnActive,
    onAction: handleOnAction
  });
```
and call start or reset

2. Perform events (move mouse),  onAction / onActive should call callback based on action (as expected)
3. Wait few time defined in WAIT_TIME_FOR_TIMEOUT for prompt to appear
4. Perfrom action (i.e: move mouse) such that prompt can go away
5. onAction/onActive is not called/not recorded. (Issue)
6. WAIT_TIME_FOR_PROMPT time runs out, onIdle gets triggered it calls callback, then only onAction and onActive actions will call callbacks if/when user shows activity

### Expected behavior
When onPrompt is called, ideally developers show dialog stating that user is inactive and perform some action(move mouse/ keyboard) to show activity and make the prompt disappear.

Since the onAction/onActive is disabled (*?). there is no way to find out if user had activity during onPrompt period.

The expected behaviour should be onAction / onActive being called or maybe some other action being called that shows user is now during onPrompt phase.

Ideally I think onAction should be called (as stated in documentation):
`https://idletimer.dev/docs/features/activity-detection`
[onAction](https://idletimer.dev/docs/props#onaction): Function called each time an event is triggered.

### Screenshots
__

### System Information (please complete the following information)
 - `OS`: macOS Monterey v12.2 M1
 - `Device`: Desktop
 - `Browser Vendor`: chrome
 - `Browser Version`: Version 98.0.4758.102 (Official Build) (arm64)

**Comment by SupremeTechnopriest** [comment]
Hey @bhattaraib58,

This is actually by design. When the prompt is open, I don't think we would want user activity to reset it.  It would be jarring to the user to see a prompt briefly and then move the mouse to have it disappear.  So when the prompt is active, all events are unbound and either the prompt will expire calling `onIdle`, or the user clicks your `Im Still Here` button at which point you would call `reset()`.  Calling reset will emit `onActive` and you can use that to hide your prompt. 

Having the timer still emit `onAction` is probably a good idea, but that change will take a little time because I will have to update all the surrounding tests and stuff.  I will work on it this week and let you know when a new release candidate is out.

**Comment by bhattaraib58** [comment]
@SupremeTechnopriest thank you. I didn't knew that it was by design.
It's a good enhancement to have but not a must-have. Thank you for looking into it.

**Comment by SupremeTechnopriest** [comment]
No problem! I have a rollout coming up tomorrow for my day job, but I should have some time on Thursday to sort this out.

**Comment by SupremeTechnopriest** [comment]
Hey @bhattaraib58!

Try out `5.0.0-rc.16`.  The `onAction` event should be emitted while the prompt is open.  So if you want user activity to close the prompt automatically, you can piggyback on `onAction`!

This was a good suggestion.  Thanks for your input!  If there are any issues, feel free to reopen this.
