### ISSUE TITLE
Missing TypeScript declarations file './types/IIdleTimerProps' causes compilation errors

### ISSUE THREAD

**Issue by mszmida** [SupremeTechnopriest/react-idle-timer#216]
### Affected Module

- `Version`: **5.0.0-rc.12**

### Describe the bug

In the `index.d.ts` file there is an export of the `IIdleTimerProps` type that should be defined in the missing file `./types/IIdleTimerProps` which results in TypeScript compilation errors. Probably something went wrong during the library building phase.

### To Reproduce

1. Install the latest RC version (**5.0.0-rc.12**) in any TypeScript project:
`npm install --save react-idle-timer@next`
2. Try to compile the TypeScript project:
`npx tsc`
3. You will see the following errors:
`error TS2307: Cannot find module './types/IIdleTimerProps' or its corresponding type declarations.`

### Expected behavior

A library source code does not break any TypeScript project compilation.

### Screenshots
Compilation errors visible below:

![image](https://user-images.githubusercontent.com/6221149/155801080-edc837c1-fdce-4860-980c-e72735a61d3a.png)

### System Information (please complete the following information)

 - `Windows 10`,
 - `react v17.0.2`,
 - `vite v2.8.2`,
 - `typescript v4.5.5`.

### Additional context

This issue prevents use in TypeScript projects. Please take a look ASAP. Should be an easy fix for you 😉 

Thank you for the library and your effort! 👍

**Comment by SupremeTechnopriest** [comment]
@mszmida Thanks for the report!  I will take a look at it this weekend!

**Comment by SupremeTechnopriest** [comment]
I found the issue.  Should have a fix for you tomorrow.

**Comment by mszmida** [comment]
@SupremeTechnopriest That's great news. Thank you very much for the quick response 👍

**Comment by mszmida** [comment]
@SupremeTechnopriest Confirmed. It works like a charm. Thanks for a quick fix!
