### ISSUE TITLE
404s in the docs

### ISSUE THREAD

**Issue by hangtwenty** [SupremeTechnopriest/react-idle-timer#218]
## Bug information

It seems like a few links have broken in the new docs.

### Affected Module

Latest on idletimer.dev

### To Reproduce

1. Go to any of these pages:
	* https://idletimer.dev/docs/features/idle-detection
	* https://idletimer.dev/docs/features/activity-detection
	* https://idletimer.dev/docs/features/confirm-prompt
	* https://idletimer.dev/docs/features/cross-tab
2. Then click on any of the links in the lists of "Properties" or "Methods".
3. You'll get a 404 for each of them.

### Expected behavior

Either workings links/anchors (or if it really does not link to anything, it shouldn't be marked up as a link)

**Comment by SupremeTechnopriest** [comment]
Thanks for the report!  I will get this fixed this weekend.

**Comment by SupremeTechnopriest** [comment]
This has been resolved.  Thank you for the report!
