### ISSUE TITLE
The worker-timers library cannot be properly mocked in Jest

### ISSUE THREAD

**Issue by mszmida** [SupremeTechnopriest/react-idle-timer#219]
### Affected Module

- `Version`: **5.0.0-rc.13**

### Describe the bug

According to the [Mock Worker Timers](https://idletimer.dev/docs/getting-started/testing#mock-worker-timers) documentation the following code should be sufficient to mock [worker-timers](https://github.com/chrisguttandin/worker-timers) library:

```javascript
jest.mock('worker-timers', () => ({
  setTimeout: setTimeout,
  clearTimeout: clearTimeout,
  setInterval: setInterval,
  clearInterval: clearInterval
}))
```

Unfortunately mock is not applied correctly and a real module implementation is executed. This may be connected to the `worker-timers` library that is not installed by the `react-idle-timer` as its own dependency. Take a look at the `package.json` file where `worker-timers` library is defined in `devDependencies` section:
https://github.com/SupremeTechnopriest/react-idle-timer/blob/1e38f1352e44dc66ec37e04474ccfa1f538f0bc4/package.json#L64

### To Reproduce

1. Create simple TypeScript project and install the latest RC version (**5.0.0-rc.13**):
`npm install --save react-idle-timer@next`
2. Create a component that will utilize `useIdleTimer()` hook.
3. Create a Jest setup according to the [Full Mock](https://idletimer.dev/docs/getting-started/testing#full-mock) documentation.
4. Create a simple test in Jest that renders the component by the usage of `@testing-library/react`.
5. You will see the following error:
`Error: Uncaught [TypeError: URL.createObjectURL is not a function]`

### Expected behavior

The `worker-timers` library is mocked properly and component can be rendered without any errors.

### Screenshots
The `react-idle-timer` has no `node_modules` directory with the `worker-timers` library:

![image](https://user-images.githubusercontent.com/6221149/156800979-cea105b9-7776-43ce-894a-4ca13bef1f3e.png)

### System Information (please complete the following information)

- `Windows 10`,
- `react v17.0.2`,
- `jest v27.5.1`,
- `ts-jest v27.1.3`,
- `@testing-library/react v12.1.3`,
- `typescript v4.6.2`.

### Additional context

N/A

**Comment by pocketbookbrando** [comment]
I am also experiencing this inability to mock worker-timers as suggested in the documentation. I am receiving the same error as the OP. Using latest version 5.0.0-rc.13.

**Comment by SupremeTechnopriest** [comment]
Ah, yes this actually makes sense since worker-timers actually gets bundled into the exported code.  Give me the weekend to come up with a solution.  I will update you here when its resolved.

**Comment by SupremeTechnopriest** [comment]
Thanks for the report @mszmida!

Can you try to update to `5.0.0-rc.15` and use the new `createMocks` function?  The documentation has been updated.

https://idletimer.dev/docs/getting-started/testing

This should do the trick.  If you are still having issues, please reopen this ticket!

**Comment by mszmida** [comment]
@SupremeTechnopriest Problem solved. Thanks!
