### ISSUE TITLE
No basic examples

### ISSUE THREAD

**Issue by poorpaddy** [SupremeTechnopriest/react-idle-timer#22]
Was looking for examples in the examples directory per the readme.md. Would be nice to see a couple of basic examples showing fire action after XX ms, resetting etc.

**Comment by SupremeTechnopriest** [comment]
Hey @poorpaddy.  The example can be found here https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/src_examples/App.js

If you run the examples, you will get a page where you can what you described here.  Just run `npm start` from this project.

**Comment by SupremeTechnopriest** [comment]
Looking at the examples again, I need to update them for the latest react.  You don't use refs like you used to, but you should be able to get an idea of how to use idle-timer.

**Comment by GenZai** [comment]
Yes it seems there is a problem with refs.
I get this.refs.idleTimer is undefined

**Comment by poorpaddy** [comment]
Yes, being new to react I wasn't really able to figure it out. Now that I've had a couple weeks of experience I get it. The doc should be updated though and maybe a simple helloworld level of example.
