### ISSUE TITLE
multiple tab issue 

### ISSUE THREAD

**Issue by shashika18923** [SupremeTechnopriest/react-idle-timer#220]
## Question

when I using this component I used that cross tab feature to use multiple tabs but if I used another web application in another tab in same browser the idle timer is not working can you help me to solve that.

**Comment by SupremeTechnopriest** [comment]
Hello @shashika18923!

When you say "another web application" is it the same site?  You cant communicate to other tabs across origins so the other web app would have to be on the same origin for cross tab to work.  The only way to message across tabs on two different web apps is to get a server involved, probably with web sockets.  

Which version of IdleTimer are you running?

**Comment by shashika18923** [comment]
No as an example I'm using my web application in localhost and same time I'm using Facebook in same browser on another tab when I'm doing that the idle time is not triggering. I think component is taking user is active if we used another web application in same browser. is there any way to fix that issue.

**Comment by SupremeTechnopriest** [comment]
You're using version 5? Cross tab wouldn't apply here. The normal timer should work just fine for that case. Can you show me how you are initializing IdleTimer?

**Comment by SupremeTechnopriest** [comment]
It's been a bit since I have heard from you.  If you are still having issues, feel free to reopen this.
