### ISSUE TITLE
IdleTimerProvider triggers 'React is not defined' error 

### ISSUE THREAD

**Issue by specialdoom** [SupremeTechnopriest/react-idle-timer#221]
## Bug information
IdleTimerProvider triggers 'React is not defined' error 

### Affected Module

- `Version`: 5.0.0-rc.16

### Describe the bug

Using ```IdleTimerProvider``` over the app triggers 'React is not defined' error.

### To Reproduce

1. Install react-idle-time@next
2. Import ```IdleTimerProvider```
3. Wrap the app with ```IdleTimerProvider```
4. See error.

### Expected behavior

App to compile correctly

### Screenshots

SB: https://stackblitz.com/edit/react-7cneax

### System Information (please complete the following information)

 - `OS`: Windows 10
 - `Device`: Desktop
 - `Browser Vendor`: chrome
 - `Browser Version`: 99

**Comment by SupremeTechnopriest** [comment]
Thanks for the report @specialdoom!  I will take a look at this today.

**Comment by SupremeTechnopriest** [comment]
Hey @specialdoom, Can you tell me what version of react you are using?

**Comment by jinweiri-only** [comment]
Got the same issue!

**Comment by SupremeTechnopriest** [comment]
Resolved in `5.0.0-rc.17`!  Reopen if you still have issues!
