### ISSUE TITLE
isPrompted, promptTimeout, onPrompt in useIdleTimer is not working

### ISSUE THREAD

**Issue by deepikazuci** [SupremeTechnopriest/react-idle-timer#222]
## Question

![doubt](https://user-images.githubusercontent.com/95339477/157861816-814c45a7-d8d1-4f16-8dab-ed1a5b65be2a.PNG)
This is my code,

I wanted to set up a modal by using onPrompt and promptTimeout properties. But it is not working as expected. I tried reinstalling the npm packing. But still, I couldn't bring that functionality.

**Comment by specialdoom** [comment]
What version are you using?

**Comment by deepikazuci** [comment]
Oh, Thanks. I was using `"react-idle-timer": "^4.6.4",`

Is onPrompt Feature stable in beta version, so that I can use it in production App??

**Comment by tugboat-m** [comment]
is there a timeline we can expect v5+ @specialdoom?

**Comment by SupremeTechnopriest** [comment]
Thanks for hopping on this @specialdoom. Im thinking the end of the month, middle of next month before releasing v5 out in the wild.  I want to give beta testers adequate time to put it through the paces so we can release it in a bug free state.  There was a lot of changes this patch.

**Comment by SupremeTechnopriest** [comment]
Im going to close this issue.  Please create another one if v5 doesn't fix it for you @deepikazuci!
