### ISSUE TITLE
Add option to sync timeout/prompTimeout between tabs

### ISSUE THREAD

**Issue by rowrowrowrow** [SupremeTechnopriest/react-idle-timer#224]
### Is your feature request related to a problem? Please describe.

This is related to https://github.com/SupremeTechnopriest/react-idle-timer/issues/223. I originally expected the crossTab behavior to keep each tabs timeout and prompTimeout countdowns in sync. Because each tab's countdowns are independent I ran into the issue described in https://github.com/SupremeTechnopriest/react-idle-timer/issues/223. 

Without syncing the countdowns it's likely that an inactive tab will expire while other tabs are still active. Additionally, if you use the remaining time for anything shared among tabs, like displaying a countdown, these will be out of sync.

### Describe the solution you'd like.

A boolean config option to keep timeout and prompTimeout countdowns in sync regardless of which tab has the leader status. I expect that this will only affect the countdowns.

I expect that the each tab will be synced with the leader's time.

I don't expect each tab to be perfectly synced at all times since it takes time for the tabs to communicate. But, I do expect it's possible to get their countdowns within a small margin for error.

I think a good approach might be for the leader to send their current time in the countdown and a timestamp for when that time was generated every single time the leader restarts their timeout or promptTimeout countdown. Then when the other tabs receive the message they can use their current timestamp and that information to calculate their remaining time. I'd be happy to help with this if needed.

### Describe alternatives you've considered.

The only solution I can find for myself is to somehow force them to be in sync.

### Additional context.

None.

**Comment by SupremeTechnopriest** [comment]
Closing this in favor of #223.  We can continue the discussion there.
