### ISSUE TITLE
Content Security Policy violation for version 5.0.0-rc.16

### ISSUE THREAD

**Issue by mschultz4** [SupremeTechnopriest/react-idle-timer#225]
### Affected Module

- `Version`: 5.0.0-rc.16

### Describe the bug

We are getting a Content Security Policy error when running 5.0.0-rc.16 version.  Version 4.6.4 works fine for us. 

```
Refused to create a worker from 'blob:https://oursite' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://oursite https://www.google-analytics.com/". Note that 'worker-src' was not explicitly set, so 
'script-src' is used as a fallback.
```

### To Reproduce

Run with our CSP and attempt to load the app.

### Expected behavior

No CSP error.

### System Information (please complete the following information)

 - `OS`: Windows 10 Enterprise
 - `Device`: Desktop
 - `Browser Vendor`: Chrome
 - `Browser Version`: 99.0.4844.51

**Comment by SupremeTechnopriest** [comment]
Hi @mschultz4!

This is because of a new feature that moves timers into a web worker to prevent background throttling from causing unintended behavior. If you want to use that feature you would have to create an exception in your CSP rules. If you can do with our it you can call the `createMocks` function to use native timers instead. I will actually make it a configuration option. 

As far as supporting threaded timers and strict CSP rules, that's probably a won't fix. I'd prefer to keep the worker as a blob url. It makes usage way easier and keeps the overall package size down. 

Stand by for an option to use native timers.

**Comment by mschultz4** [comment]
That sounds reasonable.  Thank you for the clarification!

**Comment by SupremeTechnopriest** [comment]
Hey @mschultz4!

Added `nativeTimers` prop in `5.0.0-rc.17`.  If you wan to keep your CSP rules strict you can use that, but you will have the same browser throttling effects as v4.

**Comment by SupremeTechnopriest** [comment]
Just an update on this.  I made some changes to help with treeshaking for those who wish to opt out of worker timers.  Basically I removed the `nativeTimers` property and replaced it with a `timers` property that takes an interface to replace the main thread timers. I also exposed an implementation of the interface that moves timers to a web worker (this will have the same CSP requirements as the old implementation).  You can find the relevant docs [here](https://idletimer.dev/docs/getting-started/new#web-worker-timers).

**Comment by mschultz4** [comment]
Awesome.  Thank you!

**Comment by tkpffi** [comment]
Hi @SupremeTechnopriest can you please provide a proper documentation for implementating the react idle timer with the latest version. Kindof a working project because we could see some issues. Thank you

**Comment by tkpffi** [comment]
Hi @mschultz4 if you have the working code of react idle timer can you please update the code snippets.

**Comment by SupremeTechnopriest** [comment]
There is extensive documentation on the docs site.  https://idletimer.dev/docs/api/use-idle-timer. Im planning on adding some code sandbox examples when I get some free time. Also checkout the https://idletimer.dev/docs/getting-started/new section to see how to use the new features.
