### ISSUE TITLE
isPrompted value changing between false and true when specifying events

### ISSUE THREAD

**Issue by aburleigh94** [SupremeTechnopriest/react-idle-timer#227]
### Affected Module

- `Version`: 5.0.0-rc.16

### Describe the bug

Adding a list of event types causes the prompt timeout to behave erratically due to isPrompted switching between true and false.

### To Reproduce

Codesandbox to reproduce the issue is here: https://codesandbox.io/s/react-idle-timer-events-issue-swnfcr?file=/index.js

When the events prop is specified, the prompt seems to get reset and is never closed. When the events prop is removed, the prompt counts down as expected.

### Expected behavior

The prompt will count down correctly using the isPrompted and getRemainingTime methods when the events property is specified

### System Information (please complete the following information)

 - `OS`: Windows 11
 - `Device`: Desktop
 - `Browser Vendor`: Edge
 - `Browser Version`:  99.0.1150.46

**Comment by SupremeTechnopriest** [comment]
Hey @aburleigh94,

Im not able to reproduce this with your code sandbox.  I tried it in chrome and in Edge (same version as you). The only difference here is Im still running Windows 10.  Windows 11 still has a lot of problems imo.  Would it be possible for you to open your code sandbox on another machine with a different os so we can rule that out?

**Comment by SupremeTechnopriest** [comment]
Scratch that, you mean the counter.  Confirmed.  Let me see whats going on.

**Comment by SupremeTechnopriest** [comment]
`5.0.0-rc.17` should fix the issue.  I added a test case to make sure it doesn't creep back in.  Reopen if you still have trouble.  I tried updating the code sandbox, but the module version cache is taking a while to update.

**Comment by SupremeTechnopriest** [comment]
Hmm according to the sandbox this is still broken... Gonna continue debugging.

**Comment by aburleigh94** [comment]
Thanks for the follow up, much appreciated. I'll continue to keep an eye out.

**Comment by SupremeTechnopriest** [comment]
@aburleigh94 Found the culprit!  The events array wasn't being properly memoized.  Applied the same fix to `immediateEvents` and added reliable tests.  You should be good to go now!

**Comment by aburleigh94** [comment]
Awesome! Thanks a lot!
