### ISSUE TITLE
Dynamic timeout value on useIdleTimer

### ISSUE THREAD

**Issue by Project-Omelet** [SupremeTechnopriest/react-idle-timer#228]
Before begin, thank you for making a awesome program.

I want to use this module in my project, but I have a problem.
Module version is 5.0.0-rc.16

This is common steps in my program.
1. When my app is started, do not start idle timer automatically.
2. User login user's account, then start idle timer
3. Mouse event occur (mouse move), do not fall into idle state.
4. If the mouse does not move for a specific time(timeout), it falls into a certain state and show idle lock page.
5. User can release this idle lock using user's account information.

This sequence works fine. But I change timeout value when app is running, always first timeout is available.

my code
```typescript
  // Timeout state, initial timeout is 1min
  const [timeout, setTimeout] = useState(1);

  // On Idle
  const onIdle = () => {
    console.log('Idle!!!!');

    batch(() => {
      // Show Idle modal
      dispatch(
        actions.modalActions.setIdleLockDialogStatus({ id: 'IdleLock' }),
      );
    });
  };

  // Action
  const onAction = () => {
    console.log('Mouse move!');
  };

  // idleLockTime is redux item, using useSelector
  const { start, pause } = useIdleTimer({
    timeout: 1000 * 60 * timeout,
    onIdle,
    onAction,
    startOnMount: false,  // before logged in, do not start idle timer
    startManually: true,
    stopOnIdle: true,
  });

  // idleLockTime is redux state variable
  useEffect(() => {
    if (authenticated) {
      // User success to login, start timer
      console.log('Start idle timer');
      console.log(`Idle timeout: ${idleLockTime}`);
      setTimeout(idleLockTime);
      start();
    } else {
      // User logged out, stop timer
      console.log('Stop idle timer');
      pause();
    }
  }, [authenticated, idleLockTime]);
```

This code always fall idle state after 1 min

What's the problem in my code?
Thank you

**Comment by SupremeTechnopriest** [comment]
this is just a hunch, but can you try changing your state to something like:

```js
const [timeoutValue, setTimeoutValue] = useState(1);
```

Then use those values in the rest of your code

```js
const { start, pause } = useIdleTimer({
    timeout: 1000 * 60 * timeoutValue,
    onIdle,
    onAction,
    startOnMount: false,  // before logged in, do not start idle timer
    startManually: true,
    stopOnIdle: true,
  });

  // idleLockTime is redux state variable
  useEffect(() => {
    if (authenticated) {
      // User success to login, start timer
      console.log('Start idle timer');
      console.log(`Idle timeout: ${idleLockTime}`);
      setTimeoutValue(idleLockTime);
      start();
    } else {
      // User logged out, stop timer
      console.log('Stop idle timer');
      pause();
    }
  }, [authenticated, idleLockTime]);
```

`setTimeout` is a javascript global and that might be why your state is not updating.

**Comment by Project-Omelet** [comment]
I fix [timeout, setTimeout] to [timeoutValue, setTimeoutValue] and run, but still work on 1min.
When I change idleLockTime other component, console print 'Start idle timer' and changed value..but still lock on 1min.
Did I use it wrong?

**Comment by SupremeTechnopriest** [comment]
A couple things worth noting:  IdleTimer v5 has built in prompting that you might want to consider using for your lock screen.  More on that [here](https://idletimer.dev/docs/getting-started/new#integrated-prompting).  Then you wouldn't need to use `stopOnIdle`.  

Maybe try one more thing, if this doesn't work I might need you to make a code sandbox so I can help you debug it. 

```js
const [timeoutValue, setTimeoutValue] = useState(1000 * 60);

const { start, pause } = useIdleTimer({
    timeout: timeoutValue,
    onIdle,
    onAction,
    startOnMount: false,  // before logged in, do not start idle timer
    startManually: true,
    stopOnIdle: true,
  });

  // idleLockTime is redux state variable
  useEffect(() => {
    if (authenticated) {
      // User success to login, start timer
      console.log('Start idle timer');
      console.log(`Idle timeout: ${idleLockTime}`);
      setTimeoutValue(idleLockTime * 1000 * 60);
      start();
    } else {
      // User logged out, stop timer
      console.log('Stop idle timer');
      pause();
    }
  }, [authenticated, idleLockTime]);```

**Comment by SupremeTechnopriest** [comment]
While you are at it try it with `stopOnIdle: false`.

**Comment by Project-Omelet** [comment]
Thank you for your prompt reply!
I change my code stopOnIdle false and move calculate logic to setTimeoutValue, but still not work on 5.0.0-rc.16.

But I downgrade version 4.6.4, it works.
Soon the deadline for the project came near, I'll use version 4.6.4.
After deadline, I make test code on code sendbox and share to you.

**Comment by SupremeTechnopriest** [comment]
Sounds good! I will try to recreate in tests in the mean time.

**Comment by SupremeTechnopriest** [comment]
I wrote this test which should recreate your scenario and it's passing.  

```js
    it('Should update when started manually', async () => {
        props.timeout = 400
        props.startOnMount = false
        props.startManually = true
        props.stopOnIdle = true
        const { result, rerender } = idleTimer()
        result.current.pause()
        expect(result.current.isIdle()).toBe(true)
        props.timeout = 200
        rerender(props)
        result.current.start()
        expect(result.current.isIdle()).toBe(false)
        await sleep(200)
        expect(result.current.isIdle()).toBe(true)
      })
```

This makes me think that something is preventing the new timeout from making it to IdleTimer.  Its concerning that the same code works in v4 but not in v5.  All the test coverage from v4 is also in v5.  Looking forward to taking a look at your reproduction.

**Comment by Project-Omelet** [comment]
Interesting...my code worked perfect on v4, but still not working v5, whicth factor prevent making new timeout..

Is it because of the problem with the project environment? My environment is as follows.
- React 17.0.2 (react-scripts 5.0.0)
- Electronjs 17.1.0 (chromium version: 98.0.4758.102)
- Typescript 4.5.5

And my final code (worked perfact on v4)
```typescript
import { useEffect, useState } from 'react';

import { useSelector, useDispatch, batch } from 'react-redux';
import { RootState } from 'src/renderer/stores';
import * as actions from 'src/renderer/stores/actions';

// Call ipcRenderer in electron module
import {
  nodeEvtSender,
  releaseNodeEvt,
} from 'src/renderer/endpoints/ipcInterface';

// Test: react-idle-timer 4.6.4 pass / v5 failed
import { useIdleTimer } from 'react-idle-timer';

type Props = {
  children: JSX.Element;
};

const IdleTimeout = (props: Props) => {
  const { authenticated, idleLockTime, idleTimerState } = useSelector(
    (state: RootState) => ({
      authenticated: state.system.authenticated,
      idleLockTime: state.system.idleLockTime,
      idleTimerState: state.system.idleTimerState,
    }),
  );
  const dispatch = useDispatch();

  const [timeoutValue, setTimeoutValue] = useState(idleLockTime * 1000 * 60);

  const onIdle = () => {
    console.log('Idle!!!!');
    // Spread idle state to apps
    nodeEvtSender('goIdleState');  // spread other apps

    batch(() => {
      // Show Idle modal
      dispatch(
        actions.modalActions.setIdleLockDialogStatus({ id: 'IdleLock' }),
      );
      dispatch(actions.systemActions.setIdleTimerState(false));
    });
  };

  const onAction = () => {
    console.log('Mouse move!');
  };

  const { start, pause } = useIdleTimer({
    timeout: timeoutValue,
    onIdle,
    onAction,
    startOnMount: false,
    startManually: true,
  });

  useEffect(() => {
    // Request Idle timer from electron
    nodeEvtSender('getIdleTimeValue').then((res: number) => {
      // Set timeout value
      dispatch(actions.systemActions.setIdleLockTime(res));
    });
    dispatch(actions.systemActions.setIdleTimerState(true));

    logger.system.info('idleTimer stared', 'IdleTimeout');
    console.log('idleTimer stared');
  }, []);

  // Auth & settings
  useEffect(() => {
    if (authenticated && idleTimerState) {
      // When user logged in, Reset timer
      console.log(`Start idle timer [login], timeout: ${idleLockTime}`);
      console.log(new Date());
      start();
    } else {
      // When user logged out, Stop timer
      console.log('Stop idle timer');
      console.log(new Date());
      pause();
    }
  }, [authenticated, isIdle]);

  useEffect(() => {
    if (authenticated && idleTimerState) {
      console.log(
        `Start idle timer [setting changed or idle lock state changed], timeout: ${idleLockTime}`,
      );
      setTimeoutValue(idleLockTime * 1000 * 60);
      console.log(new Date());
      pause();
      start();
    }
  }, [idleTimerState, idleLockTime]);

  return <div>{props.children}</div>;
};

export default IdleTimeout;

```

TGIF!

**Comment by SupremeTechnopriest** [comment]
You might want to add `authenticated` to your second `useEffect` dependencies.  Other than that this code looks good to me.  I will continue testing and see if I can make a test fail.

**Comment by SupremeTechnopriest** [comment]
@Project-Omelet This is published as `5.0.0-rc.18`.  I added tests so it should work the way you want it now!

**Comment by SupremeTechnopriest** [comment]
Sorry commented on the wrong ticket.  This is still open until we figure out whats going on.

**Comment by Project-Omelet** [comment]
@SupremeTechnopriest Hi! I installed 5.0.0-rc.19 on my project, and I met this error message
<img width="523" alt="image" src="https://user-images.githubusercontent.com/79133857/160959703-d450b696-cd83-4d6a-8c66-bd005fd8be66.png">

My code is changed using useIdleTimer hooks, add events manually (for remove visibilitychange)
```typescript
  const { start, pause } = useIdleTimer({
    timeout: timeoutValue,
    onIdle,
    onAction,
    startOnMount: false,
    startManually: true,
    events: [
      'mousemove',
      'keydown',
      'wheel',
      'DOMMouseScroll',
      'mousewheel',
      'mousedown',
      'touchstart',
      'touchmove',
      'MSPointerDown',
      'MSPointerMove',
    ],
  });
```

**Comment by SupremeTechnopriest** [comment]
Hmmm, interesting.  Thanks for checking.  Your project is electron if I'm not mistaken?

**Comment by Project-Omelet** [comment]
When app entered idle state, onIdle function send idle signal to electron (like backend server).
There's nothing else, but this. :)

**Comment by SupremeTechnopriest** [comment]
Okay good to know.  I will keep you posted.

**Comment by SupremeTechnopriest** [comment]
@Project-Omelet Fixed the illegal invocation.  Can you try version `5.0.0-rc.21`?

**Comment by SupremeTechnopriest** [comment]
Thanks for checking!

The only thing I can think of is that IdleTimer's state isn't being updated.  When you change the timeout, are you sure a rerender is being triggered?  Im not able to reproduce this on the demo page or in tests.  That would be the first step to getting this resolved.

**Comment by SupremeTechnopriest** [comment]
On second thought... I might have just reproduced it while investigating a bug with the new feature.  Will get back to you when I push a new release candidate.

**Comment by SupremeTechnopriest** [comment]
@Project-Omelet Can you give `5.0.0-rc.22` a shot?  Pretty sure I found and fixed the issue.  LMK!

**Comment by Project-Omelet** [comment]
@SupremeTechnopriest Wow!! It works!!!
I tested 5.0.0-rc.22 changed timeout 10 times, works perfect.
When v5 is ready, I'll update this module in my project immediately!
Thank you for dealing with my issue. I'm really appreciate!

**Comment by SupremeTechnopriest** [comment]
@Project-Omelet  YESSS!  We got it!  Thanks for finding the bug.  Much appreciated.  I expect to be releasing v5 within the next few weeks.  You can join the discord to get notified when it goes live (and other news) but I will also comment here when it has been released!

**Comment by SupremeTechnopriest** [comment]
@Project-Omelet v5 released!
