### ISSUE TITLE
Reset getElapsedTime when reset() method is called

### ISSUE THREAD

**Issue by Phalguna2125** [SupremeTechnopriest/react-idle-timer#229]
Hi,

Thanks for the awesome library,

While I was migrating from v4.6.4 to v 5 to leverage new methods of message and others, I have observed upon calling **reset() method.** The getElapsedTime() is automatically being reset to 0 in v4.

But in v5 it seems to not reset the time, I was using this **getElapsedTime()** and out sessionTimeout variable to check and add a background refresh call.

I am using useIdleTimer and here is my configuration
````

  // inactivity timer hook intialization
  const {getElapsedTime, pause, reset, getRemainingTime} = useIdleTimer({
    timeout: inactivityTimerTimeout,
    onIdle: handleOnIdle,
    onActive: handleOnActive,
    onAction: handleOnAction,
    crossTab: true,
    //onMessage: handleOnMessage,
    eventsThrottle: 500,
  });
````

Any idea we could reset getElapsedTime the same in v5 too.

Thanks in advance

**Comment by SupremeTechnopriest** [comment]
Hey @Phalguna2125,

This def sounds like a bug.  Let me add some tests to confirm.

**Comment by SupremeTechnopriest** [comment]
@Phalguna2125 

So I wrote this test which should cover this use case and its passing.

```js
it('Should reset when start or reset is called', async () => {
  props.timeout = 200
  const { result } = idleTimer()
  await sleep(100)
  expect(result.current.getRemainingTime()).toBeAround(100, 10)
  await waitFor(() => result.current.isIdle())
  expect(result.current.getRemainingTime()).toBe(0)
  result.current.reset()
  expect(result.current.getRemainingTime()).toBeAround(200, 10)
  await waitFor(() => result.current.isIdle())
  expect(result.current.getRemainingTime()).toBe(0)
  result.current.start()
  expect(result.current.getRemainingTime()).toBeAround(200, 10)
})
```

Any chance you can try to recreate in a code sandbox?

**Comment by Phalguna2125** [comment]
Hi @SupremeTechnopriest , can you check for **getElapsedTime** after reset, instead of getRemainingTime and let me know.
Any reason you were checking for getRemainingTime.?

i believe and verified the getRemainingTime was working well. In my case i was using elapsed time(getElapsedTime) to check difference between component mount time and session expiry time from my storage. although I also use getRemainingTime for modal popup until it becomes idle. The issues i was facing was with getElapsedTime.
Its pretty late for my timezone and I couldn’t sandbox at the moment. Would try to create  the scenario in sandbox by tomorrow at the earliest.

**Comment by SupremeTechnopriest** [comment]
Ah damn. I misread that.  Coming right up.

**Comment by SupremeTechnopriest** [comment]
So for elapsed time you want it to return the inverse of remaining time `timeout - getRemainingTime`.  I think right now its total elapsed time since the timer was mounted.

**Comment by Phalguna2125** [comment]
It keeps on incrementing now, instead of resetting when i call reset(). Can we just reset it to default when calling it or have a way to reset it , instead of getting total elapsed time.
I might not need inverse , but just a way to reset it. Because when using the way of hook initialization, i could remount them after extending session and set elapse time to default. Is it possible.?
In v4 we would get getElapsedTime as 0 after reset(). But the functionality now changed to overall time,.

**Comment by SupremeTechnopriest** [comment]
I will add a `getTotalElapsedTime` that behaves like the current implementation. Then I will make `getElapsedTime` reset like it did in v4.

**Comment by Phalguna2125** [comment]
Thanks a lot that would be great.

**Comment by SupremeTechnopriest** [comment]
@Phalguna2125 This is deployed as `5.0.0-rc.18`under the `next` tag.  Also updated the docs.  Everything is tested so it should do what you expect now!

**Comment by Phalguna2125** [comment]
Checked and its working as expected
