### ISSUE TITLE
Link broke

### ISSUE THREAD

**Issue by JSDUNIYA** [SupremeTechnopriest/react-idle-timer#235]
## Bug information
https://idletimer.dev/docs/getting-started/installation on this page 

To see what has updated in a given version of IdleTimer, you can check the [changelog](https://idletimer.dev/docs/changelog) or the [github releases](https://github.com/SupremeTechnopriest/react-idle-timer/releases).

github releases link doesn't seem to be working
### Affected Module

- `Version`: Put the module version number here (0.0.1)

### To Reproduce

4. See error.

### System Information (please complete the following information)

 - `OS`: [e.g. Windows 10, iOS 8.1]
 - `Device`: [e.g. iPhone6, Desktop]
 - `Browser Vendor`: [e.g. chrome]
 - `Browser Version`: [e.g. 75]

**Comment by SupremeTechnopriest** [comment]
Thanks for the report.  Will fix this today.

**Comment by SupremeTechnopriest** [comment]
Fixed!  Thanks again!
