### ISSUE TITLE
React 17 peer dependency

### ISSUE THREAD

**Issue by mschultz4** [SupremeTechnopriest/react-idle-timer#236]
## Question

Wondering why you are requiring React 17 as a peer dependency.  We are running 16 and have no issues with the latest IdleTimer RC.  Is there some feature we can't use while still on React 16?

**Comment by SupremeTechnopriest** [comment]
I can make it compatible with 16.  The reason why I bumped it was because I stopped importing React on every file that used jsx.  I will make it compatible with 16 later today.

**Comment by mschultz4** [comment]
Ignored.  Thanks again!

**Comment by SupremeTechnopriest** [comment]
React peer dependencies dropped to 16 in `5.0.0-rc.20`
