### ISSUE TITLE
support for react 16 :)

### ISSUE THREAD

**Issue by benmonro** [SupremeTechnopriest/react-idle-timer#24]

**Comment by SupremeTechnopriest** [comment]
Shouldn't be too hard.  We can start a PR.

**Comment by ValeryG** [comment]
yes, we really need this, please,  any updates @SupremeTechnopriest ?

**Comment by SupremeTechnopriest** [comment]
@ValeryG Sorry for the delay.  Been busy with my day job... I will go through and prep a new release tonight.

**Comment by benmonro** [comment]
@SupremeTechnopriest I did a PR to update it, works on my machine if you want to approve the PR and publish.  :)

**Comment by ValeryG** [comment]
@benmonro  - tested  your changes. Works just fine.

**Comment by benmonro** [comment]
cool, glad that works @ValeryG

**Comment by SupremeTechnopriest** [comment]
Nice! thanks @benmonro. Rolling out now.

**Comment by SupremeTechnopriest** [comment]
@ValeryG published as `react-idle-timer@1.6.0`
