### ISSUE TITLE
Please add getPromptRemainingTime

### ISSUE THREAD

**Issue by masterbater** [SupremeTechnopriest/react-idle-timer#240]
It would be nice if you could add getPromptRemainingTime.  For now I just make my own timer when onPrompt gets triggered

**Comment by SupremeTechnopriest** [comment]
When `isPrompted()` is true, `getRemainingTime()` returns the prompt remaining time. That should be what you want :)

**Comment by SupremeTechnopriest** [comment]
If for some reason thats not working for you (it should there are a bunch of tests), feel free to re open this.

**Comment by SupremeTechnopriest** [comment]
Here are the relevant docs https://idletimer.dev/docs/api/methods#getremainingtime

**Comment by masterbater** [comment]
Yup thank you I also read it here https://idletimer.dev/docs/features/confirm-prompt. 
Everything is well documented. Excited for the stable release

**Comment by SupremeTechnopriest** [comment]
Going to be adding a bunch of code sandbox examples to the docs as well.  If you join the discord you can stay up to date on the release.  I have an event for the release on April 22 at 5 PM PST. 

https://discord.gg/fjNdTG4k?event=961525880365121586

The current release candidate is most likely the last one.  I think we got all the bugs worked out.

**Comment by SupremeTechnopriest** [comment]
@masterbater v5 is released!

**Comment by masterbater** [comment]
Congratulations 🎉. I will surely update to stable release thanks for
informing me.
