### ISSUE TITLE
Throw an error when a crosstab feature activated Failed to execute 'postMessage' on 'BroadcastChannel': Channel is closed

### ISSUE THREAD

**Issue by emresandikci** [SupremeTechnopriest/react-idle-timer#242]
### Affected Module

- `Version`: 4.6.4

### Describe the bug

When activate the `crosstab ` feature and open a new tab with the same URL I getting an error like `Unhandled Rejection (InvalidStateError): Failed to execute 'postMessage' on 'BroadcastChannel': Channel is closed`

### To Reproduce

1. Run project 
2. When a project running on a browser tab copy the URL
3. Paste the URL into the new tab
4. See error.

### Expected behavior

There shouldn't be any error when I open the URL into the new tab and should be sync timer.

### Screenshots
![Screen Shot 2022-04-18 at 2 14 48 PM](https://user-images.githubusercontent.com/7765958/163801012-c13d4d8e-326a-4c03-9d34-76f2dc4a5bf7.png)

### System Information (please complete the following information)

 - `OS`: [macOS catalina 10.15.7 ]
 - `Browser Vendor`: [BRAVE]
 - `Browser Version`: Version 1.37.114 Chromium: 100.0.4896.88 ]

**Comment by SupremeTechnopriest** [comment]
Hi @emresandikci!

Could you please try the v5 beta?  V4 is at end of life and v5 is being promoted on Friday.  Join the discord for important announcements.  `npm i react-idle-timer@next`.  You can see the new docs here https://idletimer.dev.  Specifically you want to check the whats new section.

**Comment by emresandikci** [comment]
Hi @SupremeTechnopriest,

First of all, thanks for your quick answer, I will try it out tomorrow and let you know the result.

**Comment by SupremeTechnopriest** [comment]
Sure thing!  It's been very well beta tested and is definitely ready for production use.  Let me know if you have any problems getting started.
