### ISSUE TITLE
Cross tab support not working with multiple tabs

### ISSUE THREAD

**Issue by ssureez** [SupremeTechnopriest/react-idle-timer#244]
cross tab feature not working with more than two tab

### Affected Module

- `Version`: 4.6.4

### Describe the bug

react-idle-timer's cross tab support working with two tabs opened but when we open the third tab i see that onIdle callback is not invoked. 

### To Reproduce

`<IdleTimer
          ref={ref => {
            this.idleTimer = ref;
          }}
          timeout={1000 * 10}
          onActive={this.handleOnActive}
          onIdle={this.handleOnIdle}
          onAction={this.handleOnAction}
          debounce={250}
          crossTab={{ type: 'localStorage' }}
        />`

1. Add some log in onIdle callback function with 10 sec timeout
2. Open the application and wait for 10 sec and you will see a onIdle callback
3. open a Duplicate tab and go to second tab and then wait for 10 sec and you will see a onIdle callback in leader tab
4. open a Duplicate tab and go to third tab and then wait for 10 sec and you will see a onIdle callback in leader tab again. 
5. Wait for another 10 seconds and you will not get onIdle callback. it will be like user is active on the screen.

### Expected behavior

It should work regardless of opening multiple tabs

### System Information (please complete the following information)

 - `OS`: iOS 10.15.7
 - `Device`: Mac Book Laptop
 - `Browser Vendor`: FireFox
 - `Browser Version`: 98.0.2

**Comment by SupremeTechnopriest** [comment]
Hey @ssureez,

Can you try the v5 beta? `npm i react-idle-timer@next`.  Cross tab has been rewritten from scratch.  It's actually being promoted to the latest tag today and is definitely stable for production use.  You can check out the new docs site here. https://idletimer.dev. I suggest reading over the whats new section to start.  https://idletimer.dev/docs/getting-started/new

It's been tested by many people and its should work well for you.  If you have any issues feel free to re open this or stop by the discord.
