### ISSUE TITLE
CrossTab functionality

### ISSUE THREAD

**Issue by Niks218** [SupremeTechnopriest/react-idle-timer#246]
## Question
Hi, I have a small question I can't figure it out myself. 

In v4 I used `isLeader()` method to determine the main tab. This timer would send request to backend to close session, so I could send only one request. Other tabs just logged out user locally without sending request.
Do you have something similar in v5? It's not a feature request, I just wanna know how much I need to refactor my code.

Thank you again for this amazing library!

**Comment by SupremeTechnopriest** [comment]
Hey @Niks218!

Im about to go to bed, but you can take a look at this issue and it should point you in the right direction. 

https://github.com/SupremeTechnopriest/react-idle-timer/issues/243#issuecomment-1105673416

Im considering adding leader election back in V5, though it wouldn't isolate the events for you.  Events will be emitted on all tabs, and then you could just use `isLeader()` inside your events to determine what to do.  Its fairly simple to implement yourself, but it seems it was used by a few people, so I should probably put it on the roadmap for 5.1.0. 

I will be around tomorrow if you need more assistance. Otherwise let me know how it works out.

**Comment by Niks218** [comment]
Thank you!

Yes, this looks like working solution, I'll give it a try and reply here later.

**Comment by Niks218** [comment]
Hey @SupremeTechnopriest!

I tried to play around this issue today. I tried to use `beforeunload` event to notify other tabs about leader change, but I discovered that you use the same event, so I can't send message on this event because apparently channel is already closed at the moment.

Another thing I found, but didn't dig too deep, is that `onAction` handler is fired on mouse move event despite `throttle` setting be set. Only `eventsThrottle` can stop this madness. You can check this behavior on your demo site https://idletimer.dev/.

I'll try to implement this leader election logic without `beforunload` event and will keep it posted.

**Comment by SupremeTechnopriest** [comment]
Yeah that is true.  The message socket gets disconnect on `beforeunload`.  I will put it on the road map for v5.1 to add leader election back in.  I will look into the onAction throttle this weekend.

**Comment by SupremeTechnopriest** [comment]
@Niks218,

Im going to work on the leader detection today.  I looked into the throttle, and it seems to be working correctly.  All the tests are passing and I made a simple code sandbox to demonstrate it.  

https://codesandbox.io/s/stupefied-glade-db2hg8?file=/src/App.js

If you open the console, you will see that action is only logged once every 5 seconds.  Could you modify the sandbox to get it into the error state you described?  That would help me in debugging. Thanks!

**Comment by SupremeTechnopriest** [comment]
Hey @Niks218!

I just published `5.1.0` which brings back Leader Election.  There are some subtle differences from v4 that are outlined [here](https://idletimer.dev/docs/getting-started/new#leader-election).  Let me know how it goes.  Also, if you are able to recreate that throttle issue in a code sandbox for me, just re open this issue.

**Comment by Niks218** [comment]
@SupremeTechnopriest Just checked new release today. Works like a charm, thank you!

Regarding throttling problem I mentioned earlier. Turns out it was RTQ query that unexpectedly causes rerendering on every call. Sorry for bothering you with this nonexistent issue.

**Comment by SupremeTechnopriest** [comment]
No problem!
