### ISSUE TITLE
reactnode

### ISSUE THREAD

**Issue by johnilizy17** [SupremeTechnopriest/react-idle-timer#248]
## Bug information
Type '{}' is not assignable to type 'ReactNode'
### Affected Module
IdleTimer
- `Version`: Put the module version number here (0.0.1)
^4.6.4
### Describe the bug

it  don't make me compiler my work on vercel

### To Reproduce

4. See error.

### System Information (please complete the following information)

 - `OS`: [e.g. Windows 10, iOS 8.1]
 - `Device`: [e.g. iPhone6, Desktop]
 - `Browser Vendor`: [e.g. chrome]
 - `Browser Version`: [e.g. 75]

**Comment by SupremeTechnopriest** [comment]
Hi @johnilizy17, 

Version 4 is no longer supported.  Can you update to v5?  The relevant docs can be found here https://idletimer.dev/docs/getting-started/new
