### ISSUE TITLE
activeAction triggered unexpectedly

### ISSUE THREAD

**Issue by krizpoon** [SupremeTechnopriest/react-idle-timer#25]
I moved the `tId` from state variable to instance variable and it works well now.

**Comment by krizpoon** [comment]
Just like the React quick start guide [here](https://facebook.github.io/react/docs/state-and-lifecycle.html#adding-lifecycle-methods-to-a-class), I think that the setTimeout ID should be an instance variable.

**Comment by krizpoon** [comment]
Steps to reproduce this issue:
- calling reset() after activeAction is invoked but before the state of IdleTimer is updated

**Comment by SupremeTechnopriest** [comment]
Good catch @krizpoon.  Do you have a PR?  Otherwise ill make the change and push a new version today.

**Comment by krizpoon** [comment]
Sorry, I just copied the source code to my project to try things. So it'd be better to do it on your side :)

**Comment by SupremeTechnopriest** [comment]
@krizpoon no problem, ill get to it shortly

**Comment by SupremeTechnopriest** [comment]
@krizpoon this issue is resolved and published to npm as `1.5.1`

**Comment by krizpoon** [comment]
Awesome 🎉
