### ISSUE TITLE
withIdleTimer error: React is not defined

### ISSUE THREAD

**Issue by thaindq** [SupremeTechnopriest/react-idle-timer#250]
## Bug information
Unable to use `withIdleTimer` following the doc (https://idletimer.dev/docs/api/with-idle-timer). It's causing `React is not defined` error

### Affected Module
withIdleTimer

- `Version`: 5.1.0

### Describe the bug
ReferenceError: React is not defined
```
The above error occurred in one of your React components:
    at eval (https://7tmfcz.csb.app/node_modules/react-idle-timer/dist/index.cjs.js:1:2299)
    at div
    at App
```
### To Reproduce
https://codesandbox.io/s/withidletimer-7tmfcz?file=/src/App.tsx

### Expected behavior
A `timeout` message in console after 5s

### Screenshots
![image](https://user-images.githubusercontent.com/2677309/166339185-a6181bf9-32f3-45ba-9090-b96f0229ffea.png)

**Comment by SupremeTechnopriest** [comment]
@thaindq 

No problem I will fix this for you.  You are running react 16 I imagine?

**Comment by thaindq** [comment]
I'm running React 17

**Comment by SupremeTechnopriest** [comment]
Hmm I see.  You shouldn't have to import React for jsx anymore from v17 on.  Either way, this is an easy fix and Ill have it up shortly.  Just updating the docs now.

**Comment by SupremeTechnopriest** [comment]
Version `5.1.1` published.  That should resolve it for you.  Thanks for the report!

**Comment by thaindq** [comment]
Working great now. Thank you

**Comment by SupremeTechnopriest** [comment]
You are welcome!
