### ISSUE TITLE
Use cases for two idle timers on a page

### ISSUE THREAD

**Issue by MTamPham** [SupremeTechnopriest/react-idle-timer#252]
## Question

Firstly, thank you for making this great library.

Secondly, I am wondering if I could make two idle timers on a page? If so, how could I achieve this?

I've tried to add two IdleTimer components on a page where the component was created by using the withIdleTimer(). One has a different timeout from the other and there is a different popup for each timeout. If I set crossTab={false}, onIdle() could be called separately. But if I set it to be true, it's only called when the longer timeout has been reached.

Replicate: React 18 + react-idle-timer 5.1.3

Thanks in advance.

**Comment by MTamPham** [comment]
I apologize for the delay in getting back to you. I would need two idle timers in my application: one is for the session and the other one is for asking to continue playing the live view. Let's say the first one is 30 minutes and the other one is 5 minutes. If the user is idle for 5 minutes, I would ask whether they want to continue the live view? And if the user is idle long enough to 30 minutes, then of course I will log them out.

**Comment by MTamPham** [comment]
Thanks in advance

**Comment by SupremeTechnopriest** [comment]
@MTamPham,

Your feature request has been published to NPM as `5.2.0`.  You can set the name for your timer instance using the `name` prop. https://idletimer.dev/docs/api/props#name

Let me know if that works for you!

**Comment by MTamPham** [comment]
@SupremeTechnopriest,

Thank you for the quick update. I appreciate it. I've done a few simple checks and it seems to work flawlessly. I will contact you again if I found something.

**Comment by SupremeTechnopriest** [comment]
Glad to hear it!
