### ISSUE TITLE
getRemainingTime() returns incorrect time value

### ISSUE THREAD

**Issue by olefrank** [SupremeTechnopriest/react-idle-timer#256]
### Affected Module

- `Version`: 5.2.0

### Describe the bug

`getRemainingTime()` returns incorrect time when `promptTimeout` is used. It always returns `promptTimeout` even if prompt is visible. If "remaining time" is defined as "time until idle state is reached" `getRemainingTime()` return incorrect value.

### To Reproduce

1. Start the time manually with `idleTimer.start()`
2. Pass `idleTimer.getRemainingTime()` as prop to prompt component
3. Call `idleTimer.getRemainingTime()` inside prompt component
4. `getRemainingTime()` will first return time until prompt is visible `promptTimeout`) before returning idle timeout value.

### Expected behavior

`getRemainingTime()` should always return remaining time until `onIdle` callback is triggered.

### System Information (please complete the following information)

 - `OS`: MacOS Monterey 12.4
 - `Device`: Macbook
 - `Browser Vendor`: Google Chrome
 - `Browser Version`: 102.0.5005.61 (arm64)

**Comment by SupremeTechnopriest** [comment]
This was actually by design but I think we can implement it the way you described here without any adverse effects.  Ill be working on a new release this weekend.  Will keep you posted.

**Comment by SupremeTechnopriest** [comment]
This has been published as `5.3.0`.  Let me know if you have any issues!
