### ISSUE TITLE
Problems with getTotalActiveTime() and reset() on v5

### ISSUE THREAD

**Issue by d9k** [SupremeTechnopriest/react-idle-timer#257]
## Bug information

Reopening issue #195 

### Affected Module

- `Version`: `5.2.0`

### Describe the bug

Update: maybe it was my local webpack cache problem, see https://github.com/SupremeTechnopriest/react-idle-timer/issues/257#issuecomment-1146194770 for more recent issue.

I get negative (`< 0`) `getTotalActiveTime()` result after `reset()`.

_**I think that's because `lastIdle.current` value is not reset in `reset()` function.**_

Related code:

(at `src/useIdleTimer.tsx`):

```
const reset = useCallback<(remote?: boolean) => void>((remote?: boolean): void => {

// . . . . .

    // Reset state
    idle.current = false
    prompted.current = false
    paused.current = false
    remaining.current = 0
    promptTime.current = 0
    lastReset.current = now()

// . . . .

  const getTotalActiveTime = useCallback<() => number>((): number => {
    const total = Math.round(getTotalElapsedTime() - getTotalIdleTime())
    return total >= 0 ? total : 0
  }, [startTime, lastIdle, idleTime])

// . . . .

  const getTotalElapsedTime = useCallback<() => number>((): number => {
    return Math.round(now() - startTime.current)
  }, [startTime])

// . . . .

  const getTotalIdleTime = useCallback<() => number>((): number => {
    if (idle.current) {
      return Math.round((now() - lastIdle.current) + idleTime.current)
    }
    return Math.round(idleTime.current)
  }, [lastIdle, idleTime])
```

### To Reproduce

```
const timerProps = {
 debounce: 500,
 timeout: 2000,
}

const timer = useIdleTimer(timerProps);

// after some time active

timer.reset();

// then immediately after

timer.getTotalActiveTime(); // < 0  :(
```

### Expected behavior

```
timer.getTotalActiveTime(); 
```

result should never go below 0;

### System Information (please complete the following information)

 - `OS`: Ubuntu 18.04
 - `Device`: Desktop
 - `Browser Vendor`: Chrome
 - `Browser Version`: 100.0.4896.60

**Comment by d9k** [comment]
temporary fix in top-level code

before:

```
getTotalActiveTime = idleTimer.getTotalActiveTime;
const resetActiveTime = idleTimer.reset;
```

after:

```
const totalActiveTimeToSubtract = useRef(0);
getTotalActiveTime = useCallback(
    () => idleTimer.getTotalActiveTime() - totalActiveTimeToSubtract.current,
    [idleTimer]
);
const resetActiveTime = useCallback(() => {
    totalActiveTimeToSubtract.current += getTotalActiveTime();
}, [getTotalActiveTime]);
```

**Comment by SupremeTechnopriest** [comment]
I will look into this this weekend. Thanks for the report.

**Comment by d9k** [comment]
@SupremeTechnopriest, hello and thank you! Sorry for contradictory report.

**Comment by SupremeTechnopriest** [comment]
`totalActiveTime` will never return less than 0.  There's a conditional hard coded into the function.  See here: https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/src/useIdleTimer.tsx#L599

You said there was a webpack problem?  Does that mean this is a non issue?  As far as reset not working, that function is getting a small refactor.  You can test it again on the next release.

**Comment by SupremeTechnopriest** [comment]
Give `5.3.0` a try and get back to me.

**Comment by SupremeTechnopriest** [comment]
`5.4.0` has been released with a few new methods and bug fixes.  Im going to close this due to inactivity, but feel free to re open it if you are still having this issue on the latest version.
