### ISSUE TITLE
v1.5.1 is broken

### ISSUE THREAD

**Issue by sidoruk-sv** [SupremeTechnopriest/react-idle-timer#26]
Screenshot with problem (note logs timings in millisecond): http://take.ms/RPTyz
Sandboxed: https://codesandbox.io/s/z2xm14nzm

**Comment by SupremeTechnopriest** [comment]
Ill take a look at this issue today.  Thanks for the report.

**Comment by SupremeTechnopriest** [comment]
@sidoruk-sv Sorry about that.  Version `1.5.2` is latest on npm.  Please reopen if you still experience this issue.
