### ISSUE TITLE
5.3.0 not calling onActive as expected

### ISSUE THREAD

**Issue by kmarple1** [SupremeTechnopriest/react-idle-timer#263]
### Affected Module

- `Version`: 5.3.0

### Describe the bug

In version 5.2.0, the following test will fire the `onActive` function passed to `useIdleTimer`:

```js
it("should allow the user to stay logged in", () => {
        jestExpect(mockAxios.post).not.toHaveBeenCalled();

        wrapper.find("CustomButton").simulate("click");

        jestExpect(mockAxios.post).toHaveBeenCalled();
    });
```

`CustomButton` is the "Keep Me Logged In" button in the dialog opened by `onPrompt`.

However, in 5.3.0, `onActive` is no longer being triggered.

EDIT: This is possibly a result of `reset()` no longer calling `onActive()`? This issue then becomes that, even in the browser, it *never* seems to be called. I added a `console.log("active")` to it and it never fires. For now I've just rewritten things to not use `isActive`, but when *is* it supposed to fire?

### To Reproduce

See above. Add a `console.log()` statement to `onActive` to check if it's being called.

### Expected behavior

Click events should trigger `onActive`.

### System Information (please complete the following information)

 - Unit testing with Jest v28.1. `createMocks()` called in test setup.

**Comment by SupremeTechnopriest** [comment]
Yeah that is the issue.  I'm going to push a patch today where you can pass a boolean to `reset` to make it call `onActive`.  I think that would be the best of both worlds.  So in your case it would be `reset(true)`.  I will let you know when it is published.

**Comment by SupremeTechnopriest** [comment]
I think what I will do here is add another method `active()` that will allow you to manually activate the user.  It will behave like the old reset did.  It will reset the state and call `onActive` if the user is currently idle.  How does that sound?

**Comment by kmarple1** [comment]
It seems like I was misunderstanding how `onActive` was meant to be used and before 5.3.0 it just happened to work. Specifically, I thought the function was being called anytime the user did something that would reset the idle timer, but it appears that it's only supposed to be called when the user is already idle and triggers one of those events. With that in mind, I've rewritten my own code to just not use `onActive`. It might be good to clarify things in the documentation, but I don't know that you actually need to change anything.

**Comment by SupremeTechnopriest** [comment]
Ah, what you are describing is `onAction`.  That gets called any time a watched event is emitted.  You can throttle or debounce it with the `throttle` and `debounce` props.  The `onAction` event is still emitted when the prompt is active so that might be a good solution for you.  I have a new method called `activate()` that will reset the timer and also emit `onActive` if the user is idle (similar to how `reset()` used to work).  You will be able to use that on your prompt button.  Im hoping to have it released tonight.

**Comment by SupremeTechnopriest** [comment]
`5.4.0` is released and has the new `activate()` method.  That method should can be used in place of reset for your prompt confirm buttons. 

https://idletimer.dev/docs/getting-started/new#integrated-prompting
