### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED error while starting app

### ISSUE THREAD

**Issue by akash-pal** [SupremeTechnopriest/react-idle-timer#264]
## Question

Facing this issue while doing `npm run start` after installing `react-idle-timer`.

Node version being used is 12.22.7

`
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /project/node_modules/react-idle-timer/package.json`
`

**Comment by SupremeTechnopriest** [comment]
What are you using to bundle your app?

**Comment by akash-pal** [comment]
@SupremeTechnopriest am using webpack v4.
It was previously working fine with node v10.
After upgrading i have started facing this issue.

**Comment by SupremeTechnopriest** [comment]
Interesting... I will try to reproduce this and get back to you.

**Comment by SupremeTechnopriest** [comment]
Could you try removing your `node_modules` folder and your `package-lock.json` and reinstalling?  

`rm -rf node_modules package-lock.json && npm i`

If that doesn't work you might need to update your node to an LTS version.  Node 10 has been at end of life for a while now.  The lowest I would go is node 14, but if you can install at least node 16 that would be best.

https://nodejs.org/en/about/releases/

**Comment by akash-pal** [comment]
@SupremeTechnopriest i did try removing both node modules and package lock, still that didn't work.
For now am on node v12 with react-idle-timer 4.6.0 , which is working fine for me.
I will close this issue for now.
In future when I go to latest node lts then i would try with latest version of react-idle-timer.
