### ISSUE TITLE
The execution time of the onIdle function and the time set by the timeout are wrong

### ISSUE THREAD

**Issue by hezhisheng1930** [SupremeTechnopriest/react-idle-timer#267]
Hello, the interface has started timing, the timeout is set to 10 minutes, then the browser window is switched to another web page, and finally the browser window is reduced. During this process, the execution time of the onIdle function and the time set by the timeout There is an error, how can I solve it?

**Comment by SupremeTechnopriest** [comment]
Hello!

Could you please describe the error you are experiencing?

**Comment by SupremeTechnopriest** [comment]
Im not sure if you are seeing an actual error in the console, or if the behavior is unexpected.  It sounds like you might need to use worker timers to get around the browser throttling of timers.  You can see how to do that here: https://idletimer.dev/docs/getting-started/new#web-worker-timers

**Comment by SupremeTechnopriest** [comment]
Going to close this due to lack of activity.  Feel free to re open if you are still having issues.
