### ISSUE TITLE
Continuously runs

### ISSUE THREAD

**Issue by FugenApps** [SupremeTechnopriest/react-idle-timer#27]
Idk maybe i'm doing it wrong, but as far as i can tell when i implement this, and someone goes idle for X amount of time, it works, and than that function is called over 80x, and completely breaks my program

**Comment by SupremeTechnopriest** [comment]
Thanks for the heads up.  I found the issue and ill be pushing a fix shortly.

**Comment by SupremeTechnopriest** [comment]
@FugenApps Sorry about that.  I did made some changes under the covers and forgot to propagate them across a few functions.  Version `1.5.2` is latest on npm and that should solve all your issues.
