### ISSUE TITLE
Last Active Time

### ISSUE THREAD

**Issue by ChiWuSage** [SupremeTechnopriest/react-idle-timer#28]
It seems like the last active time is off.

<img width="552" alt="screen shot 2017-10-04 at 10 09 54 pm" src="https://user-images.githubusercontent.com/8961607/31211784-ccb98aca-a950-11e7-9dcd-c3e73233b407.png">

**Comment by SupremeTechnopriest** [comment]
Hi @ChiWuSage can you give me a bit more info?  What version are you running and what options are you instantiating with?  Thanks!

**Comment by ChiWuSage** [comment]
Hi @SupremeTechnopriest 
I'm running on version 1.5.2 and I'm basically using your simple code to test it out first. The idle timer is set for every 25 sec
When I call the following function right after going from idle to active, it should get the current time or close to the current time instead I'm getting the above in the image. 

`this.idleTimer.getLastActiveTime();`

Thanks!

**Comment by SupremeTechnopriest** [comment]
I took a look at this and it looks like you are passing a format to the constructor?  Your problem could be in the format string.  By default it should return you a timestamp `+new Date()`.  Could you update to the latest version `1.6.0` and run your test again with no formatting option?

**Comment by jimmyspiffy** [comment]
I've upgraded to 1.6.0 and I'm still seeing incorrect lastActiveTimes. :\ It's off by some 30 seconds or so.

**Comment by SupremeTechnopriest** [comment]
Okay, before I dig in I would like to verify that its not a formatting error.  Could you instantiate `IdleTimer` with no `format` option?  It should then return a timestamp on `getLastActiveTime()` then you can log it out and paste the results here.  Something like:

`console.log('last active: ', this.idleTimer.getLastActiveTime(), 'actual: ', +new Date(), 'diff: ', this.idleTimer.getLastActiveTime() - (+new Date()));`

If the results are skewed I will take a day to write a better test suite for this component.

**Comment by ChiWuSage** [comment]
So this is what I get from the log. Looks like it's off by 60sec

`last active:  1509421157931 actual:  1509421218316 diff:  -60386`

**Comment by SupremeTechnopriest** [comment]
Hi @ChiWuSage!  I just released version 4. It's a big rewrite and your issue should be solved, although I admit I was not able to root cause it.  The code is just much cleaner, more predictable and well tested now. There are a few breaking changes so make sure you checkout the README.  Reopen if you see anything else that looks off.
