### ISSUE TITLE
Before Unload cancel

### ISSUE THREAD

**Issue by Daneng66** [SupremeTechnopriest/react-idle-timer#285]
## Question

Could the idle timer potentially be affected by a cancelling of a browser beforeUnload notification, my implementations appears to stop working. (in Chrome)

**Comment by sadashivm** [comment]
Even I'm also facing a same issue. I have implemented before unload event.
Display message when user try to close a tab with the help of before unload event listerner.

After adding this event, the react idle timer always giving isLeader() true If I open another tab.
But If I disable this onBefore unload event code, then it is working as I expected. Like isLeader() method return false when open another tab.

I request to developer please provide a solution to handle unload event listerner as well isLeader() method shoud return false if user open another tab.

**Comment by SupremeTechnopriest** [comment]
Closing this in favor of #291 which has more detail.
