### ISSUE TITLE
Is it expected that onActive is not called if actions are fired during prompt window?

### ISSUE THREAD

**Issue by Slessi** [SupremeTechnopriest/react-idle-timer#286]
## Question

1. User action _before_ `onPrompt` => `onActive` is not called (expected)
1. User action _after_ `onIdle` => `onActive` is called (expected)
1. User action _after_ `onPrompt` but _before_ `onIdle` => `onActive` is not called (?)

Is scenario 3 expected?
I would've thought an action after `onPrompt` would trigger the `onActive` event and prevent the `onIdle` event from being called.

If this is expected, am I meant to call `activate` inside `onAction` to get the functionality I am describing?

sandbox (look at console): https://codesandbox.io/s/upbeat-banzai-1ibixc?file=/src/App.js

In below, `onActive` log was not triggered despite triggering an `onAction` after `onPrompt`.
`onActive` is only triggered after `onIdle`.

![image](https://user-images.githubusercontent.com/3223500/193466338-16eb0d31-59df-4143-9dbd-cde1aab90195.png)

**Comment by SupremeTechnopriest** [comment]
Yes that is expected. Once the prompt is fired you are in the prompt state. If you want activity to automatically close the prompt you can hook into the `onAction` event.

**Comment by Slessi** [comment]
@SupremeTechnopriest closing the prompt is easy, but it doesn't stop `onIdle` from firing.

E.g. If I want to show a warning prompt, then after prompt times out logout a user, am I expected to call `activate` in `onAction` ?

```ts
  const { activate } = useIdleTimer({
    onPrompt: () => showPrompt(),
    onIdle: () => logout(),
    onAction: () => {
      activate(); // Without this, the prompt will close, but onIdle is still called
      closePrompt();
    },
  });
```

**Comment by SupremeTechnopriest** [comment]
You can check for isPrompted inside onAction and call activate or reset.
