### ISSUE TITLE
⚡ PointerEvents types not supported in EventType.ts

### ISSUE THREAD

**Issue by drecali** [SupremeTechnopriest/react-idle-timer#287]
### Is your feature request related to a problem? Please describe.

I think [pointer event types](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent) are not supported as an `event` prop for `useIdleTimer` or `withIdleTimer`. It would be useful to support these types of events for better compatibility with other libraries that use them to handle events.

### Describe the solution you'd like.

The `PointerEvent`s below are not included in [`src/types/EventType.ts`](https://github.com/SupremeTechnopriest/react-idle-timer/blob/55cf8152b902cb75dfd25819fbb3ce76829a9e0d/src/types/EventsType.ts). I would like to include them if it doesn't have any negative effects. I don't use all these events but according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent), it seems like they're all valid and supported.

```
pointerover
pointerenter
pointerdown
pointermove
pointerup
pointercancel
pointerout
pointerleave
gotpointercapture
lostpointercapture
```

### Describe alternatives you've considered.

There is another way to add more events but it may not be easy for all users to implement. It would be easier if the library supported these types of events.

```diff
- import { useIdleTimer } from 'react-idle-timer';
+ import { EVENTS, useIdleTimer } from 'react-idle-timer';

+ const timerEvents = [
+  'pointerup',
+  'pointermove'
+ ] as const;

  const { pause, resume, reset } = useIdleTimer({
    element: document,
    timeout: 2000,
-  events: ['pointerup', 'pointermove'],
+  events: timerEvents as unknown as EVENTS[],
  });
```

### Additional context.
Please let me know if I can start on this issue or if I missed anything. Thanks again for maintaining such a useful library!

**Comment by SupremeTechnopriest** [comment]
I will add these to the type in the next version!

**Comment by drecali** [comment]
Thanks @SupremeTechnopriest! Can I add them in a PR soon so it can qualify for Hacktoberfest?

**Comment by SupremeTechnopriest** [comment]
@drecali Absolutely!

**Comment by SupremeTechnopriest** [comment]
On it.

**Comment by SupremeTechnopriest** [comment]
@drecali Merged!  Thanks for your contribution!

**Comment by SupremeTechnopriest** [comment]
I will publish to npm along with the next release.

**Comment by drecali** [comment]
Thanks so much! Once again, this library is awesome! The docs/demo website is great too! Thanks for creating and maintaining it! When the process to support OSS at our company is implemented, I will nominate this repo 🙂

**Comment by SupremeTechnopriest** [comment]
That would be much appreciated! Glad you find it helpful!
