### ISSUE TITLE
beforeunload is not working with this plugin

### ISSUE THREAD

**Issue by sadashivm** [SupremeTechnopriest/react-idle-timer#291]
## Question

Ask your question here!
First of all want to say @SupremeTechnopriest for this grreat npm package. It is really awesome.

![image](https://user-images.githubusercontent.com/10355473/196926636-6f40fc22-6d78-4c11-9d7d-8666adeb536e.png)

isLeader() method is returning false value if I open another tab.
And If I disable above code then it is working fine.

I request you could you please beforeUnload event as well?

**Comment by SupremeTechnopriest** [comment]
If someone can make a code sandbox that recreates this issue I can look into it.  My gut is telling me that before unload kills all the running timers, so if you cancel it you might need to start it back up again.

**Comment by Daneng66** [comment]
Issue is I am pretty sure there isn't any browser support for understanding if the user cancelled the before unload notification (I have seen some work arounds done with timers but it feels pretty hacky). Could the timers not get destroyed on the onUnload event?

**Comment by SupremeTechnopriest** [comment]
I don't think this is in our control from JS.  Javascript is single threaded, so any alert will suspend everything else.  We could maybe open a feature request with tc39 and maybe we can get an event for `onbeforeunloadcancelled`.  Then I could handle the scenario within the IdleTimer library.  I think for now you are going to have to do something like:

```js
const stillHereHandler = () => {
  idleTimer.reset()
  document.removeEventListener('mousemove', stillHereHandler)
}

const beforeUnloadListener = evt => {
  evt.preventDefault()
  document.addEventListener('mousemove', stillHereHandler)
  evt.returnValue = 'Are you sure you want to exit?'
  return evt.returnValue
}
```

**Comment by SupremeTechnopriest** [comment]
Going to close this, feel free to re open if there is any other activity on this.

**Comment by sadashivm** [comment]
Hello @SupremeTechnopriest , after adding the above code. **`isLeader()`**  always return true value, if I open multiple tabs.
I expected isLeader() returns false in other tabs.
