### ISSUE TITLE
change isIdle=false as default value

### ISSUE THREAD

**Issue by sivakannan** [SupremeTechnopriest/react-idle-timer#304]
https://github.com/SupremeTechnopriest/react-idle-timer/blob/d343d4d189dffe46c86dcc07b863da19cc98409a/src/useIdleTimer.tsx#L59

I am creating react-idle-timer as utility, my utility will return isIdle. Based on that we are showing popup in frontend. However we are receiving isIdle=true and after some point of time when timer started, we are receiving isIdle=false.

we need isIdle=false as default value. kindly suggest.

**Comment by SupremeTechnopriest** [comment]
If you call `start` when the hook mounts the `isIdle` state will toggle to `false`.  I will consider changing the default to false in the next release.

**Comment by sivakannan** [comment]
> If you call `start` when the hook mounts the `isIdle` state will toggle to `false`. I will consider changing the default to false in the next release.

thanks for your quick response. do you have any suggestion to fix(isIdle = false) in meanwhile ?

**Comment by SupremeTechnopriest** [comment]
Idle will default to `false` with version `5.5.0`. Should have it published this week!

**Comment by sivakannan** [comment]
When are we planning for the release? just to plan. @SupremeTechnopriest

**Comment by SupremeTechnopriest** [comment]
I'm just getting over being sick. It kind of put a damper on my plans. I'm gonna work on the release this week and hopefully have it out next by the end of the week.

**Comment by sivakannan** [comment]
@SupremeTechnopriest thanks. Hope you feel better now.
