### ISSUE TITLE
this becomes 'undefined' when wrapped with the library

### ISSUE THREAD

**Issue by ved-north27** [SupremeTechnopriest/react-idle-timer#309]
### Affected Module

- `5.4.2`

### Describe the bug

When using the library by wrapping it to the component `this` becomes undefined, the moment I remove the library it works fine.

### To Reproduce

1. Write console.log(this) in componentDidMount()
2. Wrap the component when you export like withIdleTimer(App)
3. Test, the value of this becomes undefined
4. Remove withIdleTimer in step 2. this becomes available

### Expected behavior

It shouldn't make **this** undefined

### Screenshots

Screenshot 1 showing debug information with the library
![Screenshot 1](https://user-images.githubusercontent.com/109797569/206714028-fe47f428-1772-4eaf-b5bf-92cc97abdf54.png)

Screenshot 2 showing debug information without the library
<img width="767" alt="Screenshot 2" src="https://user-images.githubusercontent.com/109797569/206714104-82c6138c-2758-4925-b927-4b1969f7a733.png">

**Comment by SupremeTechnopriest** [comment]
Thanks for the report @ved-north27.  This is confirmed and patched.  Will be released with the 5.5.0 patch later this week.  If you want to test it out I pushed a release candidate that can be installed with `npm i react-idle-timer@next`.
