### ISSUE TITLE
onPrompt getting triggered everytime on reset

### ISSUE THREAD

**Issue by jitujazz** [SupremeTechnopriest/react-idle-timer#310]
## Bug information
I am working with `useIdleTimer` and whenever I use the `startManually: true` and try to reset the timer, the `onPrompt` function gets called again

### Affected Module

- `Version`: 5.4.2

### Describe the bug

Below is the code I am using

```js
const IdleTimeout = () => {
	const [timeoutOpen, setTimeoutOpen] = useState(false);
	const [uiTimeout, setUiTimeout] = useState(0);

	const onIdle = () => {
    console.log('Idle')
    handleTimeoutLogout();
  }

  const onPrompt = () => {
    console.log('prompt')
    handleTimeoutClose();
    setTimeoutOpen(true);
  }

	const onActive = () => {
		console.log('active')
	}

  const { reset, start, pause } = useIdleTimer({
		onIdle,
		onPrompt,
		onActive,
		promptTimeout: 1000*10,
		timeout: uiTimeout,
		startManually: true,
		startOnMount: false
	});

	useEffect(() => {
		console.log('loading component')
		setTimeout(() => {
			console.log('setting timeout')
			setUiTimeout(1000 * 10)
		}, 10000)
	}, []);

	useEffect(() => {
		if(uiTimeout){
			console.log('starting timer')
			start()
		}
		else {
			console.log('pausing timer')
			pause()
		}
	}, [start, pause, uiTimeout])

  const handleTimeoutClose = () => {
    console.log('Staying on for now!')
    reset();
    setTimeoutOpen(false);
  }

  const handleTimeoutLogout = () => {
    console.log('Logout!')
    setTimeoutOpen(false);
  }
  };
}
```
The `start` and `pause` works perfectly fine. But, when the timeout of 10 secs is done, I get a prompt, as expected. `onPrompt` I am trying to `reset` the timer and moving the mouse even a bit triggers the `onPrompt` function again and the loop continues.

Am I doing any wrong here?

### System Information (please complete the following information)

 - `OS`: Windows 11
 - `Device`: Desktop
 - `Browser Vendor`: chrome
 - `Browser Version`: 108

**Comment by jitujazz** [comment]
Bumping this up

**Comment by jitujazz** [comment]
Bumping it up again

**Comment by SupremeTechnopriest** [comment]
Can you pop your use case into a code sandbox for me? I don't think this is a problem with idle timer (theres a lot of tests around this behavior) but I will be able to help you solve it if I can see how you are integrating this IdleTimeout component in your app.

**Comment by deshiknaves** [comment]
This is definitely an issue. `promptTimeout` works as expected. If you have a continue button and call `reset`, the timers get reset.

When using `promptBeforeIdle` after clicking the continue button which calls `activate` and/or `reset` the prompt opens back up immediately. I'd love to open a codesandbox, but `jest.useFakeTimers` doesn't work in Codesandbox. Here is a link with the code there so you can run it https://codesandbox.io/s/idle-timer-0sdn6k?file=/src/App.tsx.

**Comment by SupremeTechnopriest** [comment]
Thanks for the sandbox. I will take a look at this after work today.
