### ISSUE TITLE
Documentation of useIdleTimer

### ISSUE THREAD

**Issue by anavalo** [SupremeTechnopriest/react-idle-timer#313]
### Affected Module

- `Version`: Put the module version number here (0.0.1)

### To Reproduce

1. Go to 'useIdleTImer'
2. Scroll down to the bottom of the page
3. Click on 'Features'
4. See error.

### Expected behavior

I expected to be navigated to `Features` page.

### System Information (please complete the following information)

 - `OS`: MacOs 13.0.1
 - `Device`: Desktop
 - `Browser Vendor`: Chrome
 - `Browser Version`: 106

**Comment by SupremeTechnopriest** [comment]
This has been resolved.  Thanks!
