### ISSUE TITLE
`isLeader` and `getTabId` runtime error with `crossTab: true`

### ISSUE THREAD

**Issue by tgelu** [SupremeTechnopriest/react-idle-timer#317]
## Bug information

I'm trying to call `isLeader` and `getTabId` on the first render. This results in the below runtime exception:

```
Uncaught Error: ❌ Cross Tab feature is not enabled. To enable it set the "crossTab" property to true.
```

### Affected Module

- `Version`: `5.4.2`

### Describe the bug

Seems like the tab manager is instantiated in an effect. This means those functions (like `isLeader` or `getTabId`) that have the following check won't be callable except at certain times:

```
    if (!manager.current) {
      throw new Error('❌ Cross Tab feature is not enabled. To enable it set the "crossTab" property to true.')
    }
```

Either the error message is deceiving or the behavior is unexpected.

### To Reproduce

4. See error.

### Expected behavior

Etiher:
1) the error message should reflect reality since one can get the exception even with `crossTab: true`.
2) or the functions in question should reflect the "not initialized state" in their return value instead of throwing. Throwing should happen only if `crossTab` is really set to `false`.
3) or [this initialization](https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/src/useIdleTimer.tsx#L664-L684) should not happen in an effect, if that's feasible.

Either way this should probably be documented.

### Screenshots

N/A

### System Information (please complete the following information)

 - `OS`: irrelevant
 - `Device`: irrelevant
 - `Browser Vendor`: irrelevant
 - `Browser Version`: irrelevant

### Additional context

-

**Comment by SupremeTechnopriest** [comment]
Are you setting the `crossTab` property to true?

**Comment by tgelu** [comment]
I will get back once I try that :) thanks.

**Comment by SupremeTechnopriest** [comment]
Any luck?

**Comment by tgelu** [comment]
this seems to work in `@next`. Thanks! 👍
