### ISSUE TITLE
I find it difficult to understand the way the "idle" state and "prompted" interact

### ISSUE THREAD

**Issue by tgelu** [SupremeTechnopriest/react-idle-timer#318]
### What would be the implications if the "prompted" state would overlap the "active" state?

Imagine that instead of `promptTimeout` you would have an option `promptBeforeIdle: number` (name is not too important) which would instead trigger the prompted state X number of ms before becoming idle.

This has a few advantages:
- The prompt feature would be just a way to get notified through a callback about when there are X seconds left until becoming idle.
- It is simpler to think about the possible states a user can be in: active -> active and prompted -> idle. In the current scheme it took me a little while to understand that my prompt is pushing my `timeout` basically.
- Simpler to achieve the most common use case: I want to react to an idle user after X amount of time and prompt him Y seconds before that happens. Today that's awkward: you have to set the  `promptTimeout: promptBeforeXSeconds` and `timeout` to `myActualDesiredTimeout - promptBeforeXSeconds`.

**Comment by SupremeTechnopriest** [comment]
In the current implementation, both prompted and idle should both be considered "Idle" states.  The suggested `promptBeforeIdle` is just a bit of inversion of logic.  I could add this as an additional configuration option, but it would be a breaking change to replace `promptTimeout`.

These two configurations would be equivalent:

```
timeout: 2000 // Time until prompt is fired
promptTimeout: 1000 // Time prompt is displayed before idle
```

```
timeout: 3000 // Time until idle
promptBeforeIdle: 1000 // Prompt 1000ms before idle
```

Its really just semantics.  the underlying implementation wouldn't change.  I would just convert it on initialization:

`promptTimeout = promptBeforeIdle > 0 ? timeout - promptBeforeIdle : promptTimeout`

You suggestion is a bit easier to reason about. I will consider deprecating `promptTimeout` in favor of `promptBeforeIdle` but in the mean time I will allow for both configurations.

**Comment by SupremeTechnopriest** [comment]
Done! `promptBeforeIdle` does what you asked here.  I agree with you that this is less confusing, so I've deprecated `promptTimeout`.  Thanks for the good suggestion!  If you wouldn't mind testing it out for me, the latest release candidate (7) has this feature `npm i react-idle-timer@5.5.0-rc.7`.
