### ISSUE TITLE
`onActive()` called on user event before idle state was reached (w/ `crossTab` & `syncTimers`)

### ISSUE THREAD

**Issue by tgelu** [SupremeTechnopriest/react-idle-timer#320]
## Bug information

The [documentation](https://idletimer.dev/docs/api/props#onactive) says that `onActive` is the "function to call when user becomes active." Which I understand to mean that the user was idle and became active (otherwise there wouldn't be any distinction between `onActive` and `onAction`). But when I tested the simplest use case, `onActive` gets called on any event, even before reaching any idle state.

#### This seems to be happening when both `crossTab: true` and `syncTimers: true`.

This is probably related to #319 

### Affected Module

- `Version`: `5.4.2`

### Describe the bug

I think the below test describes it best:

```js
        it('Should not call onActive if the state wasn\'t previously idle', async () => {
          props.element = window
          props.timeout = 200
          props.onActive = jest.fn()
          idleTimer()
          fireEvent.mouseDown(props.element)
          expect(props.onActive).not.toHaveBeenCalled() // failing, it gets called once
        })
```

[This](https://github.com/SupremeTechnopriest/react-idle-timer/blob/fdb3bd9546103841c1cc56585e0792138de6f2c2/src/TabManager/index.ts#L136-L144) seems to be the culprit. If there is any active tab, an event will trigger `onActive` on all tabs.

### To Reproduce

Run the above test.

### Expected behavior

`onActive` should only be called on the state changed from idle to active.

### Screenshots

N/A

### System Information (please complete the following information)

Irrelevant

### Additional context

N/A

**Comment by SupremeTechnopriest** [comment]
Confirmed to be a bug with sync timers.  Looking into it.

**Comment by SupremeTechnopriest** [comment]
Fixed!  It will be released with `5.5.0`, but you can test it now by installing the latest release candidate (6) with `npm i react-idle-timer@next`.

**Comment by tgelu** [comment]
Maybe I'm testing it wrong but one of my tests fail with `5.5.0`. I can reproduce it by adding the following test to `react-idle-timer`:

```ts
        it('Should call `onActive' when calling "activate()" from "prompted" state', async () => {
          props.element = document
          props.timeout = 200
          props.promptTimeout = 100
          props.onActive = jest.fn()

          const { result } = idleTimer()
          await waitFor(() => result.current.isPrompted())

          result.current.activate()
          expect(props.onActive).toHaveBeenCalledTimes(1) // fails
        })

```

**Comment by SupremeTechnopriest** [comment]
Yeah this was an oversight on my part. I pushed a new release candidate that resolves it temporarily.  Im am rethinking activate calling onActive from the prompt state.  Need to model all the implications.
