### ISSUE TITLE
User interaction

### ISSUE THREAD

**Issue by Andriy-Lyashenko** [SupremeTechnopriest/react-idle-timer#324]
## Question

Is it possible to to clear events after first user interaction? For instance user interaction callback `onActive` is executed only once and will be disabled further. I actually need to detect very first action of user and that should be it.
Thanks

**Comment by SupremeTechnopriest** [comment]
Yeah this is possible.

```js
const { pause } = useIdleTimer({
  onAction: () => {
    // Do first action stuff
    pause() // pause the timer preventing it from continuing
  }
})
```

Though if you just need to detect the first action and nothing more, I would suggest implementing it yourself as idle timer is going to be a bit heavier than you need.

```js
// The events you want to track
const events = [
  'mousemove',
  'mousedown',
  'mousewheel',
  'keydown'
]

// The event handler
const handler = () => {
  // Do what ever you need to do
  // Then unbind the events
  for (const event of events) {
    window.removeEventListener(event, handler)
  }
}

useEffect(() => {
  for (const event of events) {
    window.addEventListener(event, handler)
  }

  return () => {
    for (const event of events) {
      window.removeEventListener(event, handler)
    }
  }
})
```

This is far less code being included in your project.  Let me know if this helps.

**Comment by Andriy-Lyashenko** [comment]
Yeah, that's actually what I need! As for custom approach.. it would help if I knew for sure that req's will still the same therefore I would stick on `react-idle-timer` because of various methods under the hood.
Thanks for an input
