### ISSUE TITLE
Did you mean to release version `5.3.3` when the latests was `5.5.2`?

### ISSUE THREAD

**Issue by garyb01** [SupremeTechnopriest/react-idle-timer#331]
## Question

Did you mean to release version `5.3.3` when the latests was `5.5.2`?

https://github.com/SupremeTechnopriest/react-idle-timer/releases

```
npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-idle-timer@5.3.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

Npm install `5.5.3` works :)

**Comment by SupremeTechnopriest** [comment]
AH good catch.  That is a type-o.  Will fix.  Did 5.5.3 fix the sleep issue?

**Comment by SupremeTechnopriest** [comment]
Update the release.  Thanks!

**Comment by garyb01** [comment]
`5.5.3` seems to have fixed the issue.. thanks for all the hard work!! :D

**Comment by SupremeTechnopriest** [comment]
Awesome!
