### ISSUE TITLE
Idle timer not catching event inside (or over the top) of and Object SVG

### ISSUE THREAD

**Issue by DannyMurphy** [SupremeTechnopriest/react-idle-timer#332]
```
<object type="image/svg+xml" data="./assets/504.svg" id="svg">
          Please reload the page
</object>
```

When interacting with an SVG in an Object container I get captures of Mousemoves or clicks. Is this as intended if so what is the best way to manually trigger a timer reset?

Thank you,
Danny

**Comment by SupremeTechnopriest** [comment]
https://idletimer.dev/docs/api/methods#reset
or
https://idletimer.dev/docs/api/methods#activate

You can try to set `pointer-events: none` on the object.

**Comment by DannyMurphy** [comment]
Thanks, that got the manual reset() working. 

With the pointer because I still needed to capture the click events I added the pointer-events:none to the hover state and that works like a treat thank you. 

```
object:hover {
  pointer-events: none;
}
```
