### ISSUE TITLE
How to track user idle state inside the specific container?

### ISSUE THREAD

**Issue by AkromDev** [SupremeTechnopriest/react-idle-timer#336]
## Question

I want to track if user is active or idle inside the specific container. 
For example, I want to track user idle state in pink box only. Other components and document should be ignored.
I tried passing `ref` to `element` prop but it did not work. 
Unfortunately, I could not find examples in [doc site](https://idletimer.dev/docs/getting-started/installation) that tracks specific container. (all tracking `document`)

```js
const containerRef = useRef();

useIdleTimer({
   ...
   element: containerRef,
})

... 

return (
  <div ref={containerRef}>
     ....
  </div>
)

```
<img width="476" alt="Screen Shot 2023-03-16 at 08 52 43" src="https://user-images.githubusercontent.com/41626115/225510032-62741694-66e7-4fc7-9c3f-8d5034efa9c2.png">

Sandbox: https://codesandbox.io/s/idle-timer-hook-example-cdnozm

**Comment by SupremeTechnopriest** [comment]
Someone else recently asked this in the discord.  I will add something to the docs for this on the next update.

The reason why this isn't working is that your ref is initially null and when a refs current value changes a rerender is not triggered.  You will need to use a piece of state to trigger a rerender in order for IdleTimer to receive the new `element` value.

```js
const [element, setElement] = useState(document)
const ref = useRef(null)

const { start } = useIdleTimer({
  element,
  startManually: true,
  ...otherProps
})

useEffect(() => {
  if (ref.current) {
    setElement(ref.current)
    start()
  }
}, [ref])
```

Use an effect hook to detect when your ref gets set and then utilize that event to set your state.  Setting the state will cause a rerender and the Idle Timer hook will get the new element.  You can also use the `startManually` option to make sure it does not try to start until you have a valid element set.  I think this is the best way to implement `element` with a ref.  

The other option is to use a [Portal](https://reactjs.org/docs/portals.html).  That way your element is defined in html and will be present when your javascript is run.  Then you can just use `document.getElementById`.

**Comment by SupremeTechnopriest** [comment]
Here is your sandbox with it working.

https://codesandbox.io/s/idle-timer-hook-example-forked-bvz84m

**Comment by AkromDev** [comment]
Hi @SupremeTechnopriest 
Sorry for late reply and thanks for the solution.

Unfortunately, the code sandbox you shared is not working as expected.
In that code sandbox, activity tracking is completely broken and `onActive` is not getting triggered at all.
But If comment `element` prop and comment it out again, it works after saving code sandbox, which is very weird.
