### ISSUE TITLE
[Feature Request] Expose values of IIdleTimerProps as parameters of all the callbacks in IIdleTimer

### ISSUE THREAD

**Issue by kylemh** [SupremeTechnopriest/react-idle-timer#339]
### Is your feature request related to a problem? Please describe.

I wanted to do a customized prompt dialog in an app that has a separate hook for displaying dialogs. I basically didn't have the ability to pass necessary props to the dialog with our API because both function calls were at the same level of scope.

The API for the `useModal` hook was basically like this (excluding generics for brevity-sake):
```ts
type showFn = (props: SpecificModalsPropsDerivedByGenerics) => void;
type hideFn = () => void;
type useModal = (Modal: FunctionComponent) => [showFn, hideFn];
```
My modal wanted to render the time remaining and be able to activate and reset the timer, but that was impossible:

```ts
const [showInactivityWarningModal, hideInactivityWarningModal] = useModal(InactivityModal);

const { getRemainingTime, isPrompted, activate, reset } = useIdleTimer({
  timeout: ONE_HOUR,
  promptBeforeIdle: ONE_MINUTE * 5,
  onPrompt: () => showInactivityWarningModal({ /* i want to pass props here, but can't */ }),
});
```

### Describe the solution you'd like.

I thought it'd be way cooler if the callback members of the `IIdleTimer` type were passed as arguments to all the callbacks of `IIdleTimerProps`. Then I could've done...

```ts
const [showInactivityWarningModal, hideInactivityWarningModal] = useModal(InactivityModal);

useIdleTimer({
  timeout: ONE_HOUR,
  promptBeforeIdle: ONE_MINUTE * 5,
  onPrompt: ({ getRemainingTime, reset }) => showInactivityWarningModal({ getRemainingTime, resetInactivityTimer: reset }),
});
```

### Describe alternatives you've considered.

A workaround exists! I could (and will) call the `showFn` as a side effect within a `useEffect` based on the props from `useIdleTimer`

**Comment by SupremeTechnopriest** [comment]
@kylemh Thats a real good idea! I will add this in the next release. Also thank you for the donation! I am in the middle of a move, but I will work on adding this for you next week. Another work around in the mean time would be the context provider. 

https://idletimer.dev/docs/api/idle-timer-provider

**Comment by kylemh** [comment]
No rush at all. Absolutely loved stumbling upon your library. A very pristine, open source gem. I wish I could donate more!

**Comment by SupremeTechnopriest** [comment]
Feature has been release with version `5.6.0`.  The `IIdleTimer` interface is exposed as the second parameter of all callback functions!  This was a good suggestion.  Thanks again!

**Comment by SupremeTechnopriest** [comment]
Also @kylemh if you end up joining the discord, DM me and I will give you the sponsor role.  Thanks again for that and let me know if this new feature works out for you!
