### ISSUE TITLE
Legacy Bundle

### ISSUE THREAD

**Issue by AGontcharov** [SupremeTechnopriest/react-idle-timer#345]
## Question

Is there a legacy bundle for react-idle-timer to support older browsers? I was under impression from the v4 docs that v5 would contain a modern bundle (default) and a legacy bundle. Looking at the code that doesn't seem to be the case.

Thanks!

**Comment by SupremeTechnopriest** [comment]
Yeah I definitely overlooked that.  I will add a legacy bundle on the next release.

**Comment by SupremeTechnopriest** [comment]
Hey @AGontcharov!

The legacy bundle is released in version `5.7.2`!  Here are the relevant docs:

https://idletimer.dev/docs/getting-started/installation#legacy-browser-support

Let me know if there are any issues!
