### ISSUE TITLE
I want to start the timer when my user logs in ,so i have a condition and if condition satisfies then the timer should start from idleTimer .

### ISSUE THREAD

**Issue by Mursalin7** [SupremeTechnopriest/react-idle-timer#347]
I want to start the timer when my user logs in ,so i have a condition and if condition satisfies then the timer should start from idleTimer .Please help

**Comment by SupremeTechnopriest** [comment]
The `startManually` prop and `start` method will do what you want.

https://idletimer.dev/docs/api/props#startmanually
https://idletimer.dev/docs/api/methods#start
