### ISSUE TITLE
Add `disabled` prop to `useIdleTimer()`

### ISSUE THREAD

**Issue by dkreft-termly** [SupremeTechnopriest/react-idle-timer#349]
### Is your feature request related to a problem? Please describe.

I have a need to set an idle timer on a conditional basis (based upon the type of user who's logged in), so it seemed like all I'd need to do is this:

```js
  const startOnMount = false

  useIdleTimer({
    onIdle() {
      setTimedOut(true)
    },
    startOnMount,
    timeout: IDLE_TIMEOUT,
  })
```

While this prevents the timer from starting on mount, it does not prevent the timer from starting based upon other events (e.g., mousemove).

### Describe the solution you'd like.

I'd like a very clear `enabled` prop (defaults to `true` for backwards compatibility):

```js
useIdleTimer({
  disabled: false,   // defaults to true
})
```

### Describe alternatives you've considered.

I could set the timeout to `Infinity`, but that implies that the timer is still running...it just takes forever to trigger. This feels very side-effecty.

I could also conditionally modify the `events` prop, but that also seems side-effecty--it doesn't turn anything off, it just kinda neuters the timer.

**Comment by SupremeTechnopriest** [comment]
Hey @dkreft-termly,

This is already possible via the `startManually` property.  You can default that to `true` and then call `start` when you want to kick things off.

Heres a simple example:

```ts
const { start } = useIdleTimer({ startManually: true })

useEffect(() => {
  fetch('https://foo.com/login').then(res => {
    if (res.ok) start()
  })
}, [])
```

Here are the relevant docs:
https://idletimer.dev/docs/api/props#startmanually
https://idletimer.dev/docs/api/methods#start

Re-open this issue if this is not sufficient.

**Comment by dkreft-termly** [comment]
With the approach you're suggesting, I'd have to add yet another `useEffect()` which feels really clunky:

```js
const user = useCurrentUser()

const { start } = useIdleTimer()

useEffect(() => {
  if ( !user.canBeTrustedWithLongSessions ) {
   start()
  }
}, [start, user])
```

Whereas if we had a simple flag, I could do this very simply:

```js
const user = useCurrentUser()

useIdleTimer({
  disabled: user.canBeTrustedWithLongSessions,
})
```

**Comment by dkreft-termly** [comment]
BTW, @SupremeTechnopriest , I don't see an affordance for re-opening this issue:

![image](https://github.com/SupremeTechnopriest/react-idle-timer/assets/71285654/3c596c11-d088-4a99-86c9-afb08656fa62)

**Comment by SupremeTechnopriest** [comment]
The use effect is going to have to go some where.  If I were to to

**Comment by SupremeTechnopriest** [comment]
So the `useEffect` is going to have to go somewhere.  IdleTimer doesn't actually use state because it needs to be impervious to re-renders.  I could add support for a `disabled` property, but its going to be a useEffect under the covers.  What behavior would you expect when you toggle this `disabled` property?  A `pause` and `resume` implementation  or a `stop` and `start` implementation?

**Comment by dkreft-termly** [comment]
I'm not opposed to `useEffect()` in principle, it's just that it feels like an inelegant solution for clients of `react-idle-timer`.

I'm thinking that `stop`/`start` might make more sense since if it starts disabled and then is enabled, there's nothing to `resume`...it's just a clue to get out of the way and let the timer start in the way that makes sense based upon the values supplied to the hook. Conversely, if it starts as enabled and then transitions to disabled, I would expect it to be basically a "kill switch"--just a dead stop.

**Comment by SupremeTechnopriest** [comment]
Okay I can do that.  You caught me just in time, I was just preparing a new release.  I will add this feature.  Shouldn't be too hard.  Stand by.

**Comment by dkreft-termly** [comment]
Thanks!

**Comment by SupremeTechnopriest** [comment]
Alright, this is good to go. 5.7.2 is the latest. Here are the relevant docs:

https://idletimer.dev/docs/getting-started/new#additions-in-v570
https://idletimer.dev/docs/api/props#disabled

Also added it to the demo on the docs site.  Let me know if you have any issues!

**Comment by SupremeTechnopriest** [comment]
Thanks for the suggestion! It would have been quicker but making changes to this project has gotten pretty involved. Source, tests, docs, demos, change logs, releases, etc... 

This is why I have switched from closing issues as they come up to collecting them and doing larger releases. Anyway, enjoy and let me know if there are any issues. (There shouldn't be. It's pretty well tested).
