### ISSUE TITLE
dist folder index.ems.js has module parse error with babel loader

### ISSUE THREAD

**Issue by SmudgeLord200** [SupremeTechnopriest/react-idle-timer#350]
### What happened?

Hi, it is my first time creating an issue on github, I recently cloned and built a new project on top of one of the old base react templates I found from the web. I was able to start the development server but bumped into an error saying there is a module parse error with babel loader. After spending some time debugging, I think it is about ES5+- conversion thing. I tried follow the solution of the other similar issues here but still no luck. I am new to programming so sorry if I ask some stupid things or don't have deep knowledge on some topics. 

### Reproduction Steps

```bash
1. Cloned the frontend and backend folder from github repo
2. Frontend is written in React and Backend is written in Python
3. Wrote corresponding dockerfile and docker-compose file
4. Able to run docker-compose up to start server
5. Bumped into this error
...
```

### Relevant log output

```bash
frontend-1  | Starting the development server...
frontend-1  |
frontend-1  | Failed to compile.
frontend-1  |
frontend-1  | ../node_modules/react-idle-timer/dist/index.esm.js 240:8
frontend-1  | Module parse failed: Unexpected token (240:8)
frontend-1  | File was processed with these loaders:
frontend-1  |  * ../node_modules/babel-loader/lib/index.js
frontend-1  | You may need an additional loader to handle the result of these loaders.
frontend-1  | | var Q = {},
frontend-1  | |   Ae = class {
frontend-1  | >     name;
frontend-1  | |     closed = !1;
frontend-1  | |     mc = new MessageChannel();
```

### Screenshots or Additional Context

the package.json is:
`  "dependencies": {... "react-idle-timer": "^5.2.0", ...},`
`"devDependencies": {
     "@babel/core": "^7.22.5",
    "@babel/plugin-proposal-class-properties": "^7.18.6",
    "@babel/preset-env": "^7.22.5",
    "@babel/preset-react": "^7.22.5",
}`

### Module Version

6.2.0

### What browsers are you seeing the problem on? Select all that apply.

Chrome

### What devices are you seeing the problem on?

Desktop

### Verification

- [X] I have checked for existing closed issues and discussions.

**Comment by SupremeTechnopriest** [comment]
Hey there!  If you are having issues with bundling es6 code you can try the new legacy build.  Details are here:

https://idletimer.dev/docs/getting-started/installation#legacy-browser-support

If you are using a modern node you can just change:

```ts
import { useIdleTImer } from 'react-idle-timer'
``` 
to:

```ts
import { useIdleTImer } from 'react-idle-timer/legacy'
``` 

Please reopen this issue if you are still having problems.

**Comment by SmudgeLord200** [comment]
Hi, I updated to the latest version 5.7.2 and tried your suggestion. But it gave me another error of `Module not found: Can't resolve 'react-idle-timer/legacy' in myTimer.js`. When I removed the `/legacy`, it gave me the same old error. And I don't think I can reopen the issue as I don't have the rights. Thanks.

**Comment by SmudgeLord200** [comment]
Huge thanks. It worked.

**Comment by SupremeTechnopriest** [comment]
Glad to help!

**Comment by SVenkat99** [comment]
@SupremeTechnopriest  - I have tried implementing this in React with Typescript project, and getting below error. Could not find a declaration file for module 'react-idle-timer/dist/index.legacy.esm.js'.
