### ISSUE TITLE
Date formatting

### ISSUE THREAD

**Issue by tgandrews** [SupremeTechnopriest/react-idle-timer#36]
Currently this imports date-fns library even if it is never used. As the formatter can be provided could this removed so that it doesnt add to bundles when never used. I appreciate this is a breaking change but the workaround is very small and makes the dependency more explicit.

**Comment by SupremeTechnopriest** [comment]
I could make it so you supply your own format function, or just get the date back raw.  Thats not a bad idea.

**Comment by tgandrews** [comment]
Do you want me to open a PR?

**Comment by SupremeTechnopriest** [comment]
If you don't mind. I'm exceptionally busy the next few weeks. Appreciate
it!
