### ISSUE TITLE
🐞 react-idle-timer node modules issue

### ISSUE THREAD

**Issue by ravikumar-roundsqr** [SupremeTechnopriest/react-idle-timer#368]
### What happened?

Recently I have updated react-idle-timer to latest version. After that It throwing error like as below

./node_modules/react-idle-timer/dist/index.esm.js 265:6
Module parse failed: Unexpected token (265:6)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| var Q = {},
|     Ae = class {
>   name;
|   closed = !1;
|   mc = new MessageChannel();

Can some one let me know what is causing the issue. steps to resolve the issue. Thanks in advance.

"react-idle-timer": "^5.7.2",

### Reproduction Steps

```bash
1.
2.
3.
...
```

### Module Version

5.7.2

### Verification

- [X] I have checked for existing closed issues and discussions.

**Comment by SupremeTechnopriest** [comment]
What is your react-scripts version?

**Comment by ravikumar-roundsqr** [comment]
"react-scripts": "3.4.0",

**Comment by SupremeTechnopriest** [comment]
Yeah thats a fairly old version.  I uses a version of webpack that does not support the package.json `exports` field. Can you you try directly importing the bundled file?  The options are:

`esm`: `import { useIdleTimer } from 'react-idle-timer/dist/index.esm.js`
`cjs`: `import { useIdleTimer } from 'react-idle-timer/dist/index.cjs.js`

Or to support legacy browsers:

`esm`: `import { useIdleTimer } from 'react-idle-timer/dist/index.legacy.esm.js`
`cjs`: `import { useIdleTimer } from 'react-idle-timer/dist/index.legacy.cjs.js`

**Comment by ravikumar-roundsqr** [comment]
esm: import { useIdleTimer } from 'react-idle-timer/dist/index.legacy.esm.js
cjs: import { useIdleTimer } from 'react-idle-timer/dist/index.legacy.cjs.js
it solved my problem.
Thanks for the help...
