### ISSUE TITLE
Is there something to direct to specific page once timer expires ⚡️ 

### ISSUE THREAD

**Issue by JSDUNIYA** [SupremeTechnopriest/react-idle-timer#375]
### What problem does your feature request solve?

If someone open my domain by clicking link and doesn't do anything on that page/domain, he should be redirected to previous page  from where is clicked that link?

### Describe the solution you are proposing.

Using history Api of js

### Importance

Nice to Have

### Additional Context

- [X] This missing feature presents as a bug.
- [X] This missing feature is forcing me to consider alternatives.

**Comment by SupremeTechnopriest** [comment]
This should be fairly simple to implement:

```ts
const onIdle = () => {
  if (navigation.canGoBack) navigation.back()
}
```

**Comment by JSDUNIYA** [comment]
That's Great!!

**Comment by JSDUNIYA** [comment]
That's Great!!
