### ISSUE TITLE
Using string literals in ref attributes is deprecated

### ISSUE THREAD

**Issue by srMarquinho** [SupremeTechnopriest/react-idle-timer#39]
Following the react-idle-timer docs, the instruction is to use `ref="idleTimer"`.

`ref="idleTimer"` brings me the following warning: `"Using string literals in ref attributes is deprecated (react/no-string-refs)"`

And leading me to https://reactjs.org/docs/refs-and-the-dom.html
> Legacy API: String Refs
If you worked with React before, you might be familiar with an older API where the ref attribute is a string, like "textInput", and the DOM node is accessed as this.refs.textInput. We advise against it because string refs have some issues, are considered legacy, and are likely to be removed in one of the future releases.

In this case, what's is recommended?
If required change I could follow the recommendation and maybe update the docs?

Thank you!

**Comment by maxvfischer** [comment]
Interested in this as well!

**Comment by SupremeTechnopriest** [comment]
Ah yeah react is ever changing. I will give this repository some attention today.

**Comment by SupremeTechnopriest** [comment]
Hey @srMarquinho and @maxvfischer!  I've just pushed the initial commit for the next version of IdleTimer.  I still have a few things to do before I can release it, but the examples in that repository will show you how to do refs with react 16.  Have a peek here:

https://github.com/SupremeTechnopriest/react-idle-timer/blob/next/example/src/App.js#L8
https://github.com/SupremeTechnopriest/react-idle-timer/blob/next/example/src/App.js#L44
https://github.com/SupremeTechnopriest/react-idle-timer/blob/next/example/src/App.js#L82

**Comment by SupremeTechnopriest** [comment]
Hello again!  I just pushed out version 4.  Take a look at the new readme, there were a few breaking changes, but it should only take a few minutes to migrate. Going to close this issue for now, feel free to open another if anything pops up.
