### ISSUE TITLE
🐞 The documentation server is down

### ISSUE THREAD

**Issue by tavershimafx** [SupremeTechnopriest/react-idle-timer#398]
### What happened?

 the documentation server [idletimer.dev](https://idletimer.dev/) is down
 

### Reproduction Steps

```bash
1. type in https://idletimer.dev/ in your browser and see it doesn't open
2.
3.
...
```

### Module Version

5.7.2

### What devices are you seeing the problem on?

Desktop

### Verification

- [X] I have checked for existing closed issues and discussions.

**Comment by SupremeTechnopriest** [comment]
It's up for me. Can you give me some additional logs? What is the response status?
