### ISSUE TITLE
Add listeners with { passive: true } option

### ISSUE THREAD

**Issue by scottc-netflix** [SupremeTechnopriest/react-idle-timer#42]
See here:

https://alligator.io/js/speed-up-scroll-events/

**Comment by SupremeTechnopriest** [comment]
Hey @scottc-netflix, 

Thanks for the tip!  I just released version 4 which adds two new props; `passive` and `capture`.  They both default to true so you only need to set if you want it turned off for some reason.  There are a few breaking changes in v4 so checkout the README before upgrading.

**Comment by mikesobol** [comment]
https://github.com/SupremeTechnopriest/react-idle-timer/blob/9a25457899d2b36aea54000f6ae62bc9c74e24c7/src/index.js#L186-L189

You're not passing the `passive` and `capture` options to `addEventListener`, because there is a closing parenthesis before them.

**Comment by SupremeTechnopriest** [comment]
Nice catch @scottc-netflix.  I reformatted that function so it reads easier. It's pushed up as `4.0.8`
