### ISSUE TITLE
Module not found: Can't resolve 'react-idle-timer'

### ISSUE THREAD

**Issue by shauntrennery** [SupremeTechnopriest/react-idle-timer#44]
Package.json for version 4.0.3 has main set to 'build/index.js'. The build directory is not present in the npm package.

Importing IdleTimer from 'react-idle-timer/dist/index.min.js' is a work around for now.

**Comment by SupremeTechnopriest** [comment]
@shauntrennery thanks for that!  So much changed I missed the small stuff... `4.0.4` will do it for you.  Thanks again!
