### ISSUE TITLE
Start in idle

### ISSUE THREAD

**Issue by fraserhaer** [SupremeTechnopriest/react-idle-timer#45]
Hi I may have missed it, but I was wondering if you can start the timer in its idle state.

The use case is that at the start of the day we switch on the devices, open the app and a call to action is present for any clients who walk in before the idle state (set to 5 minutes) has activated.

Thanks
Fraser

**Comment by SupremeTechnopriest** [comment]
Hwy @fraserhaer. You can set `startOnMount` to false and it will wait for user input to start.  You can also start it manually by calling `idleTimer.restart()`.  Lmk if this does it for you.  If not we might need to add the feature you're looking for.

**Comment by fraserhaer** [comment]
Hi @SupremeTechnopriest thanks for the quick reply.

I don't think the built in functionality covers it, but I might not understand.

Essentially, I want to start the device with the screensaver (and 'click here' call-to-action) already running. I have code to hide the screensaver in `onActive` and show it in `onIdle`.

Setting `startOnMount` to `false` would suit me fine if that first user input would trigger an `onActive` event rather than simply starting the timer internally.

It's not a dealbreaker or anything, but I think it could be useful to anyone making a public display.

**Comment by SupremeTechnopriest** [comment]
Okay let me have a think on it today and we will implement something
tomorrow. I'm afk because it's a holiday in America. I do understand what
you want to do. Just need to think about the best way to implement and
potential side effects.

**Comment by fraserhaer** [comment]
Oh it is too! Happy 4th of July mate :)

I appreciate you looking into it.

**Comment by SupremeTechnopriest** [comment]
Thanks @fraserhaer!  So I just pushed up version `4.0.5` which takes care of this for you.  It was definitely a bug so nice catch there and thanks for running it through the ringer for me. 

IdleTimer was starting in the wrong state when `startOnMount` was set to `false`.  I added a new [test](https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/src/__tests__/index-test.js#L65-L73) to make sure that the state is set correctly and that `onActive` is called on the first user input event. 

If for some reason this doesn't fix it for you please reopen the issue!

**Comment by SupremeTechnopriest** [comment]
Forgot the condition. The latest `4.0.6` is good to go. Should have had my morning tea before getting into this 🍵

**Comment by fraserhaer** [comment]
Cheers mate, works great :)
