### ISSUE TITLE
Question: What happens if the computer goes to sleep?

### ISSUE THREAD

**Issue by HenrikGr** [SupremeTechnopriest/react-idle-timer#53]
Hi, just wanted to say I like this component and thinking about to use it but I wonder what will happens when a computer goes to sleep. Does the timeout function continue running or will it stop?

**Comment by SupremeTechnopriest** [comment]
Hey @HenrikGr, 

Under the covers `IdleTimer` uses a `setTimeout` so it is susceptible to [background tab throttling](https://developers.google.com/web/updates/2017/03/background_tabs) and [sleep/wake pausing](https://stackoverflow.com/questions/6346849/what-happens-to-settimeout-when-the-computer-goes-to-sleep). TLDR; If your computer goes to sleep, `IdleTimer` will be paused and it will resume when the computer awakes. 

Hope this helps!
