### ISSUE TITLE
when wrapping iframe component showing idle most of the time

### ISSUE THREAD

**Issue by veeramarni** [SupremeTechnopriest/react-idle-timer#59]
When I wrap around an iframe editor component, when it goes to ide state it won't comes back to active state even when I have something typed in the editor. It only comes to active state when the mousemoved off and into the browser tab. Does this component suppose to track the key press as well right?

```
      <IdleTimer
        // ref={ref => { this.idleTimer = ref }}
        element={document}
        onActive={this.onActive}
        onIdle={this.onIdle}
        // timeout={this.state.timeout}
        timeout={1000 * 3}
        startOnLoad={true}
      >
        <Frame
          url={remote editor url}
          width="100%"
          height="100%"
          id={this.componentId}
          ref={(ref) => this.frame = ref}
          className="myClassname"
          display="initial"
          position="relative"
          onLoad={this.iframeLoaded()}
          allowFullScreen={true}
        />
      </IdleTimer>
```

**Comment by SupremeTechnopriest** [comment]
In the case of the iFrame, you are going to want to have the IdleTimer component rendered inside the iFrame.  iFrames are almost like separate browser windows.  They have their own set of events.  The way you have it set up here, `IdleTimer` is running on your container app, not your framed app (remote editor url).
