### ISSUE TITLE
Empty IdleTimer tag not working

### ISSUE THREAD

**Issue by fkrauthan** [SupremeTechnopriest/react-idle-timer#6]
If you don't provide any body for IdleTimer it throws an error.

I've looked at the code and I think the problem is that you return a empty string if no children are provided:

```javascript
render() {
    return this.props.children ? this.props.children : '';
  }
```

You probably should return null in that case. Or an empty div/span element.

My current workaround is to use it like this: `<IdleTimer ...><div></div></IdleTimer>`

**Comment by SupremeTechnopriest** [comment]
So there is a bit of debate about usage of this component.  It was originally intended to be a wrapper around your top most component.  

```xml
render() {
    <IdleTimer {...timerProps}>
       <div>{appContent}</div>
    </IdleTimer>
}
```
but it seems people like to instantiate it with no children...

```xml
render() {
    <div>
        <IdleTimer {...timerProps} />
        {otherContent}
    </div>
}
```
I will return null so the component can be used either way.  Thanks for the catch.  Will have a new version up shortly.

**Comment by fkrauthan** [comment]
There are probably use cases for both. I use it as a session monitor that is not always included for example. So I don't wanna use it with children. Its just bad that from 1.2.9 to 1.2.10 the behaviour changed.

**Comment by SupremeTechnopriest** [comment]
v`1.2.11` has been published.  Please enjoy :smile:

**Comment by SupremeTechnopriest** [comment]
@fkrauthan yea sorry about the breaking change, I added a test for that use case so integrations will be smooth.

**Comment by fkrauthan** [comment]
@SupremeTechnopriest no problem. Thanks for the cool library. It was exactly what I needed for a big project and it works like a charm. Great work! :+1:
