### ISSUE TITLE
Does this have Typescript definitions?

### ISSUE THREAD

**Issue by paigeflourin** [SupremeTechnopriest/react-idle-timer#60]
I want to implement this in my project. can this be used with typescript?

**Comment by SupremeTechnopriest** [comment]
Hi @paigeflourin, IdleTImer has been implemented with typescript before but the definitions were never committed. Here is a declaration file by @kamranayub:

```javascript
declare module "react-idle-timer" {
  import * as React from "react";

  class IdleTimer extends React.Component<IdleTimerProps> {
    /**
     * Restore initial state and restart timer
     */
    reset(): void;

    /**
     * Store remaining time and stop timer
     */
    pause(): void;

    /**
     * Resumes a paused timer
     */
    resume(): void;

    /**
     * Time remaining before idle (number of ms)
     */
    getRemainingTime(): number;

    /**
     * How much time has elapsed (timestamp)
     */
    getElapsedTime(): number;

    /**
     * Last time the user was active
     */
    getLastActiveTime(): number;

    /**
     * Returns wether or not the user is idle
     */
    isIdle(): boolean;
  }

  namespace IdleTimer {

  }

  interface IdleTimerProps {
    ref: (ref: IdleTimer) => any;

    /**
     * Activity Timeout in milliseconds default: 1200000
     */
    timeout?: number;

    /**
     * DOM events to listen to default: see [default events](https://github.com/SupremeTechnopriest/react-idle-timer#default-events)
     */
    events?: string[];

    /**
     * Element reference to bind activity listeners to default: document
     */
    element?: Node;

    /**
     * Start the timer on mount default: true
     */
    startOnMount?: boolean;

    /**
     * Bind events passively default: true
     */
    passive?: boolean;

    /**
     * Capture events default: true
     */
    capture?: boolean;

    /**
     * Function to call when user becomes active
     */
    onActive?: () => void;

    /**
     * Function to call when user is idle
     */
    onIdle?: () => void;
  }

  export = IdleTimer;
}
```

You can see this [closed issue](https://github.com/SupremeTechnopriest/react-idle-timer/issues/52).  Feel free to open a Pull Request.  I'll get it pushed up quick.

**Comment by SupremeTechnopriest** [comment]
I added the typescript file to the repository and I will keep it maintained.  See version `4.2.1`

**Comment by mellis481** [comment]
@SupremeTechnopriest Did the `IdleTimer` class' `ref` property get removed from the types at some point?  I see it referenced above as `ref: (ref: IdleTimer) => any;` and it's also referenced in the [component usage](ref: (ref: IdleTimer) => any;) documentation, but I'm not seeing it in my Typescript project.

**Comment by SupremeTechnopriest** [comment]
Let me check on that.

**Comment by SupremeTechnopriest** [comment]
Looks like it did get removed, adding it back and will roll out a patch shortly.

**Comment by SupremeTechnopriest** [comment]
@mellis481 Can you try out `4.6.3-rc.1` by `npm i react-idle-timer@next`?  Should be all set now.

**Comment by SupremeTechnopriest** [comment]
Cool!  WIll be rolling this to the `latest` tag today hopefully. Just working on fixing a few other things. I will update you here when you can switch back.

**Comment by mellis481** [comment]
@SupremeTechnopriest Just checking in to see when the new package can be published.

**Comment by SupremeTechnopriest** [comment]
Hey @mellis481,

Hoping to have this out today.  Just seeing what I can do about supporting CSP.  RegeneratorRuntime is broken IMO, but looking for a work around.  If I come up dry I will just release these fixes today and work on it for another patch.

**Comment by SupremeTechnopriest** [comment]
I should be rolling this out today.  In the mean time you can use:

```ts
// @ts-ignore 
```

to ignore type checking for the ref.  If they don't get back to me today on their issues, I will roll out a patch this evening.

**Comment by SupremeTechnopriest** [comment]
@mellis481 `4.6.3` published to `latest` tag!
