### ISSUE TITLE
pause() issue?

### ISSUE THREAD

**Issue by kkashou** [SupremeTechnopriest/react-idle-timer#61]
Hello,

I am wondering if I put the `this.idleTimer.pause()` inside the onIdle function shouldn't that stop the idle timer, regardless if the user moves the mouse or scroll?

I did noticed that this.idleTimer.pause() = undefined when I console.log that value.

Right now if the user moves the idleTimer gets activated and I don't want no timer to continue if onIdle function is activated.

Thanks!

`
.....

class App extends Component {
    constructor(props) {
        super(props);
        this.idleTimer = null;
        this.timer = null;
        this.state = {
            timeLeft: 30
        };
    }
    onIdle = () => {
        this.props.setSessionModal();
        this.idleTimer.pause();
        this.timer = setInterval(this.countdown, 3000);
    };

    countdown = () => {
        if (this.state.timeLeft === 0) {
            this.props.unAuthUser();
        } else {
            this.setState({ timeLeft: --this.state.timeLeft });
        }
    };

    actionOk = () => {
        clearInterval(this.timer);
        this.setState({ timeLeft: 30 });
        this.idleTimer.reset();
        this.props.setSessionModal();
    };
    render() {
        return (
            <div>
                <IdleTimer
                    ref={ref => {
                        this.idleTimer = ref;
                    }}
                    onIdle={this.onIdle}
                    timeout={5000}
                >
                    {this.props.getSessionModal && (
                        <ModalSession
                            isActive={this.props.getSessionModal}
                            seconds={this.state.timeLeft}
                            actionCancel={this.props.unAuthUser}
                            actionOk={this.actionOk}
                        />
                    )}
                </IdleTimer>
            </div>
        );
    }
}

export default App;`

**Comment by SupremeTechnopriest** [comment]
Hey @kkashou.  Might be a race condition here.  Maybe I can add a prop for you instead.  So you want the idle timer to only fire idle once and then stay idle until you call `reset()`?

**Comment by kkashou** [comment]
@SupremeTechnopriest yeah that would be great if you can add that! Since I need the idle timer to stop running when that function open up a modal with information that the user has to do an action. When do you think you can add that?

Thanks

**Comment by SupremeTechnopriest** [comment]
Im going to do it either tomorrow or this weekend.  Should have a new package on NPM by Monday.  I'd do it now, but I'm a bit swamped at the moment.

**Comment by kkashou** [comment]
@SupremeTechnopriest that would be amazing thank you very much!

**Comment by SupremeTechnopriest** [comment]
@kkashou All set! `4.1.0` is on npm.  The prop you want is called `stopOnIdle`.  Pass that puppy true and you should be g2g!

**Comment by kkashou** [comment]
@SupremeTechnopriest hey there thank you for the quick response! I added the props 

`<IdleTimer
                    ref={ref => {
                        this.idleTimer = ref;
                    }}
                    onIdle={this.onIdle}
                    stopOnIdle={true}
                    timeout={5000}
                />`

But the idle popup doesn't show up anymore when i put that props. Is there something else I need to add?

**Comment by SupremeTechnopriest** [comment]
Hmmm might have missed something in my test cases.  You're saying it doesn't call the initial `onIdle`?  Ill take a look tonight.

**Comment by SupremeTechnopriest** [comment]
@kkashou see how `4.1.1` works out for you

**Comment by kkashou** [comment]
@SupremeTechnopriest - Hmm still didn't do it. :/

The idle timer doesn't pause when onIdle function gets called. It is still running regardless of the props set to true. I'm I missing something?

**Comment by SupremeTechnopriest** [comment]
@kkashou If you have a look at these two tests https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/src/__tests__/index-test.js#L102-L135 it should be doing what you want.  The user goes idle and the timer should not start again when the user becomes active.  It shouldn't call `onActive` on user input either.  If you are checking against the idle state inside `IdleTimer` that might be misleading.  I decided to keep the state accurate, but prevent the timer from restarting and onActive from being called.  

Maybe I misunderstood what you are trying to do?  If you can copy paste all your code here I can try to run it on my side.

**Comment by kkashou** [comment]
@kkashou  - [![Edit yqz8m224o9](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yqz8m224o9)

Here is the code for what I have.  Let me know what you think? I just want to be able to stop the idleTimer when i have a modal box showing. Depending on the action (ok or cancel), cancel will redirect the user and ok will reset the idleTimer to check for inactivity. 

Let me know what you think.

**Comment by SupremeTechnopriest** [comment]
Can you check out this fork?  https://codesandbox.io/s/6vv4jr02o3

**Comment by SupremeTechnopriest** [comment]
Ah never-mind.  I see the issue.  If you dont give additional inputs after clicking ok it works as expected.  However if you give it input again it doesn't time out.  I will add this case to the tests and fix it.

**Comment by kkashou** [comment]
Is there any other command I would need to add? Or everything I have now in my code is good to go?

**Comment by SupremeTechnopriest** [comment]
@kkashou Looks ok on your end.  The one thing I would change is not using `IdleTimer` as a wrapper component.  Weird things can happen to the children state.  I made the change in my fork of your code.  The real fix will be incoming shortly.  Look out for `4.1.2`, Ill test it in your code to make sure it works.

**Comment by SupremeTechnopriest** [comment]
@kkashou Looking good!  Check it out https://codesandbox.io/s/6vv4jr02o3

**Comment by kkashou** [comment]
@SupremeTechnopriest I checked out the link you sent me and still doesn't work. The time still works when you move around once the modal is open and the idle timer gets activated.

**Comment by SupremeTechnopriest** [comment]
@kkashou Are you talking about your timer? The one that counts down from 30?

**Comment by SupremeTechnopriest** [comment]
@kkashou I think i see another bug.  This turned out being quite tricky :)  Pushing `4.1.3` and testing again.

**Comment by kkashou** [comment]
@SupremeTechnopriest - This seems to work! Thank you very much~!!!!

**Comment by SupremeTechnopriest** [comment]
Awesome, I made a few changes in your code. Nothing major!
