### ISSUE TITLE
typo in 'props' section of readme

### ISSUE THREAD

**Issue by aronsonben** [SupremeTechnopriest/react-idle-timer#63]
Hey man. Not sure if this is the right place to contact you regarding this, but there is a typo in the 'props' section of the readme. Instead of having 'onAction' and 'onActive' you have both bullet points saying 'onActive'. Just wanted to let you know, love using this library.

**Comment by SupremeTechnopriest** [comment]
Hey @aronsonben thanks for catching this! It's fixed on the master branch now... Undecided if I want to push a patch to update it on NPM.... I really wish you could just update the readme independently.  Anyway, thanks for using IdleTimer!
