### ISSUE TITLE
Doc error - debounce/throttle is for onAction, not onActive

### ISSUE THREAD

**Issue by moos** [SupremeTechnopriest/react-idle-timer#64]
Set `debounce` for a couple of seconds, then move the mouse -- note "user did something" outputs every 2 seconds.  

Let it become idle then move the mouse -- notice that "user is active" shows immediately.

**Comment by SupremeTechnopriest** [comment]
@moos Thanks for catching this.  I fixed it in 007fab5.  The NPM readme wont be updated until we do another publish.
