### ISSUE TITLE
Disabling the component with `timeout={0}`

### ISSUE THREAD

**Issue by afilp** [SupremeTechnopriest/react-idle-timer#65]
Feature request:

If we use `timeout={0}`, the `IdleTimer` component to not create any timers at all, and just be a pass-through component for its child component (i.e. the `app`).

Why?

I use `location.search` to get `params`. One of them is the `timeout` param. When we want to debug our app, we do not want the `IdleTimer` to reload the page (this is what it now does, after 120 seconds). So we want to disable it without any extra code, by just using `0` as our timeout param.

Of course, we could use a very large number for timeout (still, the timer will be counting) OR reformat the `<IdleTimer />` component to render conditionally.

**Comment by SupremeTechnopriest** [comment]
Hi @afilp!  If the timeout is set to `0` it logically means timeout immediately. If you wanted to remove the timer, catch the 0 in your code and dont render the timer.  You shouldn't be using it as a parent component anyway.  That is deprecated, it has some adverse side effects if you are not super careful with your state updates. 

Something like this:

```javascript
render () {
  const { timeout } = window.location.params
  const options = {
    timeout,
    // any other options
  }

  return (
    <div>
      {timeout && <IdleTimer {...options} />}
      <App />
    </div>
  )
}
```

**Comment by SupremeTechnopriest** [comment]
Edited, you probably need to `parseInt` the param as it comes in as a string.

**Comment by afilp** [comment]
Thanks! I misunderstood the `child` part, it makes sense to use it as such.
