### ISSUE TITLE
Feature: ability to pause events also

### ISSUE THREAD

**Issue by moos** [SupremeTechnopriest/react-idle-timer#67]
After reaching idle state, I'd like the component to be a no-op.  Currently, events are still bound (potential perf issue), and handlers still called (unless stopOnIdle=true).   Calling `this.idleTimer.componentWillUnmount()` does the trick - but it's not semantically correct.

Would prefer a `this.idleTimer.destroy()` (or similar) or have 'stopOnIdle' include events binding also.  Thoughts?

**Comment by SupremeTechnopriest** [comment]
Hey, this is a great idea and probably a common use case. I will get this
implemented ASAP.

**Comment by SupremeTechnopriest** [comment]
@moos Hey buddy, thanks for your input here.  Good stuff.  I implemented dynamic event binding and it is published as version 4.2.0.  The functionality that you requested should happen automagically for you, but if you want to manually bind or unbind the events, you can call the private methods directly `this.idleTimerRef._bindEvents()` and `this.idleTimerRef._unbindEvents()`.

**Comment by moos** [comment]
Works great - thanks.
