### ISSUE TITLE
support serverside

### ISSUE THREAD

**Issue by benmonro** [SupremeTechnopriest/react-idle-timer#7]
I'm using webpack for bundling.  I only use this library in my client but in order to use it in webpack I have to use some code like this:

`if (canUseDOM && enabled) {
            let Timer = require("react-idle-timer").default;`

the reason for this is that if I try to use an import I'll get a build time error:

```
ReferenceError: document is not defined
    at Object.<anonymous> (/Users/bmonro/Documents/Code/nui-redux/ext/@concur/nui-shell/node_modules/react-idle-timer/build/index.js:303:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/bmonro/Documents/Code/nui-redux/ext/@concur/nui-shell/lib/components/IdleTimer.js:15:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

it would be nice if I didn't have to do this and could instead do a normal es6 style import.

**Comment by SupremeTechnopriest** [comment]
Gonna look into this for you right now.

**Comment by benmonro** [comment]
:+1: thanks! :)

**Comment by SupremeTechnopriest** [comment]
Are you webpacking your server code?  You probably shouldn't be.  You should just uglify your server code and maybe obfuscate it if you are concerned about source size. Usually when I structure an application, I have a project for the API ( express, server side logic, etc ) and a separate project from the client ( React, Webpack, Babel ).  I wrote a project generator for the client side called [react-blueprint](https://github.com/SupremeTechnopriest/react-blueprint) you can check out for an example.  However I haven't open sourced an API boilerplate yet.  

I suppose I could move your check into my library, but you should really be requiring this library outside of the browser context.  It depends on being able to bind event listeners to keep track of the users activity.  

Maybe you can try passing another element as the `element` prop?

```xml
import { findDOMNode as $ } from 'react-dom';
<IdleTimer element={${this.refs.yourElement}} />
```

**Comment by benmonro** [comment]
well we have isomorphic code.  we're not wepbacking the server specific stuff, but some of the code is shared.  I believe the problem is that I am exporting a component which uses the IdleTimer at the root level so that the consuming application can just use it like this:
```
import {MyComponentThatUsesTimer} from 'mylib';
```

**Comment by SupremeTechnopriest** [comment]
Ah I see.  What happens if you change `node_modules/react-idle-timer/package.json```.main` to `src/index.js`

**Comment by benmonro** [comment]
that would fail becuase there's no src/index in there.

**Comment by SupremeTechnopriest** [comment]
ah yes, it just installs the build.  How about this.  Can you install `jsdom` and set it up with webpack?  That should solve your issue.

**Comment by SupremeTechnopriest** [comment]
this might be useful [gitter](https://gitter.im/webpack/webpack/archives/2014/09/01)

**Comment by benmonro** [comment]
I found another work around which was to exclude that from my index and just reference directly.  I'd rather not install jsdom for something like this.  I'll have a look at your source and maybe do a PR...

**Comment by SupremeTechnopriest** [comment]
I think I might have something for you.   You can try to install from the isomorphic branch. 

`"react-idle-timer": "git+https://git@github.com/supremetechnoprirest/react-idle-timer.git#isomorphic"`

I exposed the es6 source code as the default and added `IdleTimer.browser` for the webpack build.  Let me know if it works out.

**Comment by SupremeTechnopriest** [comment]
@benmonro So this is working for you serverside? If it is I will address #8 and publish a new version today.

**Comment by benmonro** [comment]
let me try, sorry got distracted

**Comment by benmonro** [comment]
```npm ERR! git clone --template=/Users/bmonro/.npm/_git-remotes/_templates --mirror https://git@github.com/supremetechnoprirest/react-idle-timer.git /Users/bmonro/.npm/_git-remotes/git-https-git-github-com-supremetechnoprirest-react-idle-timer-git-isomorphic-f75604d1: Cloning into bare repository '/Users/bmonro/.npm/_git-remotes/git-https-git-github-com-supremetechnoprirest-react-idle-timer-git-isomorphic-f75604d1'...
npm ERR! git clone --template=/Users/bmonro/.npm/_git-remotes/_templates --mirror https://git@github.com/supremetechnoprirest/react-idle-timer.git /Users/bmonro/.npm/_git-remotes/git-https-git-github-com-supremetechnoprirest-react-idle-timer-git-isomorphic-f75604d1: remote: Invalid username or password.
npm ERR! git clone --template=/Users/bmonro/.npm/_git-remotes/_templates --mirror https://git@github.com/supremetechnoprirest/react-idle-timer.git /Users/bmonro/.npm/_git-remotes/git-https-git-github-com-supremetechnoprirest-react-idle-timer-git-isomorphic-f75604d1: fatal: Authentication failed for 'https://git@github.com/supremetechnoprirest/react-idle-timer.git/'
```

**Comment by n-amabile** [comment]
Any updates on this? I got the same problem here, did someone find a work around?
@SupremeTechnopriest

**Comment by benmonro** [comment]
@n-amabile just the canUseDOM workaround... really no way to do it server side.

**Comment by cchamberlain** [comment]
Does https://github.com/SupremeTechnopriest/react-idle-timer/pull/15 not solve the SSR issues?

**Comment by cchamberlain** [comment]
@benmonro - exactly, it will still render the children that are passed through but will not attempt to access the DOM's document object in componentWillMount which is where the SSR errors would come from. You shouldn't get the `document` is not defined.

**Comment by gidich** [comment]
@benmonro   I've created a pull request #23 which addresses this issue. 

@SupremeTechnopriest Thanks again for this great component, I find I'm using it more and more!

**Comment by SupremeTechnopriest** [comment]
Glad you are finding it useful @gidich!  Thanks to @benmonro for maintaining the project 🙏  I'm going to let him review your PR.  I don't have an isomorphic environment set up to test with at the moment. 

I've actually been spending my time a lot deeper in the front end.  We just released our client side web acceleration and peer to peer cdn: edge**mesh**.  Our customers are seeing page load times decrease by 2 seconds on average, sometimes up to 8 seconds on poorly optimized sites.  Check it out at https://edgemesh.com!  You know how to reach me if you need any help getting started!

**Comment by benmonro** [comment]
I approved the PR but unfortunately i don't have the time nor the privileges to do the merge @SupremeTechnopriest . :)

**Comment by SupremeTechnopriest** [comment]
Okay if you are willing we can get that set up.  Ill take it from here.

**Comment by SupremeTechnopriest** [comment]
Version `1.5.0` released to npm!  Thanks for your contribution!

**Comment by gidich** [comment]
@SupremeTechnopriest @benmonro Thank you both! I'm glad I could contribute something back. 

Thanks for the info on edgemesh, it's really interesting!

**Comment by silesky** [comment]
We are using apollo / SSR. When I attempt to wrap a component I get the red screen of death.
`Server side rendering failed
_this2.props.element.addEventListener is not a function`

any hints?

**Comment by SupremeTechnopriest** [comment]
Hey sorry for the late response.  Im working on an overhaul of this module.  Its long overdue.  This issue will be resolved in the next release.
