### ISSUE TITLE
"Can't perform a React state update on an unmounted component"

### ISSUE THREAD

**Issue by moos** [SupremeTechnopriest/react-idle-timer#71]
My `onIdle` handler does a setState that triggers a re-render of my component which doesn't have IdleTimer.  The sequence is:

```
IdleTimer _toggleIdleState L317
  my onIdle
    my render
      IdleTimer "componentWillUnmount"
IdleTimer _toggleIdleState setState L339
```
resulting in:

> react-dom.development.js:506 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

I could use a setImmediate() in my onIdle -- that might fix the issue.  It may be safer in general to call your setState before calling the callbacks?

**Comment by SupremeTechnopriest** [comment]
Could you post your instantiation and your onIdle code?  Feel free to obfuscate what ever, I just need to see what you are trying to accomplish.

**Comment by moos** [comment]
Correct:

```
  onIdle(e) {
    if (this.hasWarning) {
      this.setState({ warningState: true });
    } else {
      this.expire();
    }
  }

  render() {
    return (
          {this.state.warningState ? <WarningDialog ... /> : <IdleTimer onIdle={this.onIdle.bind(this)}
... />}
  )}
```
Hope that helps.

**Comment by SupremeTechnopriest** [comment]
Published the fix as `4.2.2`.  Should be there on NPM.  If it doesn't fix the issue please reopen this, though I'm pretty sure we are good to go.  I added a test for your use case.

**Comment by moos** [comment]
Seems to have fixed it -- thanks.

**Comment by SupremeTechnopriest** [comment]
Awesome, I just updated your test case and it's all passing.  Nice catch.
