### ISSUE TITLE
Getting Typescript while import

### ISSUE THREAD

**Issue by vishnutsivan** [SupremeTechnopriest/react-idle-timer#72]
Getting following typescript while importing IdleTimer

TS1192: Module '"react-idle-timer"' has no default export. 

![image](https://user-images.githubusercontent.com/18438320/51988967-04903a00-24cc-11e9-97b8-bec135e77591.png)

**Comment by vishnutsivan** [comment]
I think this can solved by updating definition to
`/// <reference types="react"/>

declare module "react-idle-timer" {
  import * as React from "react";

  class IdleTimer extends React.Component<IdleTimerProps> {
    /**
     * Restore initial state and restart timer
     */
    reset(): void;

    /**
     * Store remaining time and stop timer
     */
    pause(): void;

    /**
     * Resumes a paused timer
     */
    resume(): void;

    /**
     * Time remaining before idle (number of ms)
     */
    getRemainingTime(): number;

    /**
     * How much time has elapsed (timestamp)
     */
    getElapsedTime(): number;

    /**
     * Last time the user was active
     */
    getLastActiveTime(): number;

    /**
     * Returns wether or not the user is idle
     */
    isIdle(): boolean;
  }

  interface IdleTimerProps {
    ref: (ref: IdleTimer) => any;

    /**
     * Activity Timeout in milliseconds default: 1200000
     */
    timeout?: number;


    /**
     * DOM events to listen to default: see [default events](https://github.com/SupremeTechnopriest/react-idle-timer#default-events)
     */
    events?: string[];

    /**
     * Function to call when user is idle
     */
    onIdle?: () => void;

    /**
     * Function to call when user becomes active
     */
    onActive?: () => void;

    /**
     * Function to call when user have an activity
     */
    onAction?: () => void;

    /**
     * Debounce the onAction function by setting delay in milliseconds default: 0
     */
    debounce?: number;

    /**
     * Throttle the onAction function by setting delay in milliseconds default: 0
     */
    throttle?: number;

    /**
     * Element reference to bind activity listeners to default: document
     */
    element?: Node;

    /**
     * Start the timer on mount default: true
     */
    startOnMount?: boolean;

    /**
     * Once the user goes idle the IdleTimer will not reset on user input instead, reset() must be called manually to restart the timer default: false
     */
    stopOnIdle?: boolean;

    /**
     * Bind events passively default: true
     */
    passive?: boolean;

    /**
     * Capture events default: true
     */
    capture?: boolean;

  }

  export default IdleTimer;
}
`

**Comment by vishnutsivan** [comment]
I think this change can solve the issue #73

**Comment by SupremeTechnopriest** [comment]
Thanks for your pull request @vishnutsivan.  It's merged in and published as version `4.2.3`.  If there are any further typescript issues please feel free to reopen this issue or create another one.  I have not throughly tested (or even really used) typescript.
