### ISSUE TITLE
TS props interface for ref - why is it mandatory?

### ISSUE THREAD

**Issue by richrout** [SupremeTechnopriest/react-idle-timer#76]
Is there a reason `ref` is mandatory on the typescript props interface? I don't really need in my use-case.

**Comment by SupremeTechnopriest** [comment]
Hey probably because I'm not very familiar with typescript and I took the typedef from a contributor.  The ref isn't required. I will make the change and push a new version.

**Comment by richrout** [comment]
Heh yeah I was just about to comment - you can just remove it and it's all good :)

**Comment by richrout** [comment]
To clarify - you can just remove it completely. It's part of the react `Component` interface

**Comment by SupremeTechnopriest** [comment]
Ah thanks for that.  Coming right up.

**Comment by SupremeTechnopriest** [comment]
`4.2.5` published to npm.  Should do the trick for you.
