### ISSUE TITLE
Warning: setState(...): Can only update a mounting component. 

### ISSUE THREAD

**Issue by jaybe78** [SupremeTechnopriest/react-idle-timer#77]
I'm using this library in an isomorphic application with react 16 and I get a warning
react-dom-server.browser.development.js:104 Warning: setState(...): Can only update a mounting component. This usually means you called setState() outside componentWillMount() on the server. This is a no-op.

I've noticed the warning occurs when I move my mouse

the problem occures in handleEvents()

```
this.setState({
            lastActive: +new Date(), // store when user was last active
            pageX: e.pageX, // update mouse coord
            pageY: e.pageY
        })
```

cause of the issue was `componentWillMount()`
I've moved the _bindEvents in didMount. Also please note that WillMount is deprecated in react16

**Comment by SupremeTechnopriest** [comment]
Yes.  I read about this recently.  I'll look into a fix tomorrow.

**Comment by SupremeTechnopriest** [comment]
Sorry for the delay on this.  Work has been crazy lately.  Version `4.2.6` is on npm and this is addressed.  Thanks again for the report.
