### ISSUE TITLE
setState to Timeout value doesnt re-render the component

### ISSUE THREAD

**Issue by a2441918** [SupremeTechnopriest/react-idle-timer#78]
Hi, I set an initial value to one minute for the timeout and I get the final timeout value from an API and I use a componentDidUpdate and update the state to 10 mins. The callback gets triggered in a minute. Is there any way to override this?

`this.state = {
    timeout: 60000
}

componentDidUpdate(prevProps) {
if(prevProps.idleTimerValue !== this.props.idleTimerValue) {
this.setState({timeout: this.props.idleTimerValue})
}
}

  IdleTimer timeout={this.state.timeout} //renders after a minute />`

P.S: Cant use a component syntax here. No typo's here.

**Comment by SupremeTechnopriest** [comment]
Could you paste your component here in a code block so i can get a better idea of what is going on?
