### ISSUE TITLE
timer doesn't seem to start unless an initial action is taken on the page

### ISSUE THREAD

**Issue by benmonro** [SupremeTechnopriest/react-idle-timer#8]
I've noticed that my timer will not start unless I click or move my mouse over the page.  I'd like the idle timer to start right away regardless of whether or not there's human interaction.

**Comment by SupremeTechnopriest** [comment]
Sure thats an easy one.  Ill make it a bool prop defaulting to `true`.

**Comment by benmonro** [comment]
👍🏻

**Comment by benmonro** [comment]
@SupremeTechnopriest has this been published?

**Comment by SupremeTechnopriest** [comment]
ah sorry not yet.  Got really busy at day job.  Ill do it for you now.

**Comment by SupremeTechnopriest** [comment]
`1.2.12` published

**Comment by SupremeTechnopriest** [comment]
@benmonro you should be good to just upgrade the module.  The default behavior is what you are after.

**Comment by SupremeTechnopriest** [comment]
just now realized should have named the prop `startOnMount` instead of `startOnLoad`  I will probably change this in the next release, but it wont affect you.  You can just ignore that prop all together.
