### ISSUE TITLE
reset() not updating getRemainingTime()

### ISSUE THREAD

**Issue by jont1212** [SupremeTechnopriest/react-idle-timer#81]
My goal for this program is to have a 15 second timeout period with a warning when there are 10 seconds left. At 10 seconds, an alert pops up asking the user if they would like to continue working. If the users clicks OK, the logout timer should be reset back to its original value using this.idleTimer.reset(). However, when the user clicks OK, the getRemainingTime() value does not reset although the session seems to internally keep track of the remaining time. To further clarify, after the user hits OK, the value of getRemainingTime() does not reset, but the _onIdle() method still triggers after 15 seconds of inactivity (from the point after the OK button has been clicked) as if the timer had been reset.

class LogoutTimer extends Component{
    constructor(props) {
        super(props)
        this.idleTimer = null
        this.onIdle = this._onIdle.bind(this)
        this.logout = this.logout.bind(this);
        this.state = {
            timeout: 15000,
            remaining: null,
            warning: 10000,
        }
    }

    // when the component mounts to the DOM for the first time, start the timer
    componentDidMount () {
        this.setState({
            remaining: Math.floor(this.idleTimer.getRemainingTime() / 1000),
            warning: Math.floor(this.state.warning / 1000),
        })
        // set the DOM to update every 1 second in order to check idle time
        setInterval(() => {
            switch(this.state.remaining){
                case(this.state.warning):
                    let response = window.confirm("10 second warning\nDo you want to keep working?")
                    if (response){
                        this.idleTimer.reset()
                        console.log("remaining time: " + this.state.remaining)
                        console.log("RESET TIMER")
                        
                    }
                    else{
                        this.logout()
                    }
                    break;
                default:
                    console.log("remaining: " + this.state.remaining)
                    break;
            }
            this.setState({
                remaining: Math.floor(this.idleTimer.getRemainingTime() / 1000)
            })
        }, 1000)
        
    }

    render() {
        return (
            <IdleTimer
            ref={ref => { this.idleTimer = ref }}
            element={document}
            onIdle={this.onIdle}
            timeout={this.state.timeout}
            />
        );
    }

    // logs out the user
    logout() {
        // logs out the user
    }

    // triggers whenever the user has been idle for the set "timeout" time
    _onIdle(e) {
        console.log('user is idle')
        this.logout();
    }

}

**Comment by SupremeTechnopriest** [comment]
Thanks for the report.  I will look into this asap.

**Comment by SupremeTechnopriest** [comment]
Sorry for the delay on this.  Work has been crazy.  Added a test case for this scenario.  If you pull the latest `4.2.6` from npm you should be g2g.

**Comment by jont1212** [comment]
After pulling 4.2.6, the same code as before does not work. In the background, the timer seems to work, but getRemainingTime() always displays the original `timeout` number. So in the code from before, it logs to the console every 1 second that there are 15 seconds remaining. This happens a total of 15 times in a row before it sees that the user is has not made an action during the timeout period, meaning that the user is idle. It seems that making an action on the screen causes the 15 second timer in the background to refresh, but getRemainingTime() always displays the original `timeout` number every time.

**Comment by SupremeTechnopriest** [comment]
Intereseting.  I will write a more robust test for this case and get to the bottom of it.  Reopening.

**Comment by SupremeTechnopriest** [comment]
Ah I found the issue here. 

```javascript
setInterval(() => {
        switch(this.state.remaining){
            case(this.state.warning):
                let response = window.confirm("10 second warning\nDo you want to keep working?")
                if (response){
                    this.idleTimer.reset()
                    console.log("remaining time: " + this.state.remaining)
                    console.log("RESET TIMER")
                    
                }
                else{
                    this.logout()
                }
                break;
            default:
                console.log("remaining: " + this.state.remaining)
                break;
        }
        this.setState({
            remaining: Math.floor(this.idleTimer.getRemainingTime() / 1000)
        })
    }, 1000)
```

You are setting your own interval.  This is unnecessary as IdleTimer handles the interval for you.  What you should do is set IdleTimers `timeout` to  5 seconds.  Then when it pops, fire your alert and set idle timers timeout to 10 seconds and rebind the events to do what you want.  Just make sure you unbind them properly or you will leak memory. 

Let me know if this helps.

**Comment by pangolingo** [comment]
I can confirm that there's an underlying issue. `getRemainingTime()` does not update until the timeout is reached. This issue occurs in `4.2.6` and is not present in `4.2.5`.

Here's a reproduction: https://codesandbox.io/s/relaxed-moon-1co1w?fontsize=14
Expected: the view updates every second to show the time remaining.
Actual: the view does not update until the timeout is reached: then it shows the time remaining as 0
If you change the version to 4.2.5 it works as expected.

**Comment by SupremeTechnopriest** [comment]
Thanks for confirming @pangolingo.  Rolling up my sleeves now.  Will have this solved shortly.

**Comment by SupremeTechnopriest** [comment]
Hey @jont1212 @pangolingo sorry about this regression.  Something stupid was able to slip through the test suite.  Opening up the examples made the problem very apparent.  Its works 100% as intended in version `4.2.7` on npm.

**Comment by pangolingo** [comment]
Thanks for the fast fix!!

**Comment by SupremeTechnopriest** [comment]
No problem! Thanks for catching the regression 🙂

**Comment by pratiksha08** [comment]
once i reach the idle session i am showing the modal pop up . If no action is taken on pop up for 30 secs i want to redirect the user to logout automatically. Any help would be appreciated.
import React from "react";
import { BrowserRouter, Switch, Route } from "react-router-dom";
import IdleTimer from "react-idle-timer";
import App from "../src/App";
import { IdleTimeOutModal } from "./idleTimePopUp";
import { logOut } from "../src/actioncreators";
import { update } from "ramda";
import Layout from "./../src/Layout";
import { Modal } from "antd";

class Landing extends React.Component {
  state = {
    timeout: 1000 * 60 * 1, // 10 secs
    showModal: false,
    userLoggedIn: false,
    isTimedOut: false
  };

  onAction = e => {
    console.log("user did something", e);
    this.setState({ isTimedOut: false });
  };

  onActive = e => {
    console.log("user is active", e);
    this.setState({ isTimedOut: false });
  };

  onIdle = async e => {
    console.log("user is idle", e);
    const isTimedOut = this.state.isTimedOut;
    if (isTimedOut) {
      logOut();
    } else {
      console.log("user is idle necesaary condition", e);
      await this.setState({ showModal: true });

      console.log("modal value", this.state.showModal);
      await this.idleTimer.reset();

      console.log("timeout", this.state.timeout);
      this.setState({ isTimedOut: true });
      //this.forceUpdate();
      console.log("isTimedOut value", this.state.isTimedOut);
    }
  };

  handleClose = () => {
    this.setState({ showModal: false });
    //this.setState({ timeout: 1000 * 120 * 1 });
  };

  handleLogout = () => {
    this.setState({ showModal: false });
    logOut();
  };

  render() {
    return (
      <>
        <IdleTimer
          ref={ref => {
            this.idleTimer = ref;
          }}
          element={document}
          onActive={this.onActive}
          onIdle={this.onIdle}
          onAction={this.onAction}
          debounce={250}
          timeout={this.state.timeout}
        />

        <div className="">
          <BrowserRouter>
            <Switch>
              <Route
                exact
                path="/bw-hello/" //{`${match.path}helloWorld`}
                component={Layout}
              />
            </Switch>
          </BrowserRouter>
          <Modal
            title="Basic Modal"
            visible={this.state.showModal}
            onOk={this.handleLogout}
            onCancel={this.handleClose}
          >
            Do you want to LogOut? Click Cancel to continue
          </Modal>
          {/* <IdleTimeOutModal
            showModal=
            handleClose={this.handleClose}
            handleLogout={this.handleLogout}
          /> */}
        </div>
      </>
    );
  }
}

export default Landing;
