### ISSUE TITLE
Node.js 9+ support

### ISSUE THREAD

**Issue by marcoscssno** [SupremeTechnopriest/react-idle-timer#82]
When running `yarn add react-idle-timer`, it returns:

`error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".`

My Node.js version: v10.16.0

**Comment by SupremeTechnopriest** [comment]
This is an easy fix. Ill update the package.json but in the mean time you can add the `--ignore-engines` flag when you install and it will work.  Idle time works on all the latest versions of node.

**Comment by SupremeTechnopriest** [comment]
So looked into this and I don't define an engine property in `package.json` as its really a client side lib. So I tried to install with yarn on a clean project and it worked fine for me.  

![image](https://user-images.githubusercontent.com/2261598/60723829-9bcd4380-9ee9-11e9-9c1e-53368a6ebfd9.png)

Hit me back if you still cant get it working. Ill need more info to debug further.
