### ISSUE TITLE
Resume not working

### ISSUE THREAD

**Issue by harrisgeorge202** [SupremeTechnopriest/react-idle-timer#84]
The idle timer is paused when calling pause method but resume does not continue from the paused time. For ex: if pause time is 357703 then when resuming the time will be 342212 something like that

setInterval(async () => {
      if (window.uploadingFiles === "uploading") {
        this.idleTimer.pause();
      }
      if (
        window.uploadingFiles === "done" ||
        window.uploadingFiles === "removed"
      ) {        
        this.idleTimer.resume();
        window.uploadingFiles = "";
      }
      if (this.idleTimer && this.idleTimer.getRemainingTime() < 60000) {
            this.setState({
              visible: true,
              confirmModal: true
            });
        }
    }, 2000);

**Comment by SupremeTechnopriest** [comment]
Hmm.  I will definitely take a look at this and add a test case if one does not exist yet.  However, is it possible that there was some user input after resume?  That would reset remaining time to `timeout`.

**Comment by harrisgeorge202** [comment]
There are chances. If the user is active though. But that is just one scenario there are also chances for no user input.

**Comment by SupremeTechnopriest** [comment]
How about in your test scenario? You are sure you aren't giving it any input?  The reason why I'm asking is that there was a bug in `getRemainingTime()` that I recently fixed.  Im wondering if this is related.

**Comment by harrisgeorge202** [comment]
Yes even when I'm not giving any input the issue stands.

**Comment by SupremeTechnopriest** [comment]
@harrisgeorge202 Thanks for catching this.  I was able to confirm the problem and added test coverage.  Version `4.2.8` is on npm now with this patch.  Let me know if there is any trouble.

**Comment by harrisgeorge202** [comment]
Cool... now it works great... thanks @SupremeTechnopriest
