### ISSUE TITLE
How can I handle start/stop event ?

### ISSUE THREAD

**Issue by mhdungnguyen** [SupremeTechnopriest/react-idle-timer#85]
Your package is very useful for me, but could you explain me some problem.
+ How can I handle start/stop event.
ex: I want to start the timer manually when I signed in the system and stop the timer when I signed out ?
+ Is there any way to handle timer ticks event.
ex: Every minute I want to do something, What should I do to catch this event ?

Thanks you every much sir, good day.

**Comment by SupremeTechnopriest** [comment]
Hello!  Glad you find it useful.  

So for your first bullet point.  The only way to do that currently is at the router level.  Your authenticated view container component is where you create idle timer.  Then its sandboxed to just the authenticated environment and automatically destroyed when you are logged out (assuming its at the router level).  I dont think it would be all that hard to add this functionality for you if you prefer to always have the timer running.

Your second bullet point. Not currently, but I could add a game loop style update function.  It would look something like `onUpdate(delta, tick, now)`.  

How does that sound?

**Comment by SupremeTechnopriest** [comment]
Hey @mhdungnguyen, so I looked into an implementation for this and the closest thing you're going to get is the `onAction` method.  Idle timer works on a `timeout` not an `interval` so implementing a game loop style system is currently out of scope for this project unfortunately.  It would be pretty easy to implement yourself though.  Something like:

```javascript
let tick = 0
let previous = 0
window.requestAnimationFrame(() => {
    const now = performance.now()
    const .delta = (this.time.now - this.previous) / 1000

    // Here is your tick.  Emit your event or whatever
    update(delta, tick, now)

    previous = now
    tick++
})
```

Hope that helps get you where you need to be.  I would also recommend implementing your start and stop with a router like I described a bunch.  Especially if there is auth involved.  It will make your life easier down the road.
