### ISSUE TITLE
Implementation for multiple tabs

### ISSUE THREAD

**Issue by KevinCepria** [SupremeTechnopriest/react-idle-timer#86]
Hello. Are there any ways to implement this to multiple tabs? I have an app where the user will be logged out when a certain amount of inactivity time is met. The problem is if multiple tabs are open, their timers are not sync.

**Comment by SupremeTechnopriest** [comment]
Hello @KevinCepria,

You would have to implement some kind of postmessage system to notify your other tabs of idle events.  I've thought about adding something like this before, but determined it is outside the scope for this project.  There are a number of ways one could implement this and I don't want the library to become too opinionated.

Essentially the flow would be like: 
`Event Fired > postmessage to other tabs > Update other IdleTimer Instances.`

Hope this helps!

**Comment by KevinCepria** [comment]
Hello. Thanks for the response. I checked in to some of your recommendation and will try some of them especially the postmessage. One other question, how do you update an IdleTimer Instance?

**Comment by SupremeTechnopriest** [comment]
Broadcast API would be perfect for this.  Good luck!

**Comment by usamamashkoor** [comment]
Did anyone find any solution for this?

**Comment by SupremeTechnopriest** [comment]
Cross tab support is built in and is pretty robust.  https://idletimer.dev/docs/features/cross-tab

**Comment by usamamashkoor** [comment]
Thanks for letting me know @SupremeTechnopriest :)

**Comment by SupremeTechnopriest** [comment]
No problem @usamamashkoor!
