### ISSUE TITLE
Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by elja** [SupremeTechnopriest/react-idle-timer#87]
When my react application did hot-reload in development mode, let say after changing some values in my component that uses react idle timer, I'm getting: `"Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method."`

I'm using IdleTimer within functional component like this:

```javascript
function SessionExpirationTracker() {
  const timeRef = useRef(null);

  const onUserActive = () => {
  };

  const onUserIdle = () => {
  };

  const onUserAction = () => {
  };

  return (
    <>
      <IdleTimer
        ref={timeRef}
        onActive={onUserActive}
        onAction={onUserAction}
        onIdle={onUserIdle}
        throttle={1000}
        timeout={10 * 1000}
      />
     /* other components goes here */
    </>
  );
}
```

I was able to fix it by adding `force` flag to the `_unbindEvents` function, by default it's set to `false`, and I just trigger `_unbindEvents` with `true` value within `componentWillUnmount`:

```javascript  
componentWillUnmount () {
    // Clear timeout to prevent delayed state changes
    clearTimeout(this.tId)
    this._unbindEvents(true);
}
```

```javascript  
_unbindEvents (force = false) {
    // If we are not in a browser
    // we dont need to unbind events
    if (!IS_BROWSER) return
    // Unbind all events
    const { element, events, passive, capture } = this.props
    const { eventsBound } = this.state
    if (eventsBound || force) {
      events.forEach(e => {
        element.removeEventListener(e, this._handleEvent, {
          capture,
          passive
        })
      })

      this.setState({ eventsBound: false })
    }
  }
```

Why do we even care about setting state on the componentWillUnmount ? Why don't you just remove event listeners from the element?

**Comment by SupremeTechnopriest** [comment]
Hmm... If events are being bound and eventsBound is false then that's a problem.  You shouldn't  have to do all this.  I will create a test for this on Monday.

**Comment by elja** [comment]
Any updates on this one? As a side not, I don't think that we should care about eventsBound when component did unmount, there will be no way to make it alive again after it was unmounted.

**Comment by SupremeTechnopriest** [comment]
@elja True that!  

Been a busy week.  Hopefully I'll have some time in a few hours to take a look.

**Comment by SupremeTechnopriest** [comment]
@elja @iAmao Alrighty this should be good to go now.  `4.2.9` published to npm.
