### ISSUE TITLE
Using timer with functional App component

### ISSUE THREAD

**Issue by rhulse** [SupremeTechnopriest/react-idle-timer#88]
I am trying to use this in a functional component, but I am stuck because I cannot seem to get  ```idleTimer``` set before any function on it are called.

I have tried to convert the example to a functional style, and if I comment out the setInterval loop I can get it to work, and the idle state changes as expected.

With the loop active I get 

```idleTimer.getRemainingTime is not a function```

And the same for the pause/resume buttons.

How would I get this working in a functional component?

Thanks!

**Comment by rhulse** [comment]
I solved this myself - I forgot that you have to use .current on a ref created with useRef. Would you like me to clean this up for you to add the repo as an example of how to do this in a functional component?

**Comment by SupremeTechnopriest** [comment]
Awsome!  Glad you got it solved!  If you would like to clean it up I can add it to the documentation and examples :)

**Comment by iantbarker** [comment]
@rhulse Did you get this working with functional components? If so, would you mind sharing your code with me?

**Comment by rhulse** [comment]
@iantbarker I did get it working.  Have a look at my [Pull request](https://github.com/SupremeTechnopriest/react-idle-timer/pull/91) (which I need to clean up). Let me know if you have any questions.
