### ISSUE TITLE
Question: Is `onIdle` accurate for inactive tabs?

### ISSUE THREAD

**Issue by Moejoe90** [SupremeTechnopriest/react-idle-timer#89]
I can see that under the hood `react-idle-timer` is using `setTimeout` this comes with problems as the counter is not accurate when the tab is not inactive. and this is for good reasons. 

My question is how accurate is `onIdle`? Also why not use `lastActive` as a measure and compare the now time with the last active time. this way you won't need to use `setTimeout` but just compare dates when the user is active.

**Comment by SupremeTechnopriest** [comment]
That wouldn't work in all use cases. If the user does not perform any inputs the idle state would never be updated (which is the main problem this module solves).  As far as backgrounded tabs go, you can utilize the `visibilityChange` listener to know when the page has been backgrounded and do some additional logic there.  For instance, 

You can call `pause()` on the IdleTimer instance (stopping the timeout) and write your own logic, although you can't detect activity on a background tab... 

If your application is sensitive and you need full resolution on the idle checks, you could perform one of these hacks to ensure the backgrounded tab does not get throttled.

_From [google](https://developers.google.com/web/updates/2017/03/background_tabs)_

- Applications playing audio are considered foreground and aren’t throttled.
- Applications with real-time connections (WebSockets and WebRTC), to avoid closing these connections by timeout. The run-timers-once-a-second rule is still applied in these cases.

Hope this helps!

**Comment by mellis481** [comment]
@SupremeTechnopriest If I'm understanding correctly, I believe the author is calling out how the execution of `setTimeout`, etal can be affected when a tab is inactive.  After running into this recently with my implementation of react-idle-timer, it seems like the recommended solution is to use web workers.  That approach is described here: https://stackoverflow.com/a/12522580/1315956

It's my understanding that this would mean that react-idle-timer would need to implement web workers (to be used optionally), but I'm not seeing any references in the source code.

I'm unclear on your response above.  Are you saying react-idle-timer won't be addressing this concern?

**Comment by SupremeTechnopriest** [comment]
I also came across this which could help you out with this issue: 

https://github.com/turuslan/HackTimer

Maybe idle timer can implement something like this behind a flag to hack the timers from being throttled... I am just a bit hesitant to release something like that because it can easily be abused and smoke all of a users resources (think mobile).  There is a reason google implemented timer throttling and I think it should be a very conscious decision if you are going to skirt the feature.  Not just adding a prop to a component.
