### ISSUE TITLE
Can't seem to hit onIdle() before TimeOut

### ISSUE THREAD

**Issue by imsam67** [SupremeTechnopriest/react-idle-timer#90]
I'm using `react-idle-timer` to automatically log users out of my React app after a certain period of inactivity.

I seem to hit the `onIdle()` function fine when the time out value is reached but not before.

I'm trying to show a warning to the user 30 seconds before automatically logging them out but looks like I'm able to hit the `onIdle()` only when the time out value is reached.

**Comment by SupremeTechnopriest** [comment]
Hi @imsam67!

No problem I can help you out here.  So what I have seen done (and have done myself) in the past is to set the timeout to `timeout - 30000`.  This will cause your `onIdle` event to fire 30 seconds early.  From there you can use that event to show your prompt and start your own 30 second timer.  At the end of the 30 second timer, you log them out.  If they click continue, clear your timer and call `reset()` on your IdleTimer instance.  

Hope this helps!  I'm going to close the issue as there is nothing actionable for me here, but feel free to continue to post here if you have any issues.
