### ISSUE TITLE
Calling timer.reset() in onActive callback causes onActive to be immediately fired after the next onIdle

### ISSUE THREAD

**Issue by kalbert312** [SupremeTechnopriest/react-idle-timer#93]
While writing up a test story for my timer component, I noticed an oddity. When I call `timer.reset()` in my `onActive` callback (which I know should be redundant), it will cause the next `onIdle` callback to be almost immediately followed up by `onActive` call.

I was inspecting my code and the package code closely to figure out what I was doing wrong. I 
tracked it down to my `timer.reset()` call on my `onActive` callback, but it raises an interesting thought because I would think that would effectively be a no-op at that point in time?

I was looking through some package code and noticed something potentially dangerous that might be the culprit to my issue:

`toggleIdleState` does not care about the previous idle state, it just does what it says... toggles it based on the current state when it is invoked. The issue is that this function is called in several places with a `setTimeout` call. It seems every time that this function is called (either as `this.toggleIdleState()` or `setTimeout(this.toggleIdleState, timeout)`, it is already known what we would want to flip to. There are several calls to `clearTimeout` which I think would prevent this type of issue but something doesn't seem right.

Without actually tracing my scenario in-depth, I have a couple thoughts:

```javascript
  _toggleIdleState (e) {
    const { idle } = this.state
    // Fire the appropriate action
    // and pass the event through
    const { onActive, onIdle, stopOnIdle } = this.props
    // Toggle the idle state
    this.setState({
      idle: !idle
    }, () => {
      if (idle) {
```
The main danger I see here is that by the time the callback on `setState` is called, `idle` may have changed from previous value somewhere else. React schedules `setState` transactions and it might be possible (though perhaps unlikely? not sure) that idle is changed between this a call to this method and the invocation of the `setState` callback.

This seems like a potentially safer version of this method:
```javascript
  _toggleIdleState (e) {
    // Fire the appropriate action
    // and pass the event through
    // Toggle the idle state
    this.setState((prevState) => ({
      idle: !prevState.idle,
    }), () => {
      const { onActive, onIdle, stopOnIdle } = this.props
      const { idle } = this.state;
      if (!idle) {
        if (!stopOnIdle) {
          this._bindEvents()
          onActive(e)
        }
      } else {
        if (stopOnIdle) {
          // Clear any existing timeout
          clearTimeout(this.tId)
          this.tId = null
          // Unbind events
          this._unbindEvents()
        }
        onIdle(e)
      }
    })
  }
```
This guarantees the correct values from props and state are received when they are needed. Another potential danger with this variant of the method is that is completely dynamic. It makes no assumptions about the current state of things... it just toggles. If this method is not scheduled/cancelled exactly right, it could lead to unintentional toggles.

I may create a PR on this but was hoping to get some feedback first.

**Comment by SupremeTechnopriest** [comment]
For some reason I haven't been receiving emails for new issues?!  Sorry for the delay.  Ill take a look at this after work today.

**Comment by kalbert312** [comment]
No worries. This code sandbox might also help in what I was trying to explain: https://codesandbox.io/embed/react-example-q5okf The setState callbacks are called after the merge of the first and second setState call (`this.state.num` is `2` in the callback of the first setState call and not `1` like what might be expected initially, so it's safer to get the value in the callback rather than the outer scope). Wondering if something similar is going on that caused the original issue. I did not dig into the code much deeper than that.

**Comment by SupremeTechnopriest** [comment]
Going to try to recreate this with a failing test, then we can take it from there.

**Comment by SupremeTechnopriest** [comment]
Okay I see what you are saying @kalbert312.  Thanks for the sandbox that was helpful.  I implemented your suggestion and I will push it to npm shortly. Thanks!

**Comment by SupremeTechnopriest** [comment]
`react-idle-timer@4.2.10` on npm
