### ISSUE TITLE
onIdle event is not triggering consistently on iOS device when timeout is met

### ISSUE THREAD

**Issue by dbcoderain** [SupremeTechnopriest/react-idle-timer#94]
On iOS device the `onIdle` event is not being triggered if timeout is more than 30 minutes.  If you come out of Safari and lock the device.  Then return just after 30 minutes you will observe that the event will have not triggered.

This seems to work as expected, however, if the device is being charged, so it would appear that when the battery is in use the the device is doing some memory management, and the `setTimeout` event is not triggering at the expected intervals.

Tested using iPhone 8 and iPhone XR.

Not tested in Android device.

**Comment by vaseems** [comment]
Same issue when we run inside a citrix. I have added some logs and saw after sometime console statements jumbled like execution of code is not linear.  For smaller timeout it works fine. But for more than 1 hour or so it doesn't work.

**Comment by dbcoderain** [comment]
Issue seems to be `setTimeout` can't be relied upon to hold accurate time if JavaScript engine is put in the background (as that is the case for mobile device, and probably similar for Citrix).

We have a fix locally for this item and will do some more testing and then open a PR.

**Comment by SupremeTechnopriest** [comment]
Thanks for the PR @dbcoderain.  I just merged it in to master.  I'm going to take a look at the rest of the issues and get a new version on npm today.

**Comment by SupremeTechnopriest** [comment]
`4.2.10` on npm
