### ISSUE TITLE
Fix for 94 does not fix Apps in scenario where stopOnIdle is configured and the onIdle event did not fire

### ISSUE THREAD

**Issue by dbcoderain** [SupremeTechnopriest/react-idle-timer#96]
The fix added for issue https://github.com/SupremeTechnopriest/react-idle-timer/issues/94, will not fix the issue if the User has configured `stopOnIdle`

**Comment by SupremeTechnopriest** [comment]
You are truly a boss @dbcoderain. Thanks for the PR.  I'm going to add a test for this case as well and I'll publish a new patch tonight.

**Comment by dbcoderain** [comment]
Good idea about the test 🙌

**Comment by SupremeTechnopriest** [comment]
`react-idle-timer@4.2.11` published!
