### ISSUE TITLE
can't update timeout value of idletimer component

### ISSUE THREAD

**Issue by lakshmisanthi** [SupremeTechnopriest/react-idle-timer#99]
Is it possible to reset the timeout value of the idle timer component?
I need to show a warning message and then need to show an expired message.
Here is my code, please check once

let [time_value, settime_value] = useState( 1000 * 60 * 1)//one min
let [isTimeOut, setisTimeOut] = useState(false);

const _onAction = (e)=>{
    // console.log('user did something', e)
    setisTimeOut(false)}
 
  const _onActive = (e) => {
    // console.log('user is active', e)
    setisTimeOut(false)
  }
 
  const _onIdle = () =>{  
     if(isTimeOut){
       setsessionConfirmation(false);
       setexpired(true)
       autoLogout();
    }else{
      setsessionConfirmation(true); 
      setisTimeOut(true)
      settime_value(1000 * 30 * 1)// 30 seconds
      idleTimer.reset();
    }
  }

return(
     <IdleTimer
        ref={ref => { idleTimer = ref }}
        element={document}
        onActive={_onActive}
        onIdle={_onIdle}
        onAction={_onAction}
        debounce={250}
        timeout={time_value} />
)

My point is when 1min idle state shows confirmatiom modal, then after half min will need to show expired modal. 
Please give me some directions to fix it?

**Comment by SupremeTechnopriest** [comment]
I would use your own timer for the second timeout.  Or a second instance of IdleTImer.  Essentially the first timer pops your modal and starts your second timer.  If second timer expires do whatever, if not stop second timer and reset the first. 

Hope this helps!
